package com.anytty.app

enum class AnyTTYDebugEvent {
    ACTIVITY_CREATED,
    CONNECTION_PLUGIN_LOADED,
    GENERATION_CHANGE_FAILED,
    RESET_PAIRINGS_FAILED,
    BRIDGE_STARTED,
    NETWORK_CHANGED,
    FILE_SAVE_FAILED,
    PERSISTABLE_PERMISSION_FAILED,
    FILE_INFO_FAILED,
}
