// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: termx-remote/protocol/runtimepb/runtime.proto

package runtimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{0}
}

type APIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIRequest) Reset() {
	*x = APIRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRequest) ProtoMessage() {}

func (x *APIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRequest.ProtoReflect.Descriptor instead.
func (*APIRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *APIRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APIRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APIRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type APIResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APIResponse) Reset() {
	*x = APIResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIResponse) ProtoMessage() {}

func (x *APIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIResponse.ProtoReflect.Descriptor instead.
func (*APIResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *APIResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *APIResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *APIResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *APIResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type EventSubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TerminalId    string                 `protobuf:"bytes,2,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Types         []int32                `protobuf:"varint,4,rep,packed,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventSubscribeRequest) Reset() {
	*x = EventSubscribeRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventSubscribeRequest) ProtoMessage() {}

func (x *EventSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventSubscribeRequest.ProtoReflect.Descriptor instead.
func (*EventSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *EventSubscribeRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventSubscribeRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *EventSubscribeRequest) GetTypes() []int32 {
	if x != nil {
		return x.Types
	}
	return nil
}

type EventEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Type              string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	ProtocolType      int32                  `protobuf:"varint,2,opt,name=protocol_type,json=protocolType,proto3" json:"protocol_type,omitempty"`
	TerminalId        string                 `protobuf:"bytes,3,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,4,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	Terminal          *TerminalInventoryItem `protobuf:"bytes,5,opt,name=terminal,proto3" json:"terminal,omitempty"`
	Error             string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *EventEnvelope) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventEnvelope) GetProtocolType() int32 {
	if x != nil {
		return x.ProtocolType
	}
	return 0
}

func (x *EventEnvelope) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *EventEnvelope) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *EventEnvelope) GetTerminal() *TerminalInventoryItem {
	if x != nil {
		return x.Terminal
	}
	return nil
}

func (x *EventEnvelope) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TerminalInventoryItem struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	TerminalId                 string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Name                       string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State                      string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Command                    []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Cols                       int32                  `protobuf:"varint,5,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows                       int32                  `protobuf:"varint,6,opt,name=rows,proto3" json:"rows,omitempty"`
	Cwd                        string                 `protobuf:"bytes,7,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Environment                string                 `protobuf:"bytes,8,opt,name=environment,proto3" json:"environment,omitempty"`
	SizeLocked                 bool                   `protobuf:"varint,9,opt,name=size_locked,json=sizeLocked,proto3" json:"size_locked,omitempty"`
	SizeLockMode               string                 `protobuf:"bytes,10,opt,name=size_lock_mode,json=sizeLockMode,proto3" json:"size_lock_mode,omitempty"`
	ResizeOwnership            *ResizeOwnership       `protobuf:"bytes,11,opt,name=resize_ownership,json=resizeOwnership,proto3" json:"resize_ownership,omitempty"`
	ResizeOwnerAttachmentCount int32                  `protobuf:"varint,12,opt,name=resize_owner_attachment_count,json=resizeOwnerAttachmentCount,proto3" json:"resize_owner_attachment_count,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TerminalInventoryItem) Reset() {
	*x = TerminalInventoryItem{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalInventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalInventoryItem) ProtoMessage() {}

func (x *TerminalInventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalInventoryItem.ProtoReflect.Descriptor instead.
func (*TerminalInventoryItem) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *TerminalInventoryItem) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TerminalInventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TerminalInventoryItem) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *TerminalInventoryItem) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TerminalInventoryItem) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *TerminalInventoryItem) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *TerminalInventoryItem) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *TerminalInventoryItem) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *TerminalInventoryItem) GetSizeLocked() bool {
	if x != nil {
		return x.SizeLocked
	}
	return false
}

func (x *TerminalInventoryItem) GetSizeLockMode() string {
	if x != nil {
		return x.SizeLockMode
	}
	return ""
}

func (x *TerminalInventoryItem) GetResizeOwnership() *ResizeOwnership {
	if x != nil {
		return x.ResizeOwnership
	}
	return nil
}

func (x *TerminalInventoryItem) GetResizeOwnerAttachmentCount() int32 {
	if x != nil {
		return x.ResizeOwnerAttachmentCount
	}
	return 0
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *Size) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Size) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type ResizeOwnership struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OwnerAttachmentId string                 `protobuf:"bytes,1,opt,name=owner_attachment_id,json=ownerAttachmentId,proto3" json:"owner_attachment_id,omitempty"`
	OwnerSurfaceId    string                 `protobuf:"bytes,2,opt,name=owner_surface_id,json=ownerSurfaceId,proto3" json:"owner_surface_id,omitempty"`
	OwnerViewId       string                 `protobuf:"bytes,3,opt,name=owner_view_id,json=ownerViewId,proto3" json:"owner_view_id,omitempty"`
	OwnerRemoteAddr   string                 `protobuf:"bytes,4,opt,name=owner_remote_addr,json=ownerRemoteAddr,proto3" json:"owner_remote_addr,omitempty"`
	Size              *Size                  `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	SizeLocked        bool                   `protobuf:"varint,6,opt,name=size_locked,json=sizeLocked,proto3" json:"size_locked,omitempty"`
	Epoch             uint64                 `protobuf:"varint,7,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResizeOwnership) Reset() {
	*x = ResizeOwnership{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeOwnership) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeOwnership) ProtoMessage() {}

func (x *ResizeOwnership) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeOwnership.ProtoReflect.Descriptor instead.
func (*ResizeOwnership) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{8}
}

func (x *ResizeOwnership) GetOwnerAttachmentId() string {
	if x != nil {
		return x.OwnerAttachmentId
	}
	return ""
}

func (x *ResizeOwnership) GetOwnerSurfaceId() string {
	if x != nil {
		return x.OwnerSurfaceId
	}
	return ""
}

func (x *ResizeOwnership) GetOwnerViewId() string {
	if x != nil {
		return x.OwnerViewId
	}
	return ""
}

func (x *ResizeOwnership) GetOwnerRemoteAddr() string {
	if x != nil {
		return x.OwnerRemoteAddr
	}
	return ""
}

func (x *ResizeOwnership) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *ResizeOwnership) GetSizeLocked() bool {
	if x != nil {
		return x.SizeLocked
	}
	return false
}

func (x *ResizeOwnership) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type TerminalListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Terminals     []*TerminalInventoryItem `protobuf:"bytes,1,rep,name=terminals,proto3" json:"terminals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalListResponse) Reset() {
	*x = TerminalListResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalListResponse) ProtoMessage() {}

func (x *TerminalListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalListResponse.ProtoReflect.Descriptor instead.
func (*TerminalListResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *TerminalListResponse) GetTerminals() []*TerminalInventoryItem {
	if x != nil {
		return x.Terminals
	}
	return nil
}

type TerminalDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalDirectoryRequest) Reset() {
	*x = TerminalDirectoryRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalDirectoryRequest) ProtoMessage() {}

func (x *TerminalDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalDirectoryRequest.ProtoReflect.Descriptor instead.
func (*TerminalDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *TerminalDirectoryRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

type TerminalDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalDirectoryResponse) Reset() {
	*x = TerminalDirectoryResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalDirectoryResponse) ProtoMessage() {}

func (x *TerminalDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalDirectoryResponse.ProtoReflect.Descriptor instead.
func (*TerminalDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *TerminalDirectoryResponse) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TerminalDirectoryResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TerminalDirectoryResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type TerminalCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Command       []string               `protobuf:"bytes,2,rep,name=command,proto3" json:"command,omitempty"`
	Dir           string                 `protobuf:"bytes,3,opt,name=dir,proto3" json:"dir,omitempty"`
	Env           []string               `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalCreateRequest) Reset() {
	*x = TerminalCreateRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalCreateRequest) ProtoMessage() {}

func (x *TerminalCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalCreateRequest.ProtoReflect.Descriptor instead.
func (*TerminalCreateRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{12}
}

func (x *TerminalCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TerminalCreateRequest) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *TerminalCreateRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

func (x *TerminalCreateRequest) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *TerminalCreateRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TerminalSetMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalSetMetadataRequest) Reset() {
	*x = TerminalSetMetadataRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalSetMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalSetMetadataRequest) ProtoMessage() {}

func (x *TerminalSetMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalSetMetadataRequest.ProtoReflect.Descriptor instead.
func (*TerminalSetMetadataRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{13}
}

func (x *TerminalSetMetadataRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *TerminalSetMetadataRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TerminalSetMetadataRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TerminalIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalIDRequest) Reset() {
	*x = TerminalIDRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalIDRequest) ProtoMessage() {}

func (x *TerminalIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalIDRequest.ProtoReflect.Descriptor instead.
func (*TerminalIDRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{14}
}

func (x *TerminalIDRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

type StorageEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	Version       uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageEntry) Reset() {
	*x = StorageEntry{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageEntry) ProtoMessage() {}

func (x *StorageEntry) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageEntry.ProtoReflect.Descriptor instead.
func (*StorageEntry) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{15}
}

func (x *StorageEntry) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StorageEntry) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StorageEntry) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StorageEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageEntry) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StorageEntry) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *StorageEntry) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type StorageGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageGetRequest) Reset() {
	*x = StorageGetRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageGetRequest) ProtoMessage() {}

func (x *StorageGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageGetRequest.ProtoReflect.Descriptor instead.
func (*StorageGetRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{16}
}

func (x *StorageGetRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StorageGetRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StorageGetRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StorageGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StoragePutRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppId           string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Scope           string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerId         string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Key             string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Value           []byte                 `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	CheckVersion    bool                   `protobuf:"varint,6,opt,name=check_version,json=checkVersion,proto3" json:"check_version,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,7,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoragePutRequest) Reset() {
	*x = StoragePutRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoragePutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoragePutRequest) ProtoMessage() {}

func (x *StoragePutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoragePutRequest.ProtoReflect.Descriptor instead.
func (*StoragePutRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{17}
}

func (x *StoragePutRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StoragePutRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StoragePutRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StoragePutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoragePutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *StoragePutRequest) GetCheckVersion() bool {
	if x != nil {
		return x.CheckVersion
	}
	return false
}

func (x *StoragePutRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type StorageDeleteRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AppId           string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Scope           string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerId         string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Key             string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	CheckVersion    bool                   `protobuf:"varint,5,opt,name=check_version,json=checkVersion,proto3" json:"check_version,omitempty"`
	ExpectedVersion uint64                 `protobuf:"varint,6,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StorageDeleteRequest) Reset() {
	*x = StorageDeleteRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteRequest) ProtoMessage() {}

func (x *StorageDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteRequest.ProtoReflect.Descriptor instead.
func (*StorageDeleteRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{18}
}

func (x *StorageDeleteRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StorageDeleteRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StorageDeleteRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StorageDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageDeleteRequest) GetCheckVersion() bool {
	if x != nil {
		return x.CheckVersion
	}
	return false
}

func (x *StorageDeleteRequest) GetExpectedVersion() uint64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type StorageDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Version       uint64                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageDeleteResponse) Reset() {
	*x = StorageDeleteResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageDeleteResponse) ProtoMessage() {}

func (x *StorageDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageDeleteResponse.ProtoReflect.Descriptor instead.
func (*StorageDeleteResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{19}
}

func (x *StorageDeleteResponse) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StorageDeleteResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StorageDeleteResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StorageDeleteResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageDeleteResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *StorageDeleteResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type StorageListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Prefix        string                 `protobuf:"bytes,4,opt,name=prefix,proto3" json:"prefix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageListRequest) Reset() {
	*x = StorageListRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageListRequest) ProtoMessage() {}

func (x *StorageListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageListRequest.ProtoReflect.Descriptor instead.
func (*StorageListRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{20}
}

func (x *StorageListRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *StorageListRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *StorageListRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *StorageListRequest) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

type StorageListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*StorageEntry        `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageListResponse) Reset() {
	*x = StorageListResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageListResponse) ProtoMessage() {}

func (x *StorageListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageListResponse.ProtoReflect.Descriptor instead.
func (*StorageListResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{21}
}

func (x *StorageListResponse) GetEntries() []*StorageEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FilePathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePathRequest) Reset() {
	*x = FilePathRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePathRequest) ProtoMessage() {}

func (x *FilePathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePathRequest.ProtoReflect.Descriptor instead.
func (*FilePathRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{22}
}

func (x *FilePathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{23}
}

func (x *FileListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileListRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	ModTime       string                 `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`
	LinkTarget    string                 `protobuf:"bytes,6,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	ChildCount    *int32                 `protobuf:"varint,7,opt,name=child_count,json=childCount,proto3,oneof" json:"child_count,omitempty"`
	HardLink      bool                   `protobuf:"varint,8,opt,name=hard_link,json=hardLink,proto3" json:"hard_link,omitempty"`
	LinkCount     uint64                 `protobuf:"varint,9,opt,name=link_count,json=linkCount,proto3" json:"link_count,omitempty"`
	Inode         uint64                 `protobuf:"varint,10,opt,name=inode,proto3" json:"inode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{24}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileEntry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FileEntry) GetModTime() string {
	if x != nil {
		return x.ModTime
	}
	return ""
}

func (x *FileEntry) GetLinkTarget() string {
	if x != nil {
		return x.LinkTarget
	}
	return ""
}

func (x *FileEntry) GetChildCount() int32 {
	if x != nil && x.ChildCount != nil {
		return *x.ChildCount
	}
	return 0
}

func (x *FileEntry) GetHardLink() bool {
	if x != nil {
		return x.HardLink
	}
	return false
}

func (x *FileEntry) GetLinkCount() uint64 {
	if x != nil {
		return x.LinkCount
	}
	return 0
}

func (x *FileEntry) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Entries       []*FileEntry           `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	Parent        string                 `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{25}
}

func (x *FileListResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileListResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FileListResponse) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *FileListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type FilePathResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePathResponse) Reset() {
	*x = FilePathResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePathResponse) ProtoMessage() {}

func (x *FilePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePathResponse.ProtoReflect.Descriptor instead.
func (*FilePathResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{26}
}

func (x *FilePathResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type FileRenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRenameRequest) Reset() {
	*x = FileRenameRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRenameRequest) ProtoMessage() {}

func (x *FileRenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRenameRequest.ProtoReflect.Descriptor instead.
func (*FileRenameRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{27}
}

func (x *FileRenameRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileRenameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type FileMultiPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMultiPathRequest) Reset() {
	*x = FileMultiPathRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMultiPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMultiPathRequest) ProtoMessage() {}

func (x *FileMultiPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMultiPathRequest.ProtoReflect.Descriptor instead.
func (*FileMultiPathRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{28}
}

func (x *FileMultiPathRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

type FileCopyMoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paths         []string               `protobuf:"bytes,1,rep,name=paths,proto3" json:"paths,omitempty"`
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCopyMoveRequest) Reset() {
	*x = FileCopyMoveRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCopyMoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCopyMoveRequest) ProtoMessage() {}

func (x *FileCopyMoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCopyMoveRequest.ProtoReflect.Descriptor instead.
func (*FileCopyMoveRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{29}
}

func (x *FileCopyMoveRequest) GetPaths() []string {
	if x != nil {
		return x.Paths
	}
	return nil
}

func (x *FileCopyMoveRequest) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

type FileOperationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Dest          string                 `protobuf:"bytes,2,opt,name=dest,proto3" json:"dest,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOperationResult) Reset() {
	*x = FileOperationResult{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOperationResult) ProtoMessage() {}

func (x *FileOperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOperationResult.ProtoReflect.Descriptor instead.
func (*FileOperationResult) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{30}
}

func (x *FileOperationResult) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *FileOperationResult) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *FileOperationResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileCopyMoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Affected      int32                  `protobuf:"varint,1,opt,name=affected,proto3" json:"affected,omitempty"`
	Results       []*FileOperationResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCopyMoveResponse) Reset() {
	*x = FileCopyMoveResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCopyMoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCopyMoveResponse) ProtoMessage() {}

func (x *FileCopyMoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCopyMoveResponse.ProtoReflect.Descriptor instead.
func (*FileCopyMoveResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{31}
}

func (x *FileCopyMoveResponse) GetAffected() int32 {
	if x != nil {
		return x.Affected
	}
	return 0
}

func (x *FileCopyMoveResponse) GetResults() []*FileOperationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type FileDeleteError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDeleteError) Reset() {
	*x = FileDeleteError{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDeleteError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteError) ProtoMessage() {}

func (x *FileDeleteError) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteError.ProtoReflect.Descriptor instead.
func (*FileDeleteError) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{32}
}

func (x *FileDeleteError) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDeleteError) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FileBatchDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       int32                  `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Errors        []*FileDeleteError     `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileBatchDeleteResponse) Reset() {
	*x = FileBatchDeleteResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileBatchDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileBatchDeleteResponse) ProtoMessage() {}

func (x *FileBatchDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileBatchDeleteResponse.ProtoReflect.Descriptor instead.
func (*FileBatchDeleteResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{33}
}

func (x *FileBatchDeleteResponse) GetDeleted() int32 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *FileBatchDeleteResponse) GetErrors() []*FileDeleteError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type FilePreviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	MaxSize       int64                  `protobuf:"varint,2,opt,name=max_size,json=maxSize,proto3" json:"max_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePreviewRequest) Reset() {
	*x = FilePreviewRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePreviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePreviewRequest) ProtoMessage() {}

func (x *FilePreviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePreviewRequest.ProtoReflect.Descriptor instead.
func (*FilePreviewRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{34}
}

func (x *FilePreviewRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilePreviewRequest) GetMaxSize() int64 {
	if x != nil {
		return x.MaxSize
	}
	return 0
}

type FilePreviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MimeType      string                 `protobuf:"bytes,4,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	IsText        bool                   `protobuf:"varint,6,opt,name=is_text,json=isText,proto3" json:"is_text,omitempty"`
	PreviewLimit  int64                  `protobuf:"varint,7,opt,name=preview_limit,json=previewLimit,proto3" json:"preview_limit,omitempty"`
	Content       string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	ContentBase64 string                 `protobuf:"bytes,9,opt,name=content_base64,json=contentBase64,proto3" json:"content_base64,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePreviewResponse) Reset() {
	*x = FilePreviewResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePreviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePreviewResponse) ProtoMessage() {}

func (x *FilePreviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePreviewResponse.ProtoReflect.Descriptor instead.
func (*FilePreviewResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{35}
}

func (x *FilePreviewResponse) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FilePreviewResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FilePreviewResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FilePreviewResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FilePreviewResponse) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *FilePreviewResponse) GetIsText() bool {
	if x != nil {
		return x.IsText
	}
	return false
}

func (x *FilePreviewResponse) GetPreviewLimit() int64 {
	if x != nil {
		return x.PreviewLimit
	}
	return 0
}

func (x *FilePreviewResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FilePreviewResponse) GetContentBase64() string {
	if x != nil {
		return x.ContentBase64
	}
	return ""
}

type FileDownloadInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	TransferId    string                 `protobuf:"bytes,4,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadInitRequest) Reset() {
	*x = FileDownloadInitRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadInitRequest) ProtoMessage() {}

func (x *FileDownloadInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadInitRequest.ProtoReflect.Descriptor instead.
func (*FileDownloadInitRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{36}
}

func (x *FileDownloadInitRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDownloadInitRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileDownloadInitRequest) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FileDownloadInitRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

type FileDownloadInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,4,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Offset        int64                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        int64                  `protobuf:"varint,6,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDownloadInitResponse) Reset() {
	*x = FileDownloadInitResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDownloadInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDownloadInitResponse) ProtoMessage() {}

func (x *FileDownloadInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDownloadInitResponse.ProtoReflect.Descriptor instead.
func (*FileDownloadInitResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{37}
}

func (x *FileDownloadInitResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileDownloadInitResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileDownloadInitResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileDownloadInitResponse) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *FileDownloadInitResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FileDownloadInitResponse) GetLength() int64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type FileUploadInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	ResumeId      string                 `protobuf:"bytes,3,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadInitRequest) Reset() {
	*x = FileUploadInitRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadInitRequest) ProtoMessage() {}

func (x *FileUploadInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadInitRequest.ProtoReflect.Descriptor instead.
func (*FileUploadInitRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{38}
}

func (x *FileUploadInitRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileUploadInitRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileUploadInitRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

type FileUploadInitResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TransferId     string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	ChunkSize      int32                  `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	UploadedOffset int64                  `protobuf:"varint,3,opt,name=uploaded_offset,json=uploadedOffset,proto3" json:"uploaded_offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FileUploadInitResponse) Reset() {
	*x = FileUploadInitResponse{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadInitResponse) ProtoMessage() {}

func (x *FileUploadInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadInitResponse.ProtoReflect.Descriptor instead.
func (*FileUploadInitResponse) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{39}
}

func (x *FileUploadInitResponse) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

func (x *FileUploadInitResponse) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *FileUploadInitResponse) GetUploadedOffset() int64 {
	if x != nil {
		return x.UploadedOffset
	}
	return 0
}

type FileUploadCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransferId    string                 `protobuf:"bytes,1,opt,name=transfer_id,json=transferId,proto3" json:"transfer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUploadCompleteRequest) Reset() {
	*x = FileUploadCompleteRequest{}
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUploadCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUploadCompleteRequest) ProtoMessage() {}

func (x *FileUploadCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUploadCompleteRequest.ProtoReflect.Descriptor instead.
func (*FileUploadCompleteRequest) Descriptor() ([]byte, []int) {
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP(), []int{40}
}

func (x *FileUploadCompleteRequest) GetTransferId() string {
	if x != nil {
		return x.TransferId
	}
	return ""
}

var File_termx_remote_protocol_runtimepb_runtime_proto protoreflect.FileDescriptor

const file_termx_remote_protocol_runtimepb_runtime_proto_rawDesc = "" +
	"\n" +
	"-termx-remote/protocol/runtimepb/runtime.proto\x12\x16termx.remote.runtimepb\"\a\n" +
	"\x05Empty\"\\\n" +
	"\n" +
	"APIRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"_\n" +
	"\vAPIResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\" \n" +
	"\x0eStatusResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"b\n" +
	"\x15EventSubscribeRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1f\n" +
	"\vterminal_id\x18\x02 \x01(\tR\n" +
	"terminalId\x12\x14\n" +
	"\x05types\x18\x04 \x03(\x05R\x05types\"\xfa\x01\n" +
	"\rEventEnvelope\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12#\n" +
	"\rprotocol_type\x18\x02 \x01(\x05R\fprotocolType\x12\x1f\n" +
	"\vterminal_id\x18\x03 \x01(\tR\n" +
	"terminalId\x12.\n" +
	"\x13timestamp_unix_nano\x18\x04 \x01(\x03R\x11timestampUnixNano\x12I\n" +
	"\bterminal\x18\x05 \x01(\v2-.termx.remote.runtimepb.TerminalInventoryItemR\bterminal\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"\xb6\x03\n" +
	"\x15TerminalInventoryItem\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x12\n" +
	"\x04cols\x18\x05 \x01(\x05R\x04cols\x12\x12\n" +
	"\x04rows\x18\x06 \x01(\x05R\x04rows\x12\x10\n" +
	"\x03cwd\x18\a \x01(\tR\x03cwd\x12 \n" +
	"\venvironment\x18\b \x01(\tR\venvironment\x12\x1f\n" +
	"\vsize_locked\x18\t \x01(\bR\n" +
	"sizeLocked\x12$\n" +
	"\x0esize_lock_mode\x18\n" +
	" \x01(\tR\fsizeLockMode\x12R\n" +
	"\x10resize_ownership\x18\v \x01(\v2'.termx.remote.runtimepb.ResizeOwnershipR\x0fresizeOwnership\x12A\n" +
	"\x1dresize_owner_attachment_count\x18\f \x01(\x05R\x1aresizeOwnerAttachmentCount\".\n" +
	"\x04Size\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\xa4\x02\n" +
	"\x0fResizeOwnership\x12.\n" +
	"\x13owner_attachment_id\x18\x01 \x01(\tR\x11ownerAttachmentId\x12(\n" +
	"\x10owner_surface_id\x18\x02 \x01(\tR\x0eownerSurfaceId\x12\"\n" +
	"\rowner_view_id\x18\x03 \x01(\tR\vownerViewId\x12*\n" +
	"\x11owner_remote_addr\x18\x04 \x01(\tR\x0fownerRemoteAddr\x120\n" +
	"\x04size\x18\x05 \x01(\v2\x1c.termx.remote.runtimepb.SizeR\x04size\x12\x1f\n" +
	"\vsize_locked\x18\x06 \x01(\bR\n" +
	"sizeLocked\x12\x14\n" +
	"\x05epoch\x18\a \x01(\x04R\x05epoch\"c\n" +
	"\x14TerminalListResponse\x12K\n" +
	"\tterminals\x18\x01 \x03(\v2-.termx.remote.runtimepb.TerminalInventoryItemR\tterminals\";\n" +
	"\x18TerminalDirectoryRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\"h\n" +
	"\x19TerminalDirectoryResponse\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\"\xef\x01\n" +
	"\x15TerminalCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\acommand\x18\x02 \x03(\tR\acommand\x12\x10\n" +
	"\x03dir\x18\x03 \x01(\tR\x03dir\x12\x10\n" +
	"\x03env\x18\x04 \x03(\tR\x03env\x12K\n" +
	"\x04tags\x18\x05 \x03(\v27.termx.remote.runtimepb.TerminalCreateRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdc\x01\n" +
	"\x1aTerminalSetMetadataRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12P\n" +
	"\x04tags\x18\x03 \x03(\v2<.termx.remote.runtimepb.TerminalSetMetadataRequest.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x11TerminalIDRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\"\xb7\x01\n" +
	"\fStorageEntry\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\"m\n" +
	"\x11StorageGetRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"\xd3\x01\n" +
	"\x11StoragePutRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12#\n" +
	"\rcheck_version\x18\x06 \x01(\bR\fcheckVersion\x12)\n" +
	"\x10expected_version\x18\a \x01(\x04R\x0fexpectedVersion\"\xc0\x01\n" +
	"\x14StorageDeleteRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12#\n" +
	"\rcheck_version\x18\x05 \x01(\bR\fcheckVersion\x12)\n" +
	"\x10expected_version\x18\x06 \x01(\x04R\x0fexpectedVersion\"\xa5\x01\n" +
	"\x15StorageDeleteResponse\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x04R\aversion\"t\n" +
	"\x12StorageListRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\x12\x16\n" +
	"\x06prefix\x18\x04 \x01(\tR\x06prefix\"U\n" +
	"\x13StorageListResponse\x12>\n" +
	"\aentries\x18\x01 \x03(\v2$.termx.remote.runtimepb.StorageEntryR\aentries\"%\n" +
	"\x0fFilePathRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"S\n" +
	"\x0fFileListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x9f\x02\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x19\n" +
	"\bmod_time\x18\x05 \x01(\tR\amodTime\x12\x1f\n" +
	"\vlink_target\x18\x06 \x01(\tR\n" +
	"linkTarget\x12$\n" +
	"\vchild_count\x18\a \x01(\x05H\x00R\n" +
	"childCount\x88\x01\x01\x12\x1b\n" +
	"\thard_link\x18\b \x01(\bR\bhardLink\x12\x1d\n" +
	"\n" +
	"link_count\x18\t \x01(\x04R\tlinkCount\x12\x14\n" +
	"\x05inode\x18\n" +
	" \x01(\x04R\x05inodeB\x0e\n" +
	"\f_child_count\"\x91\x01\n" +
	"\x10FileListResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12;\n" +
	"\aentries\x18\x02 \x03(\v2!.termx.remote.runtimepb.FileEntryR\aentries\x12\x16\n" +
	"\x06parent\x18\x03 \x01(\tR\x06parent\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"&\n" +
	"\x10FilePathResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"B\n" +
	"\x11FileRenameRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\",\n" +
	"\x14FileMultiPathRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\"?\n" +
	"\x13FileCopyMoveRequest\x12\x14\n" +
	"\x05paths\x18\x01 \x03(\tR\x05paths\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\"W\n" +
	"\x13FileOperationResult\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04dest\x18\x02 \x01(\tR\x04dest\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"y\n" +
	"\x14FileCopyMoveResponse\x12\x1a\n" +
	"\baffected\x18\x01 \x01(\x05R\baffected\x12E\n" +
	"\aresults\x18\x02 \x03(\v2+.termx.remote.runtimepb.FileOperationResultR\aresults\";\n" +
	"\x0fFileDeleteError\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"t\n" +
	"\x17FileBatchDeleteResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\x05R\adeleted\x12?\n" +
	"\x06errors\x18\x02 \x03(\v2'.termx.remote.runtimepb.FileDeleteErrorR\x06errors\"C\n" +
	"\x12FilePreviewRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x19\n" +
	"\bmax_size\x18\x02 \x01(\x03R\amaxSize\"\x89\x02\n" +
	"\x13FilePreviewResponse\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1b\n" +
	"\tmime_type\x18\x04 \x01(\tR\bmimeType\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x17\n" +
	"\ais_text\x18\x06 \x01(\bR\x06isText\x12#\n" +
	"\rpreview_limit\x18\a \x01(\x03R\fpreviewLimit\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12%\n" +
	"\x0econtent_base64\x18\t \x01(\tR\rcontentBase64\"~\n" +
	"\x17FileDownloadInitRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x03R\x06length\x12\x1f\n" +
	"\vtransfer_id\x18\x04 \x01(\tR\n" +
	"transferId\"\xb2\x01\n" +
	"\x18FileDownloadInitResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x04 \x01(\x05R\tchunkSize\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x03R\x06offset\x12\x16\n" +
	"\x06length\x18\x06 \x01(\x03R\x06length\"\\\n" +
	"\x15FileUploadInitRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\x12\x1b\n" +
	"\tresume_id\x18\x03 \x01(\tR\bresumeId\"\x81\x01\n" +
	"\x16FileUploadInitResponse\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferId\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\x05R\tchunkSize\x12'\n" +
	"\x0fuploaded_offset\x18\x03 \x01(\x03R\x0euploadedOffset\"<\n" +
	"\x19FileUploadCompleteRequest\x12\x1f\n" +
	"\vtransfer_id\x18\x01 \x01(\tR\n" +
	"transferIdB9Z7github.com/lozzow/termx/termx-remote/protocol/runtimepbb\x06proto3"

var (
	file_termx_remote_protocol_runtimepb_runtime_proto_rawDescOnce sync.Once
	file_termx_remote_protocol_runtimepb_runtime_proto_rawDescData []byte
)

func file_termx_remote_protocol_runtimepb_runtime_proto_rawDescGZIP() []byte {
	file_termx_remote_protocol_runtimepb_runtime_proto_rawDescOnce.Do(func() {
		file_termx_remote_protocol_runtimepb_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_termx_remote_protocol_runtimepb_runtime_proto_rawDesc), len(file_termx_remote_protocol_runtimepb_runtime_proto_rawDesc)))
	})
	return file_termx_remote_protocol_runtimepb_runtime_proto_rawDescData
}

var file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_termx_remote_protocol_runtimepb_runtime_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: termx.remote.runtimepb.Empty
	(*APIRequest)(nil),                 // 1: termx.remote.runtimepb.APIRequest
	(*APIResponse)(nil),                // 2: termx.remote.runtimepb.APIResponse
	(*StatusResponse)(nil),             // 3: termx.remote.runtimepb.StatusResponse
	(*EventSubscribeRequest)(nil),      // 4: termx.remote.runtimepb.EventSubscribeRequest
	(*EventEnvelope)(nil),              // 5: termx.remote.runtimepb.EventEnvelope
	(*TerminalInventoryItem)(nil),      // 6: termx.remote.runtimepb.TerminalInventoryItem
	(*Size)(nil),                       // 7: termx.remote.runtimepb.Size
	(*ResizeOwnership)(nil),            // 8: termx.remote.runtimepb.ResizeOwnership
	(*TerminalListResponse)(nil),       // 9: termx.remote.runtimepb.TerminalListResponse
	(*TerminalDirectoryRequest)(nil),   // 10: termx.remote.runtimepb.TerminalDirectoryRequest
	(*TerminalDirectoryResponse)(nil),  // 11: termx.remote.runtimepb.TerminalDirectoryResponse
	(*TerminalCreateRequest)(nil),      // 12: termx.remote.runtimepb.TerminalCreateRequest
	(*TerminalSetMetadataRequest)(nil), // 13: termx.remote.runtimepb.TerminalSetMetadataRequest
	(*TerminalIDRequest)(nil),          // 14: termx.remote.runtimepb.TerminalIDRequest
	(*StorageEntry)(nil),               // 15: termx.remote.runtimepb.StorageEntry
	(*StorageGetRequest)(nil),          // 16: termx.remote.runtimepb.StorageGetRequest
	(*StoragePutRequest)(nil),          // 17: termx.remote.runtimepb.StoragePutRequest
	(*StorageDeleteRequest)(nil),       // 18: termx.remote.runtimepb.StorageDeleteRequest
	(*StorageDeleteResponse)(nil),      // 19: termx.remote.runtimepb.StorageDeleteResponse
	(*StorageListRequest)(nil),         // 20: termx.remote.runtimepb.StorageListRequest
	(*StorageListResponse)(nil),        // 21: termx.remote.runtimepb.StorageListResponse
	(*FilePathRequest)(nil),            // 22: termx.remote.runtimepb.FilePathRequest
	(*FileListRequest)(nil),            // 23: termx.remote.runtimepb.FileListRequest
	(*FileEntry)(nil),                  // 24: termx.remote.runtimepb.FileEntry
	(*FileListResponse)(nil),           // 25: termx.remote.runtimepb.FileListResponse
	(*FilePathResponse)(nil),           // 26: termx.remote.runtimepb.FilePathResponse
	(*FileRenameRequest)(nil),          // 27: termx.remote.runtimepb.FileRenameRequest
	(*FileMultiPathRequest)(nil),       // 28: termx.remote.runtimepb.FileMultiPathRequest
	(*FileCopyMoveRequest)(nil),        // 29: termx.remote.runtimepb.FileCopyMoveRequest
	(*FileOperationResult)(nil),        // 30: termx.remote.runtimepb.FileOperationResult
	(*FileCopyMoveResponse)(nil),       // 31: termx.remote.runtimepb.FileCopyMoveResponse
	(*FileDeleteError)(nil),            // 32: termx.remote.runtimepb.FileDeleteError
	(*FileBatchDeleteResponse)(nil),    // 33: termx.remote.runtimepb.FileBatchDeleteResponse
	(*FilePreviewRequest)(nil),         // 34: termx.remote.runtimepb.FilePreviewRequest
	(*FilePreviewResponse)(nil),        // 35: termx.remote.runtimepb.FilePreviewResponse
	(*FileDownloadInitRequest)(nil),    // 36: termx.remote.runtimepb.FileDownloadInitRequest
	(*FileDownloadInitResponse)(nil),   // 37: termx.remote.runtimepb.FileDownloadInitResponse
	(*FileUploadInitRequest)(nil),      // 38: termx.remote.runtimepb.FileUploadInitRequest
	(*FileUploadInitResponse)(nil),     // 39: termx.remote.runtimepb.FileUploadInitResponse
	(*FileUploadCompleteRequest)(nil),  // 40: termx.remote.runtimepb.FileUploadCompleteRequest
	nil,                                // 41: termx.remote.runtimepb.TerminalCreateRequest.TagsEntry
	nil,                                // 42: termx.remote.runtimepb.TerminalSetMetadataRequest.TagsEntry
}
var file_termx_remote_protocol_runtimepb_runtime_proto_depIdxs = []int32{
	6,  // 0: termx.remote.runtimepb.EventEnvelope.terminal:type_name -> termx.remote.runtimepb.TerminalInventoryItem
	8,  // 1: termx.remote.runtimepb.TerminalInventoryItem.resize_ownership:type_name -> termx.remote.runtimepb.ResizeOwnership
	7,  // 2: termx.remote.runtimepb.ResizeOwnership.size:type_name -> termx.remote.runtimepb.Size
	6,  // 3: termx.remote.runtimepb.TerminalListResponse.terminals:type_name -> termx.remote.runtimepb.TerminalInventoryItem
	41, // 4: termx.remote.runtimepb.TerminalCreateRequest.tags:type_name -> termx.remote.runtimepb.TerminalCreateRequest.TagsEntry
	42, // 5: termx.remote.runtimepb.TerminalSetMetadataRequest.tags:type_name -> termx.remote.runtimepb.TerminalSetMetadataRequest.TagsEntry
	15, // 6: termx.remote.runtimepb.StorageListResponse.entries:type_name -> termx.remote.runtimepb.StorageEntry
	24, // 7: termx.remote.runtimepb.FileListResponse.entries:type_name -> termx.remote.runtimepb.FileEntry
	30, // 8: termx.remote.runtimepb.FileCopyMoveResponse.results:type_name -> termx.remote.runtimepb.FileOperationResult
	32, // 9: termx.remote.runtimepb.FileBatchDeleteResponse.errors:type_name -> termx.remote.runtimepb.FileDeleteError
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_termx_remote_protocol_runtimepb_runtime_proto_init() }
func file_termx_remote_protocol_runtimepb_runtime_proto_init() {
	if File_termx_remote_protocol_runtimepb_runtime_proto != nil {
		return
	}
	file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_termx_remote_protocol_runtimepb_runtime_proto_rawDesc), len(file_termx_remote_protocol_runtimepb_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_termx_remote_protocol_runtimepb_runtime_proto_goTypes,
		DependencyIndexes: file_termx_remote_protocol_runtimepb_runtime_proto_depIdxs,
		MessageInfos:      file_termx_remote_protocol_runtimepb_runtime_proto_msgTypes,
	}.Build()
	File_termx_remote_protocol_runtimepb_runtime_proto = out.File
	file_termx_remote_protocol_runtimepb_runtime_proto_goTypes = nil
	file_termx_remote_protocol_runtimepb_runtime_proto_depIdxs = nil
}
