// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {

    configurations.classpath {
        resolutionStrategy.activateDependencyLocking()
    }

    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.20' // anytty kotlinVersion
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'com.google.gms:google-services:4.4.4'
        classpath 'com.google.protobuf:protobuf-gradle-plugin:0.9.5'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply from: "variables.gradle"

allprojects {
    repositories {
        google()
        mavenCentral()
    }
    def lockName = project.path == ':' ? 'root' : project.path.substring(1).replace(':', '-')
    dependencyLocking {
        lockAllConfigurations()
        lockFile = rootProject.file("gradle/dependency-locks/${lockName}.lockfile")
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
