import { create } from '@bufbuild/protobuf'
import { timestampFromDate } from '@bufbuild/protobuf/wkt'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { BadgeCheck, Plus, Search } from 'lucide-react'
import { FormEvent, useState } from 'react'
import { Link } from 'react-router'
import { APIError, protoSend } from '../api'
import { compactID, dateTime, money, orderState } from '../format'
import { ApplyPaymentEventRequestSchema, ApplyPaymentEventResponseSchema, CreateOrderRequestSchema, CreateOrderResponseSchema, OrderStatus, PaymentEventType, SubscriptionTransition } from '../generated/cloud/v1/commerce_pb'
import { ListOperatorOrdersResponseSchema } from '../generated/cloud/v1/operator_pb'
import { CursorPagination, pageURL, useCursorPagination } from '../pagination'
import { useProtoQuery } from '../query'
import { Button, Dialog, Empty, ErrorState, Field, Input, Notice, PageHeader, Skeleton, Status, TableFrame } from '../ui'

export function OrdersPage() {
  const [search, setSearch] = useState('')
  const [queryValue, setQueryValue] = useState('')
  const pagination = useCursorPagination()
  const query = useProtoQuery(['orders', { query: queryValue, cursor: pagination.cursor }], pageURL('/api/operator/orders', pagination.cursor, queryValue), ListOperatorOrdersResponseSchema, 15_000)
  const client = useQueryClient()
  const [createOpen, setCreateOpen] = useState(false)
  const [paymentOpen, setPaymentOpen] = useState(false)
  const [created, setCreated] = useState<{ order: string; attempt: string }>()
  const [order, setOrder] = useState({ accountId: '', planId: '', planVersion: '1', provider: 'manual', idempotencyKey: '', transition: SubscriptionTransition.ACTIVATE, yearly: false })
  const [payment, setPayment] = useState({ provider: 'manual', eventId: '', attemptId: '', orderId: '', reference: '', eventType: PaymentEventType.SUCCEEDED })
  const createOrder = useMutation({ mutationFn: () => protoSend('/api/commerce/order', CreateOrderRequestSchema, create(CreateOrderRequestSchema, { accountId: order.accountId, planId: order.planId, planVersion: BigInt(order.planVersion), provider: order.provider, idempotencyKey: order.idempotencyKey, requestedTransition: order.transition, yearly: order.yearly }), CreateOrderResponseSchema), onSuccess: (value) => { setCreated({ order: value.order?.orderId ?? '', attempt: value.paymentAttempt?.paymentAttemptId ?? '' }); void client.invalidateQueries({ queryKey: ['orders'] }) } })
  const applyPayment = useMutation({ mutationFn: () => protoSend('/api/operator/payments/events', ApplyPaymentEventRequestSchema, create(ApplyPaymentEventRequestSchema, { provider: payment.provider, providerEventId: payment.eventId, paymentAttemptId: payment.attemptId, orderId: payment.orderId, providerReference: payment.reference, eventType: payment.eventType, occurredAt: timestampFromDate(new Date()) }), ApplyPaymentEventResponseSchema), onSuccess: () => { setPaymentOpen(false); void client.invalidateQueries({ queryKey: ['orders'] }); void client.invalidateQueries({ queryKey: ['subscriptions'] }); void client.invalidateQueries({ queryKey: ['accounts'] }) } })
  function submit(event: FormEvent) { event.preventDefault(); pagination.reset(); setQueryValue(search.trim()) }
  return <>
    <PageHeader title="订单与交易" meta="支付事件按 provider event ID 幂等推进订单、订阅与 Entitlement" actions={<><Button onClick={() => setPaymentOpen(true)}><BadgeCheck size={16} />录入支付事件</Button><Button tone="primary" onClick={() => { setCreated(undefined); setCreateOpen(true) }}><Plus size={17} />创建订单</Button></>} />
    <form className="list-toolbar" onSubmit={submit}><div className="search-input"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="订单、账号或支付渠道" /></div><Button type="submit">查询</Button></form>
    {query.isPending ? <Skeleton /> : query.error ? <ErrorState error={query.error} onRetry={() => void query.refetch()} /> : !query.data?.orders.length ? <Empty>暂无订单</Empty> : <><TableFrame><table><thead><tr><th>订单</th><th>账号</th><th>套餐版本</th><th>状态</th><th>金额</th><th>支付渠道</th><th>创建时间</th></tr></thead><tbody>{query.data.orders.map((value) => <tr key={value.orderId}><td><strong className="mono">{compactID(value.orderId)}</strong><small className="mono">{value.idempotencyKey}</small></td><td><Link className="table-link mono" to={`/app/admin/accounts/${value.accountId}`}>{compactID(value.accountId)}</Link></td><td>{value.planId} v{value.planVersion.toString()}</td><td><Status active={value.status === OrderStatus.PAID}>{orderState(value.status)}</Status></td><td>{money(value.amount?.currency ?? 'CNY', value.amount?.minorUnits ?? 0n)}</td><td>{value.provider}<small>{value.providerReference || '-'}</small></td><td>{dateTime(value.createdAt)}</td></tr>)}</tbody></table></TableFrame><CursorPagination page={pagination.page} nextCursor={query.data.nextCursor} onPrevious={pagination.previous} onNext={pagination.next} /></>}
    <Dialog title={created ? '订单已创建' : '创建订单'} open={createOpen} onClose={() => setCreateOpen(false)} footer={created ? <Button tone="primary" onClick={() => { setPayment({ ...payment, orderId: created.order, attemptId: created.attempt }); setCreateOpen(false); setPaymentOpen(true) }}>录入支付结果</Button> : <><Button tone="quiet" onClick={() => setCreateOpen(false)}>取消</Button><Button tone="primary" onClick={() => createOrder.mutate()} disabled={!order.accountId || !order.planId || !order.idempotencyKey || createOrder.isPending}>创建</Button></>}>
      {created ? <dl className="detail-list"><div><dt>订单 ID</dt><dd className="mono">{created.order}</dd></div><div><dt>支付尝试 ID</dt><dd className="mono">{created.attempt}</dd></div></dl> : <div className="form-grid form-grid-two"><Field label="账号 ID"><Input value={order.accountId} onChange={(event) => setOrder({ ...order, accountId: event.target.value })} /></Field><Field label="套餐 ID"><Input value={order.planId} onChange={(event) => setOrder({ ...order, planId: event.target.value })} /></Field><Field label="套餐版本"><Input type="number" min="1" value={order.planVersion} onChange={(event) => setOrder({ ...order, planVersion: event.target.value })} /></Field><Field label="支付渠道"><Input value={order.provider} onChange={(event) => setOrder({ ...order, provider: event.target.value })} /></Field><Field label="幂等键"><Input value={order.idempotencyKey} onChange={(event) => setOrder({ ...order, idempotencyKey: event.target.value })} /></Field><Field label="订阅变更"><select className="input" value={order.transition} onChange={(event) => setOrder({ ...order, transition: Number(event.target.value) })}><option value={SubscriptionTransition.ACTIVATE}>激活</option><option value={SubscriptionTransition.RENEW}>续期</option><option value={SubscriptionTransition.UPGRADE}>升级</option><option value={SubscriptionTransition.DOWNGRADE}>降级</option></select></Field><label className="check-field"><input type="checkbox" checked={order.yearly} onChange={(event) => setOrder({ ...order, yearly: event.target.checked })} />使用年付价格</label>{createOrder.error && <p className="form-error" role="alert">无法创建订单，请检查账号与套餐信息后重试。{createOrder.error instanceof APIError && createOrder.error.correlationID ? ` 关联 ID：${createOrder.error.correlationID}` : ''}</p>}</div>}
    </Dialog>
    <Dialog title="录入支付事件" open={paymentOpen} onClose={() => setPaymentOpen(false)} footer={<><Button tone="quiet" onClick={() => setPaymentOpen(false)}>取消</Button><Button tone="primary" onClick={() => applyPayment.mutate()} disabled={!payment.eventId || !payment.attemptId || !payment.orderId || applyPayment.isPending}>应用事件</Button></>}><Notice tone="warning">这里只接受已经由支付渠道适配器验签并归一化的事件。</Notice><div className="form-grid"><Field label="支付渠道"><Input value={payment.provider} onChange={(event) => setPayment({ ...payment, provider: event.target.value })} /></Field><Field label="渠道事件 ID"><Input value={payment.eventId} onChange={(event) => setPayment({ ...payment, eventId: event.target.value })} /></Field><Field label="支付尝试 ID"><Input value={payment.attemptId} onChange={(event) => setPayment({ ...payment, attemptId: event.target.value })} /></Field><Field label="订单 ID"><Input value={payment.orderId} onChange={(event) => setPayment({ ...payment, orderId: event.target.value })} /></Field><Field label="渠道流水号"><Input value={payment.reference} onChange={(event) => setPayment({ ...payment, reference: event.target.value })} /></Field><Field label="事件类型"><select className="input" value={payment.eventType} onChange={(event) => setPayment({ ...payment, eventType: Number(event.target.value) })}><option value={PaymentEventType.SUCCEEDED}>支付成功</option><option value={PaymentEventType.FAILED}>支付失败</option><option value={PaymentEventType.REFUNDED}>退款</option><option value={PaymentEventType.REVOKED}>撤销</option><option value={PaymentEventType.CHARGEBACK}>拒付</option></select></Field>{applyPayment.error && <p className="form-error" role="alert">无法录入支付事件，请检查事件信息后重试。{applyPayment.error instanceof APIError && applyPayment.error.correlationID ? ` 关联 ID：${applyPayment.error.correlationID}` : ''}</p>}</div></Dialog>
  </>
}
