import { create } from '@bufbuild/protobuf'
import { useMutation, useQueryClient } from '@tanstack/react-query'
import { Plus, Send } from 'lucide-react'
import { useState } from 'react'
import { APIError, protoSend } from '../api'
import { bytes, dateTime, money, planState } from '../format'
import { CreatePlanVersionRequestSchema, CreatePlanVersionResponseSchema, ListPlansResponseSchema, PlanState, PublishPlanVersionRequestSchema, PublishPlanVersionResponseSchema } from '../generated/cloud/v1/commerce_pb'
import { useProtoQuery } from '../query'
import { Button, Dialog, Empty, ErrorState, Field, Input, Notice, PageHeader, Skeleton, Status, TableFrame } from '../ui'

export function PlansPage() {
  const query = useProtoQuery(['plans'], '/api/operator/plans', ListPlansResponseSchema, 60_000)
  const client = useQueryClient()
  const [open, setOpen] = useState(false)
  const [form, setForm] = useState({ planId: '', name: '', description: '', monthly: '0', yearly: '0', daemonLimit: '1', relayLimit: '1', relayQuota: '0', relayLease: '0', relayRate: '0', regions: '' })
  const createPlan = useMutation({ mutationFn: () => protoSend('/api/operator/plans', CreatePlanVersionRequestSchema, create(CreatePlanVersionRequestSchema, { planId: form.planId, name: form.name, description: form.description, billingPeriodDays: 30, monthlyPrice: { currency: 'CNY', minorUnits: BigInt(form.monthly) }, yearlyPrice: { currency: 'CNY', minorUnits: BigInt(form.yearly) }, capability: { managedP2pEnabled: true, managedP2pMaxConcurrency: 0, relayEnabled: BigInt(form.relayQuota) > 0n, relayMaxConcurrency: Number(form.relayLimit), relayMaxBytesPerPeriod: BigInt(form.relayQuota), relayMaxBytesPerLease: BigInt(form.relayLease), relayMaxRateBytesPerSecond: BigInt(form.relayRate), cloudDaemonLimit: Number(form.daemonLimit), allowedRegions: form.regions.split(',').map((value) => value.trim()).filter(Boolean) } }), CreatePlanVersionResponseSchema), onSuccess: () => { setOpen(false); void client.invalidateQueries({ queryKey: ['plans'] }) } })
  const publish = useMutation({ mutationFn: (plan: NonNullable<typeof query.data>['plans'][number]) => protoSend(`/api/operator/plans/${plan.planId}/${plan.version}/publish`, PublishPlanVersionRequestSchema, create(PublishPlanVersionRequestSchema, { expectedRevision: plan.revision }), PublishPlanVersionResponseSchema), onSuccess: () => void client.invalidateQueries({ queryKey: ['plans'] }) })
  function openCreate() { createPlan.reset(); setOpen(true) }
  function closeCreate() { if (createPlan.isPending) return; setOpen(false); createPlan.reset() }
  return <>
    <PageHeader title="套餐" meta="已发布版本不可原地修改；新配置创建为新的不可变版本" actions={<Button tone="primary" onClick={openCreate}><Plus size={17} />创建套餐版本</Button>} />
    {query.isPending ? <Skeleton /> : query.error ? <ErrorState error={query.error} onRetry={() => void query.refetch()} /> : !query.data?.plans.length ? <Empty>尚无套餐版本</Empty> : <TableFrame><table><thead><tr><th>套餐版本</th><th>状态</th><th>月付 / 年付</th><th>Cloud 限额</th><th>Relay 配额</th><th>创建时间</th><th /></tr></thead><tbody>{query.data.plans.map((plan) => <tr key={`${plan.planId}:${plan.version}`}><td><strong>{plan.name}</strong><small>{plan.planId} · v{plan.version.toString()}</small></td><td><Status active={plan.state === PlanState.PUBLISHED}>{planState(plan.state)}</Status></td><td>{money(plan.monthlyPrice?.currency ?? 'CNY', plan.monthlyPrice?.minorUnits ?? 0n)}<small>{money(plan.yearlyPrice?.currency ?? 'CNY', plan.yearlyPrice?.minorUnits ?? 0n)} / 年</small></td><td>{plan.capability?.cloudDaemonLimit ?? 0} 个在线 daemon<small>P2P 不限并发 · {plan.capability?.relayMaxConcurrency ?? 0} Relay</small></td><td>{bytes(plan.capability?.relayMaxBytesPerPeriod ?? 0n)}</td><td>{dateTime(plan.createdAt)}</td><td>{plan.state === PlanState.DRAFT && <Button onClick={() => publish.mutate(plan)} disabled={publish.isPending}><Send size={15} />发布</Button>}</td></tr>)}</tbody></table></TableFrame>}
    {publish.error && <Notice tone="error">无法发布套餐版本，请刷新后重试。{publish.error instanceof APIError && publish.error.correlationID ? ` 关联 ID：${publish.error.correlationID}` : ''}</Notice>}
    <Dialog title="创建套餐版本" open={open} onClose={closeCreate} closable={!createPlan.isPending} footer={<><Button tone="quiet" onClick={closeCreate} disabled={createPlan.isPending}>取消</Button><Button tone="primary" onClick={() => createPlan.mutate()} disabled={!form.planId || !form.name || createPlan.isPending}>创建草稿</Button></>}><div className="form-grid form-grid-two"><Field label="套餐 ID"><Input placeholder="professional" value={form.planId} onChange={(event) => setForm({ ...form, planId: event.target.value })} /></Field><Field label="显示名称"><Input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="说明"><Input value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><Field label="允许区域（逗号分隔）"><Input placeholder="cn-north-1, us-west-1" value={form.regions} onChange={(event) => setForm({ ...form, regions: event.target.value })} /></Field><Field label="月付（分）"><Input type="number" min="0" value={form.monthly} onChange={(event) => setForm({ ...form, monthly: event.target.value })} /></Field><Field label="年付（分）"><Input type="number" min="0" value={form.yearly} onChange={(event) => setForm({ ...form, yearly: event.target.value })} /></Field><Field label="同时在线 daemon"><Input type="number" min="1" value={form.daemonLimit} onChange={(event) => setForm({ ...form, daemonLimit: event.target.value })} /></Field><Field label="Relay 并发"><Input type="number" min="0" value={form.relayLimit} onChange={(event) => setForm({ ...form, relayLimit: event.target.value })} /></Field><Field label="Relay 周期配额（字节）"><Input type="number" min="0" value={form.relayQuota} onChange={(event) => setForm({ ...form, relayQuota: event.target.value })} /></Field><Field label="单租约上限（字节）"><Input type="number" min="0" value={form.relayLease} onChange={(event) => setForm({ ...form, relayLease: event.target.value })} /></Field><Field label="速率上限（字节/秒）"><Input type="number" min="0" value={form.relayRate} onChange={(event) => setForm({ ...form, relayRate: event.target.value })} /></Field>{createPlan.error && <p className="form-error" role="alert">无法创建套餐草稿，请检查配置后重试。{createPlan.error instanceof APIError && createPlan.error.correlationID ? ` 关联 ID：${createPlan.error.correlationID}` : ''}</p>}</div></Dialog>
  </>
}
