syntax = "proto3";

package termx.api.v1;

import "apipb/common.proto";
import "apipb/terminal.proto";

option go_package = "github.com/lozzow/termx/proto/apipb";

message CancelOperationCommand {
  RequestContext context = 1;
  OperationStamp operation = 2;
}

message ReleaseResourceCommand {
  RequestContext context = 1;
  ResourceHandle resource = 2;
}

message CommandEnvelope {
  oneof command {
    CancelOperationCommand cancel_operation = 10;
    ReleaseResourceCommand release_resource = 11;
    TerminalDefaultsCommand terminal_defaults = 20;
    TerminalCreateCommand terminal_create = 21;
    TerminalListCommand terminal_list = 22;
    TerminalGetCommand terminal_get = 23;
    TerminalRestartCommand terminal_restart = 24;
    TerminalKillCommand terminal_kill = 25;
    TerminalRemoveCommand terminal_remove = 26;
    TerminalSetMetadataCommand terminal_set_metadata = 27;
    TerminalSetTagsCommand terminal_set_tags = 28;
    TerminalAttachCommand terminal_attach = 29;
    TerminalDetachCommand terminal_detach = 30;
    TerminalInputCommand terminal_input = 31;
    TerminalResizeCommand terminal_resize = 32;
    TerminalResizeLockCommand terminal_resize_lock = 33;
    PathListDirectoriesCommand path_list_directories = 34;
  }
}

message AcknowledgeResult {}

message ResultEnvelope {
  string request_id = 1;
  oneof result {
    AcknowledgeResult acknowledge = 10;
    ApiError error = 11;
    TerminalDefaultsResult terminal_defaults = 20;
    TerminalCreateResult terminal_create = 21;
    TerminalListResult terminal_list = 22;
    TerminalGetResult terminal_get = 23;
    TerminalAttachResult terminal_attach = 24;
    TerminalResizeResult terminal_resize = 25;
    PathListDirectoriesResult path_list_directories = 26;
  }
}

message OperationCancelledEvent {
  OperationStamp operation = 1;
}

message ResourceReleasedEvent {
  ResourceHandle resource = 1;
}

message EventEnvelope {
  string event_id = 1;
  int64 timestamp_unix_nano = 2;
  ApiVersion api_version = 3;
  oneof event {
    OperationCancelledEvent operation_cancelled = 10;
    ResourceReleasedEvent resource_released = 11;
    TerminalLifecycleEvent terminal_lifecycle = 20;
    TerminalResizeControlEvent terminal_resize_control = 21;
  }
}
