// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: apipb/application.proto

package apipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CancelOperationCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *OperationStamp        `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperationCommand) Reset() {
	*x = CancelOperationCommand{}
	mi := &file_apipb_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperationCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperationCommand) ProtoMessage() {}

func (x *CancelOperationCommand) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperationCommand.ProtoReflect.Descriptor instead.
func (*CancelOperationCommand) Descriptor() ([]byte, []int) {
	return file_apipb_application_proto_rawDescGZIP(), []int{0}
}

func (x *CancelOperationCommand) GetOperation() *OperationStamp {
	if x != nil {
		return x.Operation
	}
	return nil
}

type ReleaseResourceCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ResourceHandle        `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResourceCommand) Reset() {
	*x = ReleaseResourceCommand{}
	mi := &file_apipb_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResourceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResourceCommand) ProtoMessage() {}

func (x *ReleaseResourceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResourceCommand.ProtoReflect.Descriptor instead.
func (*ReleaseResourceCommand) Descriptor() ([]byte, []int) {
	return file_apipb_application_proto_rawDescGZIP(), []int{1}
}

func (x *ReleaseResourceCommand) GetResource() *ResourceHandle {
	if x != nil {
		return x.Resource
	}
	return nil
}

type CommandEnvelope struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Context *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*CommandEnvelope_CancelOperation
	//	*CommandEnvelope_ReleaseResource
	//	*CommandEnvelope_TerminalDefaults
	//	*CommandEnvelope_TerminalCreate
	//	*CommandEnvelope_TerminalList
	//	*CommandEnvelope_TerminalGet
	//	*CommandEnvelope_TerminalRestart
	//	*CommandEnvelope_TerminalKill
	//	*CommandEnvelope_TerminalRemove
	//	*CommandEnvelope_TerminalSetMetadata
	//	*CommandEnvelope_TerminalSetTags
	//	*CommandEnvelope_TerminalAttach
	//	*CommandEnvelope_TerminalDetach
	//	*CommandEnvelope_TerminalInput
	//	*CommandEnvelope_TerminalResize
	//	*CommandEnvelope_TerminalResizeLock
	//	*CommandEnvelope_PathListDirectories
	//	*CommandEnvelope_HistoryWindow
	//	*CommandEnvelope_HistoryCopy
	//	*CommandEnvelope_HistoryRelease
	//	*CommandEnvelope_HistoryBacklogStatus
	//	*CommandEnvelope_LiveScreenNext
	//	*CommandEnvelope_HistorySearch
	//	*CommandEnvelope_EventSubscribe
	//	*CommandEnvelope_FileList
	//	*CommandEnvelope_FileStat
	//	*CommandEnvelope_FilePreview
	//	*CommandEnvelope_FileMkdir
	//	*CommandEnvelope_FileRename
	//	*CommandEnvelope_FileDelete
	//	*CommandEnvelope_FileCopy
	//	*CommandEnvelope_FileMove
	//	*CommandEnvelope_FileDownloadOpen
	//	*CommandEnvelope_FileUploadOpen
	//	*CommandEnvelope_FileTransferCancel
	//	*CommandEnvelope_StorageGet
	//	*CommandEnvelope_StoragePut
	//	*CommandEnvelope_StorageDelete
	//	*CommandEnvelope_StorageList
	//	*CommandEnvelope_ClientAccessIdentity
	//	*CommandEnvelope_ClientAccessList
	//	*CommandEnvelope_ClientAccessTicketCreate
	//	*CommandEnvelope_ClientAccessRevoke
	//	*CommandEnvelope_RemoteStatus
	//	*CommandEnvelope_RemotePairStart
	//	*CommandEnvelope_RemoteLocalEnable
	//	*CommandEnvelope_RemoteLocalStatus
	//	*CommandEnvelope_RemoteLocalDisable
	//	*CommandEnvelope_RemoteCloudEdges
	//	*CommandEnvelope_RemoteCloudPreferEdge
	//	*CommandEnvelope_RemoteCloudReselectEdge
	Command       isCommandEnvelope_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandEnvelope) Reset() {
	*x = CommandEnvelope{}
	mi := &file_apipb_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandEnvelope) ProtoMessage() {}

func (x *CommandEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandEnvelope.ProtoReflect.Descriptor instead.
func (*CommandEnvelope) Descriptor() ([]byte, []int) {
	return file_apipb_application_proto_rawDescGZIP(), []int{2}
}

func (x *CommandEnvelope) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CommandEnvelope) GetCommand() isCommandEnvelope_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *CommandEnvelope) GetCancelOperation() *CancelOperationCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_CancelOperation); ok {
			return x.CancelOperation
		}
	}
	return nil
}

func (x *CommandEnvelope) GetReleaseResource() *ReleaseResourceCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_ReleaseResource); ok {
			return x.ReleaseResource
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalDefaults() *TerminalDefaultsCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalDefaults); ok {
			return x.TerminalDefaults
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalCreate() *TerminalCreateCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalCreate); ok {
			return x.TerminalCreate
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalList() *TerminalListCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalList); ok {
			return x.TerminalList
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalGet() *TerminalGetCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalGet); ok {
			return x.TerminalGet
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalRestart() *TerminalRestartCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalRestart); ok {
			return x.TerminalRestart
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalKill() *TerminalKillCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalKill); ok {
			return x.TerminalKill
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalRemove() *TerminalRemoveCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalRemove); ok {
			return x.TerminalRemove
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalSetMetadata() *TerminalSetMetadataCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalSetMetadata); ok {
			return x.TerminalSetMetadata
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalSetTags() *TerminalSetTagsCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalSetTags); ok {
			return x.TerminalSetTags
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalAttach() *TerminalAttachCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalAttach); ok {
			return x.TerminalAttach
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalDetach() *TerminalDetachCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalDetach); ok {
			return x.TerminalDetach
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalInput() *TerminalInputCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalInput); ok {
			return x.TerminalInput
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalResize() *TerminalResizeCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalResize); ok {
			return x.TerminalResize
		}
	}
	return nil
}

func (x *CommandEnvelope) GetTerminalResizeLock() *TerminalResizeLockCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_TerminalResizeLock); ok {
			return x.TerminalResizeLock
		}
	}
	return nil
}

func (x *CommandEnvelope) GetPathListDirectories() *PathListDirectoriesCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_PathListDirectories); ok {
			return x.PathListDirectories
		}
	}
	return nil
}

func (x *CommandEnvelope) GetHistoryWindow() *HistoryWindowCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_HistoryWindow); ok {
			return x.HistoryWindow
		}
	}
	return nil
}

func (x *CommandEnvelope) GetHistoryCopy() *HistoryCopyCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_HistoryCopy); ok {
			return x.HistoryCopy
		}
	}
	return nil
}

func (x *CommandEnvelope) GetHistoryRelease() *HistoryReleaseCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_HistoryRelease); ok {
			return x.HistoryRelease
		}
	}
	return nil
}

func (x *CommandEnvelope) GetHistoryBacklogStatus() *HistoryBacklogStatusCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_HistoryBacklogStatus); ok {
			return x.HistoryBacklogStatus
		}
	}
	return nil
}

func (x *CommandEnvelope) GetLiveScreenNext() *LiveScreenNextCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_LiveScreenNext); ok {
			return x.LiveScreenNext
		}
	}
	return nil
}

func (x *CommandEnvelope) GetHistorySearch() *HistorySearchCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_HistorySearch); ok {
			return x.HistorySearch
		}
	}
	return nil
}

func (x *CommandEnvelope) GetEventSubscribe() *EventSubscribeCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_EventSubscribe); ok {
			return x.EventSubscribe
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileList() *FileListCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileList); ok {
			return x.FileList
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileStat() *FileStatCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileStat); ok {
			return x.FileStat
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFilePreview() *FilePreviewCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FilePreview); ok {
			return x.FilePreview
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileMkdir() *FileMkdirCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileMkdir); ok {
			return x.FileMkdir
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileRename() *FileRenameCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileRename); ok {
			return x.FileRename
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileDelete() *FileDeleteCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileDelete); ok {
			return x.FileDelete
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileCopy() *FileCopyCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileCopy); ok {
			return x.FileCopy
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileMove() *FileMoveCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileMove); ok {
			return x.FileMove
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileDownloadOpen() *FileDownloadOpenCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileDownloadOpen); ok {
			return x.FileDownloadOpen
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileUploadOpen() *FileUploadOpenCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileUploadOpen); ok {
			return x.FileUploadOpen
		}
	}
	return nil
}

func (x *CommandEnvelope) GetFileTransferCancel() *FileTransferCancelCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_FileTransferCancel); ok {
			return x.FileTransferCancel
		}
	}
	return nil
}

func (x *CommandEnvelope) GetStorageGet() *StorageGetCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_StorageGet); ok {
			return x.StorageGet
		}
	}
	return nil
}

func (x *CommandEnvelope) GetStoragePut() *StoragePutCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_StoragePut); ok {
			return x.StoragePut
		}
	}
	return nil
}

func (x *CommandEnvelope) GetStorageDelete() *StorageDeleteCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_StorageDelete); ok {
			return x.StorageDelete
		}
	}
	return nil
}

func (x *CommandEnvelope) GetStorageList() *StorageListCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_StorageList); ok {
			return x.StorageList
		}
	}
	return nil
}

func (x *CommandEnvelope) GetClientAccessIdentity() *ClientAccessIdentityCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_ClientAccessIdentity); ok {
			return x.ClientAccessIdentity
		}
	}
	return nil
}

func (x *CommandEnvelope) GetClientAccessList() *ClientAccessListCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_ClientAccessList); ok {
			return x.ClientAccessList
		}
	}
	return nil
}

func (x *CommandEnvelope) GetClientAccessTicketCreate() *ClientAccessTicketCreateCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_ClientAccessTicketCreate); ok {
			return x.ClientAccessTicketCreate
		}
	}
	return nil
}

func (x *CommandEnvelope) GetClientAccessRevoke() *ClientAccessRevokeCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_ClientAccessRevoke); ok {
			return x.ClientAccessRevoke
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRemoteStatus() *RemoteStatusCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RemoteStatus); ok {
			return x.RemoteStatus
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRemotePairStart() *RemotePairStartCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RemotePairStart); ok {
			return x.RemotePairStart
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRemoteLocalEnable() *RemoteLocalEnableCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RemoteLocalEnable); ok {
			return x.RemoteLocalEnable
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRemoteLocalStatus() *RemoteLocalStatusCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RemoteLocalStatus); ok {
			return x.RemoteLocalStatus
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRemoteLocalDisable() *RemoteLocalDisableCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RemoteLocalDisable); ok {
			return x.RemoteLocalDisable
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRemoteCloudEdges() *RemoteCloudEdgesCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RemoteCloudEdges); ok {
			return x.RemoteCloudEdges
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRemoteCloudPreferEdge() *RemoteCloudPreferEdgeCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RemoteCloudPreferEdge); ok {
			return x.RemoteCloudPreferEdge
		}
	}
	return nil
}

func (x *CommandEnvelope) GetRemoteCloudReselectEdge() *RemoteCloudReselectEdgeCommand {
	if x != nil {
		if x, ok := x.Command.(*CommandEnvelope_RemoteCloudReselectEdge); ok {
			return x.RemoteCloudReselectEdge
		}
	}
	return nil
}

type isCommandEnvelope_Command interface {
	isCommandEnvelope_Command()
}

type CommandEnvelope_CancelOperation struct {
	CancelOperation *CancelOperationCommand `protobuf:"bytes,10,opt,name=cancel_operation,json=cancelOperation,proto3,oneof"`
}

type CommandEnvelope_ReleaseResource struct {
	ReleaseResource *ReleaseResourceCommand `protobuf:"bytes,11,opt,name=release_resource,json=releaseResource,proto3,oneof"`
}

type CommandEnvelope_TerminalDefaults struct {
	TerminalDefaults *TerminalDefaultsCommand `protobuf:"bytes,20,opt,name=terminal_defaults,json=terminalDefaults,proto3,oneof"`
}

type CommandEnvelope_TerminalCreate struct {
	TerminalCreate *TerminalCreateCommand `protobuf:"bytes,21,opt,name=terminal_create,json=terminalCreate,proto3,oneof"`
}

type CommandEnvelope_TerminalList struct {
	TerminalList *TerminalListCommand `protobuf:"bytes,22,opt,name=terminal_list,json=terminalList,proto3,oneof"`
}

type CommandEnvelope_TerminalGet struct {
	TerminalGet *TerminalGetCommand `protobuf:"bytes,23,opt,name=terminal_get,json=terminalGet,proto3,oneof"`
}

type CommandEnvelope_TerminalRestart struct {
	TerminalRestart *TerminalRestartCommand `protobuf:"bytes,24,opt,name=terminal_restart,json=terminalRestart,proto3,oneof"`
}

type CommandEnvelope_TerminalKill struct {
	TerminalKill *TerminalKillCommand `protobuf:"bytes,25,opt,name=terminal_kill,json=terminalKill,proto3,oneof"`
}

type CommandEnvelope_TerminalRemove struct {
	TerminalRemove *TerminalRemoveCommand `protobuf:"bytes,26,opt,name=terminal_remove,json=terminalRemove,proto3,oneof"`
}

type CommandEnvelope_TerminalSetMetadata struct {
	TerminalSetMetadata *TerminalSetMetadataCommand `protobuf:"bytes,27,opt,name=terminal_set_metadata,json=terminalSetMetadata,proto3,oneof"`
}

type CommandEnvelope_TerminalSetTags struct {
	TerminalSetTags *TerminalSetTagsCommand `protobuf:"bytes,28,opt,name=terminal_set_tags,json=terminalSetTags,proto3,oneof"`
}

type CommandEnvelope_TerminalAttach struct {
	TerminalAttach *TerminalAttachCommand `protobuf:"bytes,29,opt,name=terminal_attach,json=terminalAttach,proto3,oneof"`
}

type CommandEnvelope_TerminalDetach struct {
	TerminalDetach *TerminalDetachCommand `protobuf:"bytes,30,opt,name=terminal_detach,json=terminalDetach,proto3,oneof"`
}

type CommandEnvelope_TerminalInput struct {
	TerminalInput *TerminalInputCommand `protobuf:"bytes,31,opt,name=terminal_input,json=terminalInput,proto3,oneof"`
}

type CommandEnvelope_TerminalResize struct {
	TerminalResize *TerminalResizeCommand `protobuf:"bytes,32,opt,name=terminal_resize,json=terminalResize,proto3,oneof"`
}

type CommandEnvelope_TerminalResizeLock struct {
	TerminalResizeLock *TerminalResizeLockCommand `protobuf:"bytes,33,opt,name=terminal_resize_lock,json=terminalResizeLock,proto3,oneof"`
}

type CommandEnvelope_PathListDirectories struct {
	PathListDirectories *PathListDirectoriesCommand `protobuf:"bytes,34,opt,name=path_list_directories,json=pathListDirectories,proto3,oneof"`
}

type CommandEnvelope_HistoryWindow struct {
	HistoryWindow *HistoryWindowCommand `protobuf:"bytes,40,opt,name=history_window,json=historyWindow,proto3,oneof"`
}

type CommandEnvelope_HistoryCopy struct {
	HistoryCopy *HistoryCopyCommand `protobuf:"bytes,41,opt,name=history_copy,json=historyCopy,proto3,oneof"`
}

type CommandEnvelope_HistoryRelease struct {
	HistoryRelease *HistoryReleaseCommand `protobuf:"bytes,42,opt,name=history_release,json=historyRelease,proto3,oneof"`
}

type CommandEnvelope_HistoryBacklogStatus struct {
	HistoryBacklogStatus *HistoryBacklogStatusCommand `protobuf:"bytes,43,opt,name=history_backlog_status,json=historyBacklogStatus,proto3,oneof"`
}

type CommandEnvelope_LiveScreenNext struct {
	LiveScreenNext *LiveScreenNextCommand `protobuf:"bytes,44,opt,name=live_screen_next,json=liveScreenNext,proto3,oneof"`
}

type CommandEnvelope_HistorySearch struct {
	HistorySearch *HistorySearchCommand `protobuf:"bytes,45,opt,name=history_search,json=historySearch,proto3,oneof"`
}

type CommandEnvelope_EventSubscribe struct {
	EventSubscribe *EventSubscribeCommand `protobuf:"bytes,46,opt,name=event_subscribe,json=eventSubscribe,proto3,oneof"`
}

type CommandEnvelope_FileList struct {
	FileList *FileListCommand `protobuf:"bytes,60,opt,name=file_list,json=fileList,proto3,oneof"`
}

type CommandEnvelope_FileStat struct {
	FileStat *FileStatCommand `protobuf:"bytes,61,opt,name=file_stat,json=fileStat,proto3,oneof"`
}

type CommandEnvelope_FilePreview struct {
	FilePreview *FilePreviewCommand `protobuf:"bytes,62,opt,name=file_preview,json=filePreview,proto3,oneof"`
}

type CommandEnvelope_FileMkdir struct {
	FileMkdir *FileMkdirCommand `protobuf:"bytes,63,opt,name=file_mkdir,json=fileMkdir,proto3,oneof"`
}

type CommandEnvelope_FileRename struct {
	FileRename *FileRenameCommand `protobuf:"bytes,64,opt,name=file_rename,json=fileRename,proto3,oneof"`
}

type CommandEnvelope_FileDelete struct {
	FileDelete *FileDeleteCommand `protobuf:"bytes,65,opt,name=file_delete,json=fileDelete,proto3,oneof"`
}

type CommandEnvelope_FileCopy struct {
	FileCopy *FileCopyCommand `protobuf:"bytes,66,opt,name=file_copy,json=fileCopy,proto3,oneof"`
}

type CommandEnvelope_FileMove struct {
	FileMove *FileMoveCommand `protobuf:"bytes,67,opt,name=file_move,json=fileMove,proto3,oneof"`
}

type CommandEnvelope_FileDownloadOpen struct {
	FileDownloadOpen *FileDownloadOpenCommand `protobuf:"bytes,68,opt,name=file_download_open,json=fileDownloadOpen,proto3,oneof"`
}

type CommandEnvelope_FileUploadOpen struct {
	FileUploadOpen *FileUploadOpenCommand `protobuf:"bytes,69,opt,name=file_upload_open,json=fileUploadOpen,proto3,oneof"`
}

type CommandEnvelope_FileTransferCancel struct {
	FileTransferCancel *FileTransferCancelCommand `protobuf:"bytes,70,opt,name=file_transfer_cancel,json=fileTransferCancel,proto3,oneof"`
}

type CommandEnvelope_StorageGet struct {
	StorageGet *StorageGetCommand `protobuf:"bytes,80,opt,name=storage_get,json=storageGet,proto3,oneof"`
}

type CommandEnvelope_StoragePut struct {
	StoragePut *StoragePutCommand `protobuf:"bytes,81,opt,name=storage_put,json=storagePut,proto3,oneof"`
}

type CommandEnvelope_StorageDelete struct {
	StorageDelete *StorageDeleteCommand `protobuf:"bytes,82,opt,name=storage_delete,json=storageDelete,proto3,oneof"`
}

type CommandEnvelope_StorageList struct {
	StorageList *StorageListCommand `protobuf:"bytes,83,opt,name=storage_list,json=storageList,proto3,oneof"`
}

type CommandEnvelope_ClientAccessIdentity struct {
	ClientAccessIdentity *ClientAccessIdentityCommand `protobuf:"bytes,100,opt,name=client_access_identity,json=clientAccessIdentity,proto3,oneof"`
}

type CommandEnvelope_ClientAccessList struct {
	ClientAccessList *ClientAccessListCommand `protobuf:"bytes,101,opt,name=client_access_list,json=clientAccessList,proto3,oneof"`
}

type CommandEnvelope_ClientAccessTicketCreate struct {
	ClientAccessTicketCreate *ClientAccessTicketCreateCommand `protobuf:"bytes,102,opt,name=client_access_ticket_create,json=clientAccessTicketCreate,proto3,oneof"`
}

type CommandEnvelope_ClientAccessRevoke struct {
	ClientAccessRevoke *ClientAccessRevokeCommand `protobuf:"bytes,103,opt,name=client_access_revoke,json=clientAccessRevoke,proto3,oneof"`
}

type CommandEnvelope_RemoteStatus struct {
	RemoteStatus *RemoteStatusCommand `protobuf:"bytes,110,opt,name=remote_status,json=remoteStatus,proto3,oneof"`
}

type CommandEnvelope_RemotePairStart struct {
	RemotePairStart *RemotePairStartCommand `protobuf:"bytes,111,opt,name=remote_pair_start,json=remotePairStart,proto3,oneof"`
}

type CommandEnvelope_RemoteLocalEnable struct {
	RemoteLocalEnable *RemoteLocalEnableCommand `protobuf:"bytes,112,opt,name=remote_local_enable,json=remoteLocalEnable,proto3,oneof"`
}

type CommandEnvelope_RemoteLocalStatus struct {
	RemoteLocalStatus *RemoteLocalStatusCommand `protobuf:"bytes,113,opt,name=remote_local_status,json=remoteLocalStatus,proto3,oneof"`
}

type CommandEnvelope_RemoteLocalDisable struct {
	RemoteLocalDisable *RemoteLocalDisableCommand `protobuf:"bytes,114,opt,name=remote_local_disable,json=remoteLocalDisable,proto3,oneof"`
}

type CommandEnvelope_RemoteCloudEdges struct {
	RemoteCloudEdges *RemoteCloudEdgesCommand `protobuf:"bytes,115,opt,name=remote_cloud_edges,json=remoteCloudEdges,proto3,oneof"`
}

type CommandEnvelope_RemoteCloudPreferEdge struct {
	RemoteCloudPreferEdge *RemoteCloudPreferEdgeCommand `protobuf:"bytes,116,opt,name=remote_cloud_prefer_edge,json=remoteCloudPreferEdge,proto3,oneof"`
}

type CommandEnvelope_RemoteCloudReselectEdge struct {
	RemoteCloudReselectEdge *RemoteCloudReselectEdgeCommand `protobuf:"bytes,117,opt,name=remote_cloud_reselect_edge,json=remoteCloudReselectEdge,proto3,oneof"`
}

func (*CommandEnvelope_CancelOperation) isCommandEnvelope_Command() {}

func (*CommandEnvelope_ReleaseResource) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalDefaults) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalCreate) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalList) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalGet) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalRestart) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalKill) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalRemove) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalSetMetadata) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalSetTags) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalAttach) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalDetach) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalInput) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalResize) isCommandEnvelope_Command() {}

func (*CommandEnvelope_TerminalResizeLock) isCommandEnvelope_Command() {}

func (*CommandEnvelope_PathListDirectories) isCommandEnvelope_Command() {}

func (*CommandEnvelope_HistoryWindow) isCommandEnvelope_Command() {}

func (*CommandEnvelope_HistoryCopy) isCommandEnvelope_Command() {}

func (*CommandEnvelope_HistoryRelease) isCommandEnvelope_Command() {}

func (*CommandEnvelope_HistoryBacklogStatus) isCommandEnvelope_Command() {}

func (*CommandEnvelope_LiveScreenNext) isCommandEnvelope_Command() {}

func (*CommandEnvelope_HistorySearch) isCommandEnvelope_Command() {}

func (*CommandEnvelope_EventSubscribe) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileList) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileStat) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FilePreview) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileMkdir) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileRename) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileDelete) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileCopy) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileMove) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileDownloadOpen) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileUploadOpen) isCommandEnvelope_Command() {}

func (*CommandEnvelope_FileTransferCancel) isCommandEnvelope_Command() {}

func (*CommandEnvelope_StorageGet) isCommandEnvelope_Command() {}

func (*CommandEnvelope_StoragePut) isCommandEnvelope_Command() {}

func (*CommandEnvelope_StorageDelete) isCommandEnvelope_Command() {}

func (*CommandEnvelope_StorageList) isCommandEnvelope_Command() {}

func (*CommandEnvelope_ClientAccessIdentity) isCommandEnvelope_Command() {}

func (*CommandEnvelope_ClientAccessList) isCommandEnvelope_Command() {}

func (*CommandEnvelope_ClientAccessTicketCreate) isCommandEnvelope_Command() {}

func (*CommandEnvelope_ClientAccessRevoke) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RemoteStatus) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RemotePairStart) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RemoteLocalEnable) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RemoteLocalStatus) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RemoteLocalDisable) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RemoteCloudEdges) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RemoteCloudPreferEdge) isCommandEnvelope_Command() {}

func (*CommandEnvelope_RemoteCloudReselectEdge) isCommandEnvelope_Command() {}

type AcknowledgeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeResult) Reset() {
	*x = AcknowledgeResult{}
	mi := &file_apipb_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeResult) ProtoMessage() {}

func (x *AcknowledgeResult) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeResult.ProtoReflect.Descriptor instead.
func (*AcknowledgeResult) Descriptor() ([]byte, []int) {
	return file_apipb_application_proto_rawDescGZIP(), []int{3}
}

type ResultEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	OriginSession *EndpointSessionStamp  `protobuf:"bytes,2,opt,name=origin_session,json=originSession,proto3" json:"origin_session,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*ResultEnvelope_Acknowledge
	//	*ResultEnvelope_Error
	//	*ResultEnvelope_TerminalDefaults
	//	*ResultEnvelope_TerminalCreate
	//	*ResultEnvelope_TerminalList
	//	*ResultEnvelope_TerminalGet
	//	*ResultEnvelope_TerminalAttach
	//	*ResultEnvelope_TerminalResize
	//	*ResultEnvelope_PathListDirectories
	//	*ResultEnvelope_HistoryWindow
	//	*ResultEnvelope_HistoryCopy
	//	*ResultEnvelope_HistoryBacklogStatus
	//	*ResultEnvelope_LiveScreen
	//	*ResultEnvelope_HistorySearch
	//	*ResultEnvelope_EventSubscription
	//	*ResultEnvelope_FileList
	//	*ResultEnvelope_FileStat
	//	*ResultEnvelope_FilePreview
	//	*ResultEnvelope_FileOperation
	//	*ResultEnvelope_FileBatch
	//	*ResultEnvelope_FileTransferOpen
	//	*ResultEnvelope_FileTransferCancel
	//	*ResultEnvelope_StorageGet
	//	*ResultEnvelope_StoragePut
	//	*ResultEnvelope_StorageDelete
	//	*ResultEnvelope_StorageList
	//	*ResultEnvelope_ClientAccessIdentity
	//	*ResultEnvelope_ClientAccessList
	//	*ResultEnvelope_ClientAccessTicketCreate
	//	*ResultEnvelope_ClientAccessRevoke
	//	*ResultEnvelope_RemoteStatus
	//	*ResultEnvelope_RemotePairStart
	//	*ResultEnvelope_RemoteLocalStatus
	//	*ResultEnvelope_RemoteCloudEdges
	Result        isResultEnvelope_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultEnvelope) Reset() {
	*x = ResultEnvelope{}
	mi := &file_apipb_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultEnvelope) ProtoMessage() {}

func (x *ResultEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultEnvelope.ProtoReflect.Descriptor instead.
func (*ResultEnvelope) Descriptor() ([]byte, []int) {
	return file_apipb_application_proto_rawDescGZIP(), []int{4}
}

func (x *ResultEnvelope) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ResultEnvelope) GetOriginSession() *EndpointSessionStamp {
	if x != nil {
		return x.OriginSession
	}
	return nil
}

func (x *ResultEnvelope) GetResult() isResultEnvelope_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ResultEnvelope) GetAcknowledge() *AcknowledgeResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_Acknowledge); ok {
			return x.Acknowledge
		}
	}
	return nil
}

func (x *ResultEnvelope) GetError() *ApiError {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ResultEnvelope) GetTerminalDefaults() *TerminalDefaultsResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_TerminalDefaults); ok {
			return x.TerminalDefaults
		}
	}
	return nil
}

func (x *ResultEnvelope) GetTerminalCreate() *TerminalCreateResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_TerminalCreate); ok {
			return x.TerminalCreate
		}
	}
	return nil
}

func (x *ResultEnvelope) GetTerminalList() *TerminalListResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_TerminalList); ok {
			return x.TerminalList
		}
	}
	return nil
}

func (x *ResultEnvelope) GetTerminalGet() *TerminalGetResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_TerminalGet); ok {
			return x.TerminalGet
		}
	}
	return nil
}

func (x *ResultEnvelope) GetTerminalAttach() *TerminalAttachResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_TerminalAttach); ok {
			return x.TerminalAttach
		}
	}
	return nil
}

func (x *ResultEnvelope) GetTerminalResize() *TerminalResizeResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_TerminalResize); ok {
			return x.TerminalResize
		}
	}
	return nil
}

func (x *ResultEnvelope) GetPathListDirectories() *PathListDirectoriesResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_PathListDirectories); ok {
			return x.PathListDirectories
		}
	}
	return nil
}

func (x *ResultEnvelope) GetHistoryWindow() *HistoryWindowResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_HistoryWindow); ok {
			return x.HistoryWindow
		}
	}
	return nil
}

func (x *ResultEnvelope) GetHistoryCopy() *HistoryCopyResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_HistoryCopy); ok {
			return x.HistoryCopy
		}
	}
	return nil
}

func (x *ResultEnvelope) GetHistoryBacklogStatus() *HistoryBacklogStatusResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_HistoryBacklogStatus); ok {
			return x.HistoryBacklogStatus
		}
	}
	return nil
}

func (x *ResultEnvelope) GetLiveScreen() *NativeScreenResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_LiveScreen); ok {
			return x.LiveScreen
		}
	}
	return nil
}

func (x *ResultEnvelope) GetHistorySearch() *HistorySearchResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_HistorySearch); ok {
			return x.HistorySearch
		}
	}
	return nil
}

func (x *ResultEnvelope) GetEventSubscription() *EventSubscriptionResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_EventSubscription); ok {
			return x.EventSubscription
		}
	}
	return nil
}

func (x *ResultEnvelope) GetFileList() *FileListResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_FileList); ok {
			return x.FileList
		}
	}
	return nil
}

func (x *ResultEnvelope) GetFileStat() *FileStatResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_FileStat); ok {
			return x.FileStat
		}
	}
	return nil
}

func (x *ResultEnvelope) GetFilePreview() *FilePreviewResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_FilePreview); ok {
			return x.FilePreview
		}
	}
	return nil
}

func (x *ResultEnvelope) GetFileOperation() *FileOperationResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_FileOperation); ok {
			return x.FileOperation
		}
	}
	return nil
}

func (x *ResultEnvelope) GetFileBatch() *FileBatchResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_FileBatch); ok {
			return x.FileBatch
		}
	}
	return nil
}

func (x *ResultEnvelope) GetFileTransferOpen() *FileTransferOpenResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_FileTransferOpen); ok {
			return x.FileTransferOpen
		}
	}
	return nil
}

func (x *ResultEnvelope) GetFileTransferCancel() *FileTransferCancelResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_FileTransferCancel); ok {
			return x.FileTransferCancel
		}
	}
	return nil
}

func (x *ResultEnvelope) GetStorageGet() *StorageGetResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_StorageGet); ok {
			return x.StorageGet
		}
	}
	return nil
}

func (x *ResultEnvelope) GetStoragePut() *StoragePutResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_StoragePut); ok {
			return x.StoragePut
		}
	}
	return nil
}

func (x *ResultEnvelope) GetStorageDelete() *StorageDeleteResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_StorageDelete); ok {
			return x.StorageDelete
		}
	}
	return nil
}

func (x *ResultEnvelope) GetStorageList() *StorageListResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_StorageList); ok {
			return x.StorageList
		}
	}
	return nil
}

func (x *ResultEnvelope) GetClientAccessIdentity() *ClientAccessIdentityResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_ClientAccessIdentity); ok {
			return x.ClientAccessIdentity
		}
	}
	return nil
}

func (x *ResultEnvelope) GetClientAccessList() *ClientAccessListResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_ClientAccessList); ok {
			return x.ClientAccessList
		}
	}
	return nil
}

func (x *ResultEnvelope) GetClientAccessTicketCreate() *ClientAccessTicketCreateResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_ClientAccessTicketCreate); ok {
			return x.ClientAccessTicketCreate
		}
	}
	return nil
}

func (x *ResultEnvelope) GetClientAccessRevoke() *ClientAccessRevokeResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_ClientAccessRevoke); ok {
			return x.ClientAccessRevoke
		}
	}
	return nil
}

func (x *ResultEnvelope) GetRemoteStatus() *RemoteStatusResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_RemoteStatus); ok {
			return x.RemoteStatus
		}
	}
	return nil
}

func (x *ResultEnvelope) GetRemotePairStart() *RemotePairStartResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_RemotePairStart); ok {
			return x.RemotePairStart
		}
	}
	return nil
}

func (x *ResultEnvelope) GetRemoteLocalStatus() *RemoteLocalStatusResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_RemoteLocalStatus); ok {
			return x.RemoteLocalStatus
		}
	}
	return nil
}

func (x *ResultEnvelope) GetRemoteCloudEdges() *RemoteCloudEdgesResult {
	if x != nil {
		if x, ok := x.Result.(*ResultEnvelope_RemoteCloudEdges); ok {
			return x.RemoteCloudEdges
		}
	}
	return nil
}

type isResultEnvelope_Result interface {
	isResultEnvelope_Result()
}

type ResultEnvelope_Acknowledge struct {
	Acknowledge *AcknowledgeResult `protobuf:"bytes,10,opt,name=acknowledge,proto3,oneof"`
}

type ResultEnvelope_Error struct {
	Error *ApiError `protobuf:"bytes,11,opt,name=error,proto3,oneof"`
}

type ResultEnvelope_TerminalDefaults struct {
	TerminalDefaults *TerminalDefaultsResult `protobuf:"bytes,20,opt,name=terminal_defaults,json=terminalDefaults,proto3,oneof"`
}

type ResultEnvelope_TerminalCreate struct {
	TerminalCreate *TerminalCreateResult `protobuf:"bytes,21,opt,name=terminal_create,json=terminalCreate,proto3,oneof"`
}

type ResultEnvelope_TerminalList struct {
	TerminalList *TerminalListResult `protobuf:"bytes,22,opt,name=terminal_list,json=terminalList,proto3,oneof"`
}

type ResultEnvelope_TerminalGet struct {
	TerminalGet *TerminalGetResult `protobuf:"bytes,23,opt,name=terminal_get,json=terminalGet,proto3,oneof"`
}

type ResultEnvelope_TerminalAttach struct {
	TerminalAttach *TerminalAttachResult `protobuf:"bytes,24,opt,name=terminal_attach,json=terminalAttach,proto3,oneof"`
}

type ResultEnvelope_TerminalResize struct {
	TerminalResize *TerminalResizeResult `protobuf:"bytes,25,opt,name=terminal_resize,json=terminalResize,proto3,oneof"`
}

type ResultEnvelope_PathListDirectories struct {
	PathListDirectories *PathListDirectoriesResult `protobuf:"bytes,26,opt,name=path_list_directories,json=pathListDirectories,proto3,oneof"`
}

type ResultEnvelope_HistoryWindow struct {
	HistoryWindow *HistoryWindowResult `protobuf:"bytes,40,opt,name=history_window,json=historyWindow,proto3,oneof"`
}

type ResultEnvelope_HistoryCopy struct {
	HistoryCopy *HistoryCopyResult `protobuf:"bytes,41,opt,name=history_copy,json=historyCopy,proto3,oneof"`
}

type ResultEnvelope_HistoryBacklogStatus struct {
	HistoryBacklogStatus *HistoryBacklogStatusResult `protobuf:"bytes,42,opt,name=history_backlog_status,json=historyBacklogStatus,proto3,oneof"`
}

type ResultEnvelope_LiveScreen struct {
	LiveScreen *NativeScreenResult `protobuf:"bytes,43,opt,name=live_screen,json=liveScreen,proto3,oneof"`
}

type ResultEnvelope_HistorySearch struct {
	HistorySearch *HistorySearchResult `protobuf:"bytes,44,opt,name=history_search,json=historySearch,proto3,oneof"`
}

type ResultEnvelope_EventSubscription struct {
	EventSubscription *EventSubscriptionResult `protobuf:"bytes,45,opt,name=event_subscription,json=eventSubscription,proto3,oneof"`
}

type ResultEnvelope_FileList struct {
	FileList *FileListResult `protobuf:"bytes,60,opt,name=file_list,json=fileList,proto3,oneof"`
}

type ResultEnvelope_FileStat struct {
	FileStat *FileStatResult `protobuf:"bytes,61,opt,name=file_stat,json=fileStat,proto3,oneof"`
}

type ResultEnvelope_FilePreview struct {
	FilePreview *FilePreviewResult `protobuf:"bytes,62,opt,name=file_preview,json=filePreview,proto3,oneof"`
}

type ResultEnvelope_FileOperation struct {
	FileOperation *FileOperationResult `protobuf:"bytes,63,opt,name=file_operation,json=fileOperation,proto3,oneof"`
}

type ResultEnvelope_FileBatch struct {
	FileBatch *FileBatchResult `protobuf:"bytes,64,opt,name=file_batch,json=fileBatch,proto3,oneof"`
}

type ResultEnvelope_FileTransferOpen struct {
	FileTransferOpen *FileTransferOpenResult `protobuf:"bytes,65,opt,name=file_transfer_open,json=fileTransferOpen,proto3,oneof"`
}

type ResultEnvelope_FileTransferCancel struct {
	FileTransferCancel *FileTransferCancelResult `protobuf:"bytes,66,opt,name=file_transfer_cancel,json=fileTransferCancel,proto3,oneof"`
}

type ResultEnvelope_StorageGet struct {
	StorageGet *StorageGetResult `protobuf:"bytes,80,opt,name=storage_get,json=storageGet,proto3,oneof"`
}

type ResultEnvelope_StoragePut struct {
	StoragePut *StoragePutResult `protobuf:"bytes,81,opt,name=storage_put,json=storagePut,proto3,oneof"`
}

type ResultEnvelope_StorageDelete struct {
	StorageDelete *StorageDeleteResult `protobuf:"bytes,82,opt,name=storage_delete,json=storageDelete,proto3,oneof"`
}

type ResultEnvelope_StorageList struct {
	StorageList *StorageListResult `protobuf:"bytes,83,opt,name=storage_list,json=storageList,proto3,oneof"`
}

type ResultEnvelope_ClientAccessIdentity struct {
	ClientAccessIdentity *ClientAccessIdentityResult `protobuf:"bytes,100,opt,name=client_access_identity,json=clientAccessIdentity,proto3,oneof"`
}

type ResultEnvelope_ClientAccessList struct {
	ClientAccessList *ClientAccessListResult `protobuf:"bytes,101,opt,name=client_access_list,json=clientAccessList,proto3,oneof"`
}

type ResultEnvelope_ClientAccessTicketCreate struct {
	ClientAccessTicketCreate *ClientAccessTicketCreateResult `protobuf:"bytes,102,opt,name=client_access_ticket_create,json=clientAccessTicketCreate,proto3,oneof"`
}

type ResultEnvelope_ClientAccessRevoke struct {
	ClientAccessRevoke *ClientAccessRevokeResult `protobuf:"bytes,103,opt,name=client_access_revoke,json=clientAccessRevoke,proto3,oneof"`
}

type ResultEnvelope_RemoteStatus struct {
	RemoteStatus *RemoteStatusResult `protobuf:"bytes,110,opt,name=remote_status,json=remoteStatus,proto3,oneof"`
}

type ResultEnvelope_RemotePairStart struct {
	RemotePairStart *RemotePairStartResult `protobuf:"bytes,111,opt,name=remote_pair_start,json=remotePairStart,proto3,oneof"`
}

type ResultEnvelope_RemoteLocalStatus struct {
	RemoteLocalStatus *RemoteLocalStatusResult `protobuf:"bytes,112,opt,name=remote_local_status,json=remoteLocalStatus,proto3,oneof"`
}

type ResultEnvelope_RemoteCloudEdges struct {
	RemoteCloudEdges *RemoteCloudEdgesResult `protobuf:"bytes,113,opt,name=remote_cloud_edges,json=remoteCloudEdges,proto3,oneof"`
}

func (*ResultEnvelope_Acknowledge) isResultEnvelope_Result() {}

func (*ResultEnvelope_Error) isResultEnvelope_Result() {}

func (*ResultEnvelope_TerminalDefaults) isResultEnvelope_Result() {}

func (*ResultEnvelope_TerminalCreate) isResultEnvelope_Result() {}

func (*ResultEnvelope_TerminalList) isResultEnvelope_Result() {}

func (*ResultEnvelope_TerminalGet) isResultEnvelope_Result() {}

func (*ResultEnvelope_TerminalAttach) isResultEnvelope_Result() {}

func (*ResultEnvelope_TerminalResize) isResultEnvelope_Result() {}

func (*ResultEnvelope_PathListDirectories) isResultEnvelope_Result() {}

func (*ResultEnvelope_HistoryWindow) isResultEnvelope_Result() {}

func (*ResultEnvelope_HistoryCopy) isResultEnvelope_Result() {}

func (*ResultEnvelope_HistoryBacklogStatus) isResultEnvelope_Result() {}

func (*ResultEnvelope_LiveScreen) isResultEnvelope_Result() {}

func (*ResultEnvelope_HistorySearch) isResultEnvelope_Result() {}

func (*ResultEnvelope_EventSubscription) isResultEnvelope_Result() {}

func (*ResultEnvelope_FileList) isResultEnvelope_Result() {}

func (*ResultEnvelope_FileStat) isResultEnvelope_Result() {}

func (*ResultEnvelope_FilePreview) isResultEnvelope_Result() {}

func (*ResultEnvelope_FileOperation) isResultEnvelope_Result() {}

func (*ResultEnvelope_FileBatch) isResultEnvelope_Result() {}

func (*ResultEnvelope_FileTransferOpen) isResultEnvelope_Result() {}

func (*ResultEnvelope_FileTransferCancel) isResultEnvelope_Result() {}

func (*ResultEnvelope_StorageGet) isResultEnvelope_Result() {}

func (*ResultEnvelope_StoragePut) isResultEnvelope_Result() {}

func (*ResultEnvelope_StorageDelete) isResultEnvelope_Result() {}

func (*ResultEnvelope_StorageList) isResultEnvelope_Result() {}

func (*ResultEnvelope_ClientAccessIdentity) isResultEnvelope_Result() {}

func (*ResultEnvelope_ClientAccessList) isResultEnvelope_Result() {}

func (*ResultEnvelope_ClientAccessTicketCreate) isResultEnvelope_Result() {}

func (*ResultEnvelope_ClientAccessRevoke) isResultEnvelope_Result() {}

func (*ResultEnvelope_RemoteStatus) isResultEnvelope_Result() {}

func (*ResultEnvelope_RemotePairStart) isResultEnvelope_Result() {}

func (*ResultEnvelope_RemoteLocalStatus) isResultEnvelope_Result() {}

func (*ResultEnvelope_RemoteCloudEdges) isResultEnvelope_Result() {}

type OperationCancelledEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *OperationStamp        `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationCancelledEvent) Reset() {
	*x = OperationCancelledEvent{}
	mi := &file_apipb_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationCancelledEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationCancelledEvent) ProtoMessage() {}

func (x *OperationCancelledEvent) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationCancelledEvent.ProtoReflect.Descriptor instead.
func (*OperationCancelledEvent) Descriptor() ([]byte, []int) {
	return file_apipb_application_proto_rawDescGZIP(), []int{5}
}

func (x *OperationCancelledEvent) GetOperation() *OperationStamp {
	if x != nil {
		return x.Operation
	}
	return nil
}

type ResourceReleasedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      *ResourceHandle        `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceReleasedEvent) Reset() {
	*x = ResourceReleasedEvent{}
	mi := &file_apipb_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceReleasedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceReleasedEvent) ProtoMessage() {}

func (x *ResourceReleasedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceReleasedEvent.ProtoReflect.Descriptor instead.
func (*ResourceReleasedEvent) Descriptor() ([]byte, []int) {
	return file_apipb_application_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceReleasedEvent) GetResource() *ResourceHandle {
	if x != nil {
		return x.Resource
	}
	return nil
}

type EventEnvelope struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	EventId           string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TimestampUnixNano int64                  `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	ApiVersion        *ApiVersion            `protobuf:"bytes,3,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	OriginSession     *EndpointSessionStamp  `protobuf:"bytes,4,opt,name=origin_session,json=originSession,proto3" json:"origin_session,omitempty"`
	Subscription      *ResourceHandle        `protobuf:"bytes,5,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*EventEnvelope_OperationCancelled
	//	*EventEnvelope_ResourceReleased
	//	*EventEnvelope_TerminalLifecycle
	//	*EventEnvelope_StorageChanged
	//	*EventEnvelope_FileTransferCompleted
	Event         isEventEnvelope_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventEnvelope) Reset() {
	*x = EventEnvelope{}
	mi := &file_apipb_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventEnvelope) ProtoMessage() {}

func (x *EventEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_apipb_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventEnvelope.ProtoReflect.Descriptor instead.
func (*EventEnvelope) Descriptor() ([]byte, []int) {
	return file_apipb_application_proto_rawDescGZIP(), []int{7}
}

func (x *EventEnvelope) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventEnvelope) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *EventEnvelope) GetApiVersion() *ApiVersion {
	if x != nil {
		return x.ApiVersion
	}
	return nil
}

func (x *EventEnvelope) GetOriginSession() *EndpointSessionStamp {
	if x != nil {
		return x.OriginSession
	}
	return nil
}

func (x *EventEnvelope) GetSubscription() *ResourceHandle {
	if x != nil {
		return x.Subscription
	}
	return nil
}

func (x *EventEnvelope) GetEvent() isEventEnvelope_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *EventEnvelope) GetOperationCancelled() *OperationCancelledEvent {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_OperationCancelled); ok {
			return x.OperationCancelled
		}
	}
	return nil
}

func (x *EventEnvelope) GetResourceReleased() *ResourceReleasedEvent {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_ResourceReleased); ok {
			return x.ResourceReleased
		}
	}
	return nil
}

func (x *EventEnvelope) GetTerminalLifecycle() *TerminalLifecycleEvent {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_TerminalLifecycle); ok {
			return x.TerminalLifecycle
		}
	}
	return nil
}

func (x *EventEnvelope) GetStorageChanged() *StorageChangedEvent {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_StorageChanged); ok {
			return x.StorageChanged
		}
	}
	return nil
}

func (x *EventEnvelope) GetFileTransferCompleted() *FileTransferCompletedEvent {
	if x != nil {
		if x, ok := x.Event.(*EventEnvelope_FileTransferCompleted); ok {
			return x.FileTransferCompleted
		}
	}
	return nil
}

type isEventEnvelope_Event interface {
	isEventEnvelope_Event()
}

type EventEnvelope_OperationCancelled struct {
	OperationCancelled *OperationCancelledEvent `protobuf:"bytes,10,opt,name=operation_cancelled,json=operationCancelled,proto3,oneof"`
}

type EventEnvelope_ResourceReleased struct {
	ResourceReleased *ResourceReleasedEvent `protobuf:"bytes,11,opt,name=resource_released,json=resourceReleased,proto3,oneof"`
}

type EventEnvelope_TerminalLifecycle struct {
	TerminalLifecycle *TerminalLifecycleEvent `protobuf:"bytes,20,opt,name=terminal_lifecycle,json=terminalLifecycle,proto3,oneof"`
}

type EventEnvelope_StorageChanged struct {
	StorageChanged *StorageChangedEvent `protobuf:"bytes,30,opt,name=storage_changed,json=storageChanged,proto3,oneof"`
}

type EventEnvelope_FileTransferCompleted struct {
	FileTransferCompleted *FileTransferCompletedEvent `protobuf:"bytes,40,opt,name=file_transfer_completed,json=fileTransferCompleted,proto3,oneof"`
}

func (*EventEnvelope_OperationCancelled) isEventEnvelope_Event() {}

func (*EventEnvelope_ResourceReleased) isEventEnvelope_Event() {}

func (*EventEnvelope_TerminalLifecycle) isEventEnvelope_Event() {}

func (*EventEnvelope_StorageChanged) isEventEnvelope_Event() {}

func (*EventEnvelope_FileTransferCompleted) isEventEnvelope_Event() {}

var File_apipb_application_proto protoreflect.FileDescriptor

const file_apipb_application_proto_rawDesc = "" +
	"\n" +
	"\x17apipb/application.proto\x12\ranytty.api.v1\x1a\x12apipb/common.proto\x1a\x19apipb/access_remote.proto\x1a\x12apipb/events.proto\x1a\x10apipb/file.proto\x1a\x13apipb/history.proto\x1a\x13apipb/storage.proto\x1a\x14apipb/terminal.proto\"[\n" +
	"\x16CancelOperationCommand\x12;\n" +
	"\toperation\x18\x02 \x01(\v2\x1d.anytty.api.v1.OperationStampR\toperationJ\x04\b\x01\x10\x02\"Y\n" +
	"\x16ReleaseResourceCommand\x129\n" +
	"\bresource\x18\x02 \x01(\v2\x1d.anytty.api.v1.ResourceHandleR\bresourceJ\x04\b\x01\x10\x02\"\xbf!\n" +
	"\x0fCommandEnvelope\x127\n" +
	"\acontext\x18\x01 \x01(\v2\x1d.anytty.api.v1.RequestContextR\acontext\x12R\n" +
	"\x10cancel_operation\x18\n" +
	" \x01(\v2%.anytty.api.v1.CancelOperationCommandH\x00R\x0fcancelOperation\x12R\n" +
	"\x10release_resource\x18\v \x01(\v2%.anytty.api.v1.ReleaseResourceCommandH\x00R\x0freleaseResource\x12U\n" +
	"\x11terminal_defaults\x18\x14 \x01(\v2&.anytty.api.v1.TerminalDefaultsCommandH\x00R\x10terminalDefaults\x12O\n" +
	"\x0fterminal_create\x18\x15 \x01(\v2$.anytty.api.v1.TerminalCreateCommandH\x00R\x0eterminalCreate\x12I\n" +
	"\rterminal_list\x18\x16 \x01(\v2\".anytty.api.v1.TerminalListCommandH\x00R\fterminalList\x12F\n" +
	"\fterminal_get\x18\x17 \x01(\v2!.anytty.api.v1.TerminalGetCommandH\x00R\vterminalGet\x12R\n" +
	"\x10terminal_restart\x18\x18 \x01(\v2%.anytty.api.v1.TerminalRestartCommandH\x00R\x0fterminalRestart\x12I\n" +
	"\rterminal_kill\x18\x19 \x01(\v2\".anytty.api.v1.TerminalKillCommandH\x00R\fterminalKill\x12O\n" +
	"\x0fterminal_remove\x18\x1a \x01(\v2$.anytty.api.v1.TerminalRemoveCommandH\x00R\x0eterminalRemove\x12_\n" +
	"\x15terminal_set_metadata\x18\x1b \x01(\v2).anytty.api.v1.TerminalSetMetadataCommandH\x00R\x13terminalSetMetadata\x12S\n" +
	"\x11terminal_set_tags\x18\x1c \x01(\v2%.anytty.api.v1.TerminalSetTagsCommandH\x00R\x0fterminalSetTags\x12O\n" +
	"\x0fterminal_attach\x18\x1d \x01(\v2$.anytty.api.v1.TerminalAttachCommandH\x00R\x0eterminalAttach\x12O\n" +
	"\x0fterminal_detach\x18\x1e \x01(\v2$.anytty.api.v1.TerminalDetachCommandH\x00R\x0eterminalDetach\x12L\n" +
	"\x0eterminal_input\x18\x1f \x01(\v2#.anytty.api.v1.TerminalInputCommandH\x00R\rterminalInput\x12O\n" +
	"\x0fterminal_resize\x18  \x01(\v2$.anytty.api.v1.TerminalResizeCommandH\x00R\x0eterminalResize\x12\\\n" +
	"\x14terminal_resize_lock\x18! \x01(\v2(.anytty.api.v1.TerminalResizeLockCommandH\x00R\x12terminalResizeLock\x12_\n" +
	"\x15path_list_directories\x18\" \x01(\v2).anytty.api.v1.PathListDirectoriesCommandH\x00R\x13pathListDirectories\x12L\n" +
	"\x0ehistory_window\x18( \x01(\v2#.anytty.api.v1.HistoryWindowCommandH\x00R\rhistoryWindow\x12F\n" +
	"\fhistory_copy\x18) \x01(\v2!.anytty.api.v1.HistoryCopyCommandH\x00R\vhistoryCopy\x12O\n" +
	"\x0fhistory_release\x18* \x01(\v2$.anytty.api.v1.HistoryReleaseCommandH\x00R\x0ehistoryRelease\x12b\n" +
	"\x16history_backlog_status\x18+ \x01(\v2*.anytty.api.v1.HistoryBacklogStatusCommandH\x00R\x14historyBacklogStatus\x12P\n" +
	"\x10live_screen_next\x18, \x01(\v2$.anytty.api.v1.LiveScreenNextCommandH\x00R\x0eliveScreenNext\x12L\n" +
	"\x0ehistory_search\x18- \x01(\v2#.anytty.api.v1.HistorySearchCommandH\x00R\rhistorySearch\x12O\n" +
	"\x0fevent_subscribe\x18. \x01(\v2$.anytty.api.v1.EventSubscribeCommandH\x00R\x0eeventSubscribe\x12=\n" +
	"\tfile_list\x18< \x01(\v2\x1e.anytty.api.v1.FileListCommandH\x00R\bfileList\x12=\n" +
	"\tfile_stat\x18= \x01(\v2\x1e.anytty.api.v1.FileStatCommandH\x00R\bfileStat\x12F\n" +
	"\ffile_preview\x18> \x01(\v2!.anytty.api.v1.FilePreviewCommandH\x00R\vfilePreview\x12@\n" +
	"\n" +
	"file_mkdir\x18? \x01(\v2\x1f.anytty.api.v1.FileMkdirCommandH\x00R\tfileMkdir\x12C\n" +
	"\vfile_rename\x18@ \x01(\v2 .anytty.api.v1.FileRenameCommandH\x00R\n" +
	"fileRename\x12C\n" +
	"\vfile_delete\x18A \x01(\v2 .anytty.api.v1.FileDeleteCommandH\x00R\n" +
	"fileDelete\x12=\n" +
	"\tfile_copy\x18B \x01(\v2\x1e.anytty.api.v1.FileCopyCommandH\x00R\bfileCopy\x12=\n" +
	"\tfile_move\x18C \x01(\v2\x1e.anytty.api.v1.FileMoveCommandH\x00R\bfileMove\x12V\n" +
	"\x12file_download_open\x18D \x01(\v2&.anytty.api.v1.FileDownloadOpenCommandH\x00R\x10fileDownloadOpen\x12P\n" +
	"\x10file_upload_open\x18E \x01(\v2$.anytty.api.v1.FileUploadOpenCommandH\x00R\x0efileUploadOpen\x12\\\n" +
	"\x14file_transfer_cancel\x18F \x01(\v2(.anytty.api.v1.FileTransferCancelCommandH\x00R\x12fileTransferCancel\x12C\n" +
	"\vstorage_get\x18P \x01(\v2 .anytty.api.v1.StorageGetCommandH\x00R\n" +
	"storageGet\x12C\n" +
	"\vstorage_put\x18Q \x01(\v2 .anytty.api.v1.StoragePutCommandH\x00R\n" +
	"storagePut\x12L\n" +
	"\x0estorage_delete\x18R \x01(\v2#.anytty.api.v1.StorageDeleteCommandH\x00R\rstorageDelete\x12F\n" +
	"\fstorage_list\x18S \x01(\v2!.anytty.api.v1.StorageListCommandH\x00R\vstorageList\x12b\n" +
	"\x16client_access_identity\x18d \x01(\v2*.anytty.api.v1.ClientAccessIdentityCommandH\x00R\x14clientAccessIdentity\x12V\n" +
	"\x12client_access_list\x18e \x01(\v2&.anytty.api.v1.ClientAccessListCommandH\x00R\x10clientAccessList\x12o\n" +
	"\x1bclient_access_ticket_create\x18f \x01(\v2..anytty.api.v1.ClientAccessTicketCreateCommandH\x00R\x18clientAccessTicketCreate\x12\\\n" +
	"\x14client_access_revoke\x18g \x01(\v2(.anytty.api.v1.ClientAccessRevokeCommandH\x00R\x12clientAccessRevoke\x12I\n" +
	"\rremote_status\x18n \x01(\v2\".anytty.api.v1.RemoteStatusCommandH\x00R\fremoteStatus\x12S\n" +
	"\x11remote_pair_start\x18o \x01(\v2%.anytty.api.v1.RemotePairStartCommandH\x00R\x0fremotePairStart\x12Y\n" +
	"\x13remote_local_enable\x18p \x01(\v2'.anytty.api.v1.RemoteLocalEnableCommandH\x00R\x11remoteLocalEnable\x12Y\n" +
	"\x13remote_local_status\x18q \x01(\v2'.anytty.api.v1.RemoteLocalStatusCommandH\x00R\x11remoteLocalStatus\x12\\\n" +
	"\x14remote_local_disable\x18r \x01(\v2(.anytty.api.v1.RemoteLocalDisableCommandH\x00R\x12remoteLocalDisable\x12V\n" +
	"\x12remote_cloud_edges\x18s \x01(\v2&.anytty.api.v1.RemoteCloudEdgesCommandH\x00R\x10remoteCloudEdges\x12f\n" +
	"\x18remote_cloud_prefer_edge\x18t \x01(\v2+.anytty.api.v1.RemoteCloudPreferEdgeCommandH\x00R\x15remoteCloudPreferEdge\x12l\n" +
	"\x1aremote_cloud_reselect_edge\x18u \x01(\v2-.anytty.api.v1.RemoteCloudReselectEdgeCommandH\x00R\x17remoteCloudReselectEdgeB\t\n" +
	"\acommand\"\x13\n" +
	"\x11AcknowledgeResult\"\x8d\x16\n" +
	"\x0eResultEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12J\n" +
	"\x0eorigin_session\x18\x02 \x01(\v2#.anytty.api.v1.EndpointSessionStampR\roriginSession\x12D\n" +
	"\vacknowledge\x18\n" +
	" \x01(\v2 .anytty.api.v1.AcknowledgeResultH\x00R\vacknowledge\x12/\n" +
	"\x05error\x18\v \x01(\v2\x17.anytty.api.v1.ApiErrorH\x00R\x05error\x12T\n" +
	"\x11terminal_defaults\x18\x14 \x01(\v2%.anytty.api.v1.TerminalDefaultsResultH\x00R\x10terminalDefaults\x12N\n" +
	"\x0fterminal_create\x18\x15 \x01(\v2#.anytty.api.v1.TerminalCreateResultH\x00R\x0eterminalCreate\x12H\n" +
	"\rterminal_list\x18\x16 \x01(\v2!.anytty.api.v1.TerminalListResultH\x00R\fterminalList\x12E\n" +
	"\fterminal_get\x18\x17 \x01(\v2 .anytty.api.v1.TerminalGetResultH\x00R\vterminalGet\x12N\n" +
	"\x0fterminal_attach\x18\x18 \x01(\v2#.anytty.api.v1.TerminalAttachResultH\x00R\x0eterminalAttach\x12N\n" +
	"\x0fterminal_resize\x18\x19 \x01(\v2#.anytty.api.v1.TerminalResizeResultH\x00R\x0eterminalResize\x12^\n" +
	"\x15path_list_directories\x18\x1a \x01(\v2(.anytty.api.v1.PathListDirectoriesResultH\x00R\x13pathListDirectories\x12K\n" +
	"\x0ehistory_window\x18( \x01(\v2\".anytty.api.v1.HistoryWindowResultH\x00R\rhistoryWindow\x12E\n" +
	"\fhistory_copy\x18) \x01(\v2 .anytty.api.v1.HistoryCopyResultH\x00R\vhistoryCopy\x12a\n" +
	"\x16history_backlog_status\x18* \x01(\v2).anytty.api.v1.HistoryBacklogStatusResultH\x00R\x14historyBacklogStatus\x12D\n" +
	"\vlive_screen\x18+ \x01(\v2!.anytty.api.v1.NativeScreenResultH\x00R\n" +
	"liveScreen\x12K\n" +
	"\x0ehistory_search\x18, \x01(\v2\".anytty.api.v1.HistorySearchResultH\x00R\rhistorySearch\x12W\n" +
	"\x12event_subscription\x18- \x01(\v2&.anytty.api.v1.EventSubscriptionResultH\x00R\x11eventSubscription\x12<\n" +
	"\tfile_list\x18< \x01(\v2\x1d.anytty.api.v1.FileListResultH\x00R\bfileList\x12<\n" +
	"\tfile_stat\x18= \x01(\v2\x1d.anytty.api.v1.FileStatResultH\x00R\bfileStat\x12E\n" +
	"\ffile_preview\x18> \x01(\v2 .anytty.api.v1.FilePreviewResultH\x00R\vfilePreview\x12K\n" +
	"\x0efile_operation\x18? \x01(\v2\".anytty.api.v1.FileOperationResultH\x00R\rfileOperation\x12?\n" +
	"\n" +
	"file_batch\x18@ \x01(\v2\x1e.anytty.api.v1.FileBatchResultH\x00R\tfileBatch\x12U\n" +
	"\x12file_transfer_open\x18A \x01(\v2%.anytty.api.v1.FileTransferOpenResultH\x00R\x10fileTransferOpen\x12[\n" +
	"\x14file_transfer_cancel\x18B \x01(\v2'.anytty.api.v1.FileTransferCancelResultH\x00R\x12fileTransferCancel\x12B\n" +
	"\vstorage_get\x18P \x01(\v2\x1f.anytty.api.v1.StorageGetResultH\x00R\n" +
	"storageGet\x12B\n" +
	"\vstorage_put\x18Q \x01(\v2\x1f.anytty.api.v1.StoragePutResultH\x00R\n" +
	"storagePut\x12K\n" +
	"\x0estorage_delete\x18R \x01(\v2\".anytty.api.v1.StorageDeleteResultH\x00R\rstorageDelete\x12E\n" +
	"\fstorage_list\x18S \x01(\v2 .anytty.api.v1.StorageListResultH\x00R\vstorageList\x12a\n" +
	"\x16client_access_identity\x18d \x01(\v2).anytty.api.v1.ClientAccessIdentityResultH\x00R\x14clientAccessIdentity\x12U\n" +
	"\x12client_access_list\x18e \x01(\v2%.anytty.api.v1.ClientAccessListResultH\x00R\x10clientAccessList\x12n\n" +
	"\x1bclient_access_ticket_create\x18f \x01(\v2-.anytty.api.v1.ClientAccessTicketCreateResultH\x00R\x18clientAccessTicketCreate\x12[\n" +
	"\x14client_access_revoke\x18g \x01(\v2'.anytty.api.v1.ClientAccessRevokeResultH\x00R\x12clientAccessRevoke\x12H\n" +
	"\rremote_status\x18n \x01(\v2!.anytty.api.v1.RemoteStatusResultH\x00R\fremoteStatus\x12R\n" +
	"\x11remote_pair_start\x18o \x01(\v2$.anytty.api.v1.RemotePairStartResultH\x00R\x0fremotePairStart\x12X\n" +
	"\x13remote_local_status\x18p \x01(\v2&.anytty.api.v1.RemoteLocalStatusResultH\x00R\x11remoteLocalStatus\x12U\n" +
	"\x12remote_cloud_edges\x18q \x01(\v2%.anytty.api.v1.RemoteCloudEdgesResultH\x00R\x10remoteCloudEdgesB\b\n" +
	"\x06result\"V\n" +
	"\x17OperationCancelledEvent\x12;\n" +
	"\toperation\x18\x01 \x01(\v2\x1d.anytty.api.v1.OperationStampR\toperation\"R\n" +
	"\x15ResourceReleasedEvent\x129\n" +
	"\bresource\x18\x01 \x01(\v2\x1d.anytty.api.v1.ResourceHandleR\bresource\"\xfc\x05\n" +
	"\rEventEnvelope\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12.\n" +
	"\x13timestamp_unix_nano\x18\x02 \x01(\x03R\x11timestampUnixNano\x12:\n" +
	"\vapi_version\x18\x03 \x01(\v2\x19.anytty.api.v1.ApiVersionR\n" +
	"apiVersion\x12J\n" +
	"\x0eorigin_session\x18\x04 \x01(\v2#.anytty.api.v1.EndpointSessionStampR\roriginSession\x12A\n" +
	"\fsubscription\x18\x05 \x01(\v2\x1d.anytty.api.v1.ResourceHandleR\fsubscription\x12Y\n" +
	"\x13operation_cancelled\x18\n" +
	" \x01(\v2&.anytty.api.v1.OperationCancelledEventH\x00R\x12operationCancelled\x12S\n" +
	"\x11resource_released\x18\v \x01(\v2$.anytty.api.v1.ResourceReleasedEventH\x00R\x10resourceReleased\x12V\n" +
	"\x12terminal_lifecycle\x18\x14 \x01(\v2%.anytty.api.v1.TerminalLifecycleEventH\x00R\x11terminalLifecycle\x12M\n" +
	"\x0fstorage_changed\x18\x1e \x01(\v2\".anytty.api.v1.StorageChangedEventH\x00R\x0estorageChanged\x12c\n" +
	"\x17file_transfer_completed\x18( \x01(\v2).anytty.api.v1.FileTransferCompletedEventH\x00R\x15fileTransferCompletedB\a\n" +
	"\x05eventJ\x04\b\x15\x10\x16J\x04\b\x16\x10\x17J\x04\b\x17\x10\x18B&Z$github.com/anytty/anytty/proto/apipbb\x06proto3"

var (
	file_apipb_application_proto_rawDescOnce sync.Once
	file_apipb_application_proto_rawDescData []byte
)

func file_apipb_application_proto_rawDescGZIP() []byte {
	file_apipb_application_proto_rawDescOnce.Do(func() {
		file_apipb_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apipb_application_proto_rawDesc), len(file_apipb_application_proto_rawDesc)))
	})
	return file_apipb_application_proto_rawDescData
}

var file_apipb_application_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_apipb_application_proto_goTypes = []any{
	(*CancelOperationCommand)(nil),          // 0: anytty.api.v1.CancelOperationCommand
	(*ReleaseResourceCommand)(nil),          // 1: anytty.api.v1.ReleaseResourceCommand
	(*CommandEnvelope)(nil),                 // 2: anytty.api.v1.CommandEnvelope
	(*AcknowledgeResult)(nil),               // 3: anytty.api.v1.AcknowledgeResult
	(*ResultEnvelope)(nil),                  // 4: anytty.api.v1.ResultEnvelope
	(*OperationCancelledEvent)(nil),         // 5: anytty.api.v1.OperationCancelledEvent
	(*ResourceReleasedEvent)(nil),           // 6: anytty.api.v1.ResourceReleasedEvent
	(*EventEnvelope)(nil),                   // 7: anytty.api.v1.EventEnvelope
	(*OperationStamp)(nil),                  // 8: anytty.api.v1.OperationStamp
	(*ResourceHandle)(nil),                  // 9: anytty.api.v1.ResourceHandle
	(*RequestContext)(nil),                  // 10: anytty.api.v1.RequestContext
	(*TerminalDefaultsCommand)(nil),         // 11: anytty.api.v1.TerminalDefaultsCommand
	(*TerminalCreateCommand)(nil),           // 12: anytty.api.v1.TerminalCreateCommand
	(*TerminalListCommand)(nil),             // 13: anytty.api.v1.TerminalListCommand
	(*TerminalGetCommand)(nil),              // 14: anytty.api.v1.TerminalGetCommand
	(*TerminalRestartCommand)(nil),          // 15: anytty.api.v1.TerminalRestartCommand
	(*TerminalKillCommand)(nil),             // 16: anytty.api.v1.TerminalKillCommand
	(*TerminalRemoveCommand)(nil),           // 17: anytty.api.v1.TerminalRemoveCommand
	(*TerminalSetMetadataCommand)(nil),      // 18: anytty.api.v1.TerminalSetMetadataCommand
	(*TerminalSetTagsCommand)(nil),          // 19: anytty.api.v1.TerminalSetTagsCommand
	(*TerminalAttachCommand)(nil),           // 20: anytty.api.v1.TerminalAttachCommand
	(*TerminalDetachCommand)(nil),           // 21: anytty.api.v1.TerminalDetachCommand
	(*TerminalInputCommand)(nil),            // 22: anytty.api.v1.TerminalInputCommand
	(*TerminalResizeCommand)(nil),           // 23: anytty.api.v1.TerminalResizeCommand
	(*TerminalResizeLockCommand)(nil),       // 24: anytty.api.v1.TerminalResizeLockCommand
	(*PathListDirectoriesCommand)(nil),      // 25: anytty.api.v1.PathListDirectoriesCommand
	(*HistoryWindowCommand)(nil),            // 26: anytty.api.v1.HistoryWindowCommand
	(*HistoryCopyCommand)(nil),              // 27: anytty.api.v1.HistoryCopyCommand
	(*HistoryReleaseCommand)(nil),           // 28: anytty.api.v1.HistoryReleaseCommand
	(*HistoryBacklogStatusCommand)(nil),     // 29: anytty.api.v1.HistoryBacklogStatusCommand
	(*LiveScreenNextCommand)(nil),           // 30: anytty.api.v1.LiveScreenNextCommand
	(*HistorySearchCommand)(nil),            // 31: anytty.api.v1.HistorySearchCommand
	(*EventSubscribeCommand)(nil),           // 32: anytty.api.v1.EventSubscribeCommand
	(*FileListCommand)(nil),                 // 33: anytty.api.v1.FileListCommand
	(*FileStatCommand)(nil),                 // 34: anytty.api.v1.FileStatCommand
	(*FilePreviewCommand)(nil),              // 35: anytty.api.v1.FilePreviewCommand
	(*FileMkdirCommand)(nil),                // 36: anytty.api.v1.FileMkdirCommand
	(*FileRenameCommand)(nil),               // 37: anytty.api.v1.FileRenameCommand
	(*FileDeleteCommand)(nil),               // 38: anytty.api.v1.FileDeleteCommand
	(*FileCopyCommand)(nil),                 // 39: anytty.api.v1.FileCopyCommand
	(*FileMoveCommand)(nil),                 // 40: anytty.api.v1.FileMoveCommand
	(*FileDownloadOpenCommand)(nil),         // 41: anytty.api.v1.FileDownloadOpenCommand
	(*FileUploadOpenCommand)(nil),           // 42: anytty.api.v1.FileUploadOpenCommand
	(*FileTransferCancelCommand)(nil),       // 43: anytty.api.v1.FileTransferCancelCommand
	(*StorageGetCommand)(nil),               // 44: anytty.api.v1.StorageGetCommand
	(*StoragePutCommand)(nil),               // 45: anytty.api.v1.StoragePutCommand
	(*StorageDeleteCommand)(nil),            // 46: anytty.api.v1.StorageDeleteCommand
	(*StorageListCommand)(nil),              // 47: anytty.api.v1.StorageListCommand
	(*ClientAccessIdentityCommand)(nil),     // 48: anytty.api.v1.ClientAccessIdentityCommand
	(*ClientAccessListCommand)(nil),         // 49: anytty.api.v1.ClientAccessListCommand
	(*ClientAccessTicketCreateCommand)(nil), // 50: anytty.api.v1.ClientAccessTicketCreateCommand
	(*ClientAccessRevokeCommand)(nil),       // 51: anytty.api.v1.ClientAccessRevokeCommand
	(*RemoteStatusCommand)(nil),             // 52: anytty.api.v1.RemoteStatusCommand
	(*RemotePairStartCommand)(nil),          // 53: anytty.api.v1.RemotePairStartCommand
	(*RemoteLocalEnableCommand)(nil),        // 54: anytty.api.v1.RemoteLocalEnableCommand
	(*RemoteLocalStatusCommand)(nil),        // 55: anytty.api.v1.RemoteLocalStatusCommand
	(*RemoteLocalDisableCommand)(nil),       // 56: anytty.api.v1.RemoteLocalDisableCommand
	(*RemoteCloudEdgesCommand)(nil),         // 57: anytty.api.v1.RemoteCloudEdgesCommand
	(*RemoteCloudPreferEdgeCommand)(nil),    // 58: anytty.api.v1.RemoteCloudPreferEdgeCommand
	(*RemoteCloudReselectEdgeCommand)(nil),  // 59: anytty.api.v1.RemoteCloudReselectEdgeCommand
	(*EndpointSessionStamp)(nil),            // 60: anytty.api.v1.EndpointSessionStamp
	(*ApiError)(nil),                        // 61: anytty.api.v1.ApiError
	(*TerminalDefaultsResult)(nil),          // 62: anytty.api.v1.TerminalDefaultsResult
	(*TerminalCreateResult)(nil),            // 63: anytty.api.v1.TerminalCreateResult
	(*TerminalListResult)(nil),              // 64: anytty.api.v1.TerminalListResult
	(*TerminalGetResult)(nil),               // 65: anytty.api.v1.TerminalGetResult
	(*TerminalAttachResult)(nil),            // 66: anytty.api.v1.TerminalAttachResult
	(*TerminalResizeResult)(nil),            // 67: anytty.api.v1.TerminalResizeResult
	(*PathListDirectoriesResult)(nil),       // 68: anytty.api.v1.PathListDirectoriesResult
	(*HistoryWindowResult)(nil),             // 69: anytty.api.v1.HistoryWindowResult
	(*HistoryCopyResult)(nil),               // 70: anytty.api.v1.HistoryCopyResult
	(*HistoryBacklogStatusResult)(nil),      // 71: anytty.api.v1.HistoryBacklogStatusResult
	(*NativeScreenResult)(nil),              // 72: anytty.api.v1.NativeScreenResult
	(*HistorySearchResult)(nil),             // 73: anytty.api.v1.HistorySearchResult
	(*EventSubscriptionResult)(nil),         // 74: anytty.api.v1.EventSubscriptionResult
	(*FileListResult)(nil),                  // 75: anytty.api.v1.FileListResult
	(*FileStatResult)(nil),                  // 76: anytty.api.v1.FileStatResult
	(*FilePreviewResult)(nil),               // 77: anytty.api.v1.FilePreviewResult
	(*FileOperationResult)(nil),             // 78: anytty.api.v1.FileOperationResult
	(*FileBatchResult)(nil),                 // 79: anytty.api.v1.FileBatchResult
	(*FileTransferOpenResult)(nil),          // 80: anytty.api.v1.FileTransferOpenResult
	(*FileTransferCancelResult)(nil),        // 81: anytty.api.v1.FileTransferCancelResult
	(*StorageGetResult)(nil),                // 82: anytty.api.v1.StorageGetResult
	(*StoragePutResult)(nil),                // 83: anytty.api.v1.StoragePutResult
	(*StorageDeleteResult)(nil),             // 84: anytty.api.v1.StorageDeleteResult
	(*StorageListResult)(nil),               // 85: anytty.api.v1.StorageListResult
	(*ClientAccessIdentityResult)(nil),      // 86: anytty.api.v1.ClientAccessIdentityResult
	(*ClientAccessListResult)(nil),          // 87: anytty.api.v1.ClientAccessListResult
	(*ClientAccessTicketCreateResult)(nil),  // 88: anytty.api.v1.ClientAccessTicketCreateResult
	(*ClientAccessRevokeResult)(nil),        // 89: anytty.api.v1.ClientAccessRevokeResult
	(*RemoteStatusResult)(nil),              // 90: anytty.api.v1.RemoteStatusResult
	(*RemotePairStartResult)(nil),           // 91: anytty.api.v1.RemotePairStartResult
	(*RemoteLocalStatusResult)(nil),         // 92: anytty.api.v1.RemoteLocalStatusResult
	(*RemoteCloudEdgesResult)(nil),          // 93: anytty.api.v1.RemoteCloudEdgesResult
	(*ApiVersion)(nil),                      // 94: anytty.api.v1.ApiVersion
	(*TerminalLifecycleEvent)(nil),          // 95: anytty.api.v1.TerminalLifecycleEvent
	(*StorageChangedEvent)(nil),             // 96: anytty.api.v1.StorageChangedEvent
	(*FileTransferCompletedEvent)(nil),      // 97: anytty.api.v1.FileTransferCompletedEvent
}
var file_apipb_application_proto_depIdxs = []int32{
	8,  // 0: anytty.api.v1.CancelOperationCommand.operation:type_name -> anytty.api.v1.OperationStamp
	9,  // 1: anytty.api.v1.ReleaseResourceCommand.resource:type_name -> anytty.api.v1.ResourceHandle
	10, // 2: anytty.api.v1.CommandEnvelope.context:type_name -> anytty.api.v1.RequestContext
	0,  // 3: anytty.api.v1.CommandEnvelope.cancel_operation:type_name -> anytty.api.v1.CancelOperationCommand
	1,  // 4: anytty.api.v1.CommandEnvelope.release_resource:type_name -> anytty.api.v1.ReleaseResourceCommand
	11, // 5: anytty.api.v1.CommandEnvelope.terminal_defaults:type_name -> anytty.api.v1.TerminalDefaultsCommand
	12, // 6: anytty.api.v1.CommandEnvelope.terminal_create:type_name -> anytty.api.v1.TerminalCreateCommand
	13, // 7: anytty.api.v1.CommandEnvelope.terminal_list:type_name -> anytty.api.v1.TerminalListCommand
	14, // 8: anytty.api.v1.CommandEnvelope.terminal_get:type_name -> anytty.api.v1.TerminalGetCommand
	15, // 9: anytty.api.v1.CommandEnvelope.terminal_restart:type_name -> anytty.api.v1.TerminalRestartCommand
	16, // 10: anytty.api.v1.CommandEnvelope.terminal_kill:type_name -> anytty.api.v1.TerminalKillCommand
	17, // 11: anytty.api.v1.CommandEnvelope.terminal_remove:type_name -> anytty.api.v1.TerminalRemoveCommand
	18, // 12: anytty.api.v1.CommandEnvelope.terminal_set_metadata:type_name -> anytty.api.v1.TerminalSetMetadataCommand
	19, // 13: anytty.api.v1.CommandEnvelope.terminal_set_tags:type_name -> anytty.api.v1.TerminalSetTagsCommand
	20, // 14: anytty.api.v1.CommandEnvelope.terminal_attach:type_name -> anytty.api.v1.TerminalAttachCommand
	21, // 15: anytty.api.v1.CommandEnvelope.terminal_detach:type_name -> anytty.api.v1.TerminalDetachCommand
	22, // 16: anytty.api.v1.CommandEnvelope.terminal_input:type_name -> anytty.api.v1.TerminalInputCommand
	23, // 17: anytty.api.v1.CommandEnvelope.terminal_resize:type_name -> anytty.api.v1.TerminalResizeCommand
	24, // 18: anytty.api.v1.CommandEnvelope.terminal_resize_lock:type_name -> anytty.api.v1.TerminalResizeLockCommand
	25, // 19: anytty.api.v1.CommandEnvelope.path_list_directories:type_name -> anytty.api.v1.PathListDirectoriesCommand
	26, // 20: anytty.api.v1.CommandEnvelope.history_window:type_name -> anytty.api.v1.HistoryWindowCommand
	27, // 21: anytty.api.v1.CommandEnvelope.history_copy:type_name -> anytty.api.v1.HistoryCopyCommand
	28, // 22: anytty.api.v1.CommandEnvelope.history_release:type_name -> anytty.api.v1.HistoryReleaseCommand
	29, // 23: anytty.api.v1.CommandEnvelope.history_backlog_status:type_name -> anytty.api.v1.HistoryBacklogStatusCommand
	30, // 24: anytty.api.v1.CommandEnvelope.live_screen_next:type_name -> anytty.api.v1.LiveScreenNextCommand
	31, // 25: anytty.api.v1.CommandEnvelope.history_search:type_name -> anytty.api.v1.HistorySearchCommand
	32, // 26: anytty.api.v1.CommandEnvelope.event_subscribe:type_name -> anytty.api.v1.EventSubscribeCommand
	33, // 27: anytty.api.v1.CommandEnvelope.file_list:type_name -> anytty.api.v1.FileListCommand
	34, // 28: anytty.api.v1.CommandEnvelope.file_stat:type_name -> anytty.api.v1.FileStatCommand
	35, // 29: anytty.api.v1.CommandEnvelope.file_preview:type_name -> anytty.api.v1.FilePreviewCommand
	36, // 30: anytty.api.v1.CommandEnvelope.file_mkdir:type_name -> anytty.api.v1.FileMkdirCommand
	37, // 31: anytty.api.v1.CommandEnvelope.file_rename:type_name -> anytty.api.v1.FileRenameCommand
	38, // 32: anytty.api.v1.CommandEnvelope.file_delete:type_name -> anytty.api.v1.FileDeleteCommand
	39, // 33: anytty.api.v1.CommandEnvelope.file_copy:type_name -> anytty.api.v1.FileCopyCommand
	40, // 34: anytty.api.v1.CommandEnvelope.file_move:type_name -> anytty.api.v1.FileMoveCommand
	41, // 35: anytty.api.v1.CommandEnvelope.file_download_open:type_name -> anytty.api.v1.FileDownloadOpenCommand
	42, // 36: anytty.api.v1.CommandEnvelope.file_upload_open:type_name -> anytty.api.v1.FileUploadOpenCommand
	43, // 37: anytty.api.v1.CommandEnvelope.file_transfer_cancel:type_name -> anytty.api.v1.FileTransferCancelCommand
	44, // 38: anytty.api.v1.CommandEnvelope.storage_get:type_name -> anytty.api.v1.StorageGetCommand
	45, // 39: anytty.api.v1.CommandEnvelope.storage_put:type_name -> anytty.api.v1.StoragePutCommand
	46, // 40: anytty.api.v1.CommandEnvelope.storage_delete:type_name -> anytty.api.v1.StorageDeleteCommand
	47, // 41: anytty.api.v1.CommandEnvelope.storage_list:type_name -> anytty.api.v1.StorageListCommand
	48, // 42: anytty.api.v1.CommandEnvelope.client_access_identity:type_name -> anytty.api.v1.ClientAccessIdentityCommand
	49, // 43: anytty.api.v1.CommandEnvelope.client_access_list:type_name -> anytty.api.v1.ClientAccessListCommand
	50, // 44: anytty.api.v1.CommandEnvelope.client_access_ticket_create:type_name -> anytty.api.v1.ClientAccessTicketCreateCommand
	51, // 45: anytty.api.v1.CommandEnvelope.client_access_revoke:type_name -> anytty.api.v1.ClientAccessRevokeCommand
	52, // 46: anytty.api.v1.CommandEnvelope.remote_status:type_name -> anytty.api.v1.RemoteStatusCommand
	53, // 47: anytty.api.v1.CommandEnvelope.remote_pair_start:type_name -> anytty.api.v1.RemotePairStartCommand
	54, // 48: anytty.api.v1.CommandEnvelope.remote_local_enable:type_name -> anytty.api.v1.RemoteLocalEnableCommand
	55, // 49: anytty.api.v1.CommandEnvelope.remote_local_status:type_name -> anytty.api.v1.RemoteLocalStatusCommand
	56, // 50: anytty.api.v1.CommandEnvelope.remote_local_disable:type_name -> anytty.api.v1.RemoteLocalDisableCommand
	57, // 51: anytty.api.v1.CommandEnvelope.remote_cloud_edges:type_name -> anytty.api.v1.RemoteCloudEdgesCommand
	58, // 52: anytty.api.v1.CommandEnvelope.remote_cloud_prefer_edge:type_name -> anytty.api.v1.RemoteCloudPreferEdgeCommand
	59, // 53: anytty.api.v1.CommandEnvelope.remote_cloud_reselect_edge:type_name -> anytty.api.v1.RemoteCloudReselectEdgeCommand
	60, // 54: anytty.api.v1.ResultEnvelope.origin_session:type_name -> anytty.api.v1.EndpointSessionStamp
	3,  // 55: anytty.api.v1.ResultEnvelope.acknowledge:type_name -> anytty.api.v1.AcknowledgeResult
	61, // 56: anytty.api.v1.ResultEnvelope.error:type_name -> anytty.api.v1.ApiError
	62, // 57: anytty.api.v1.ResultEnvelope.terminal_defaults:type_name -> anytty.api.v1.TerminalDefaultsResult
	63, // 58: anytty.api.v1.ResultEnvelope.terminal_create:type_name -> anytty.api.v1.TerminalCreateResult
	64, // 59: anytty.api.v1.ResultEnvelope.terminal_list:type_name -> anytty.api.v1.TerminalListResult
	65, // 60: anytty.api.v1.ResultEnvelope.terminal_get:type_name -> anytty.api.v1.TerminalGetResult
	66, // 61: anytty.api.v1.ResultEnvelope.terminal_attach:type_name -> anytty.api.v1.TerminalAttachResult
	67, // 62: anytty.api.v1.ResultEnvelope.terminal_resize:type_name -> anytty.api.v1.TerminalResizeResult
	68, // 63: anytty.api.v1.ResultEnvelope.path_list_directories:type_name -> anytty.api.v1.PathListDirectoriesResult
	69, // 64: anytty.api.v1.ResultEnvelope.history_window:type_name -> anytty.api.v1.HistoryWindowResult
	70, // 65: anytty.api.v1.ResultEnvelope.history_copy:type_name -> anytty.api.v1.HistoryCopyResult
	71, // 66: anytty.api.v1.ResultEnvelope.history_backlog_status:type_name -> anytty.api.v1.HistoryBacklogStatusResult
	72, // 67: anytty.api.v1.ResultEnvelope.live_screen:type_name -> anytty.api.v1.NativeScreenResult
	73, // 68: anytty.api.v1.ResultEnvelope.history_search:type_name -> anytty.api.v1.HistorySearchResult
	74, // 69: anytty.api.v1.ResultEnvelope.event_subscription:type_name -> anytty.api.v1.EventSubscriptionResult
	75, // 70: anytty.api.v1.ResultEnvelope.file_list:type_name -> anytty.api.v1.FileListResult
	76, // 71: anytty.api.v1.ResultEnvelope.file_stat:type_name -> anytty.api.v1.FileStatResult
	77, // 72: anytty.api.v1.ResultEnvelope.file_preview:type_name -> anytty.api.v1.FilePreviewResult
	78, // 73: anytty.api.v1.ResultEnvelope.file_operation:type_name -> anytty.api.v1.FileOperationResult
	79, // 74: anytty.api.v1.ResultEnvelope.file_batch:type_name -> anytty.api.v1.FileBatchResult
	80, // 75: anytty.api.v1.ResultEnvelope.file_transfer_open:type_name -> anytty.api.v1.FileTransferOpenResult
	81, // 76: anytty.api.v1.ResultEnvelope.file_transfer_cancel:type_name -> anytty.api.v1.FileTransferCancelResult
	82, // 77: anytty.api.v1.ResultEnvelope.storage_get:type_name -> anytty.api.v1.StorageGetResult
	83, // 78: anytty.api.v1.ResultEnvelope.storage_put:type_name -> anytty.api.v1.StoragePutResult
	84, // 79: anytty.api.v1.ResultEnvelope.storage_delete:type_name -> anytty.api.v1.StorageDeleteResult
	85, // 80: anytty.api.v1.ResultEnvelope.storage_list:type_name -> anytty.api.v1.StorageListResult
	86, // 81: anytty.api.v1.ResultEnvelope.client_access_identity:type_name -> anytty.api.v1.ClientAccessIdentityResult
	87, // 82: anytty.api.v1.ResultEnvelope.client_access_list:type_name -> anytty.api.v1.ClientAccessListResult
	88, // 83: anytty.api.v1.ResultEnvelope.client_access_ticket_create:type_name -> anytty.api.v1.ClientAccessTicketCreateResult
	89, // 84: anytty.api.v1.ResultEnvelope.client_access_revoke:type_name -> anytty.api.v1.ClientAccessRevokeResult
	90, // 85: anytty.api.v1.ResultEnvelope.remote_status:type_name -> anytty.api.v1.RemoteStatusResult
	91, // 86: anytty.api.v1.ResultEnvelope.remote_pair_start:type_name -> anytty.api.v1.RemotePairStartResult
	92, // 87: anytty.api.v1.ResultEnvelope.remote_local_status:type_name -> anytty.api.v1.RemoteLocalStatusResult
	93, // 88: anytty.api.v1.ResultEnvelope.remote_cloud_edges:type_name -> anytty.api.v1.RemoteCloudEdgesResult
	8,  // 89: anytty.api.v1.OperationCancelledEvent.operation:type_name -> anytty.api.v1.OperationStamp
	9,  // 90: anytty.api.v1.ResourceReleasedEvent.resource:type_name -> anytty.api.v1.ResourceHandle
	94, // 91: anytty.api.v1.EventEnvelope.api_version:type_name -> anytty.api.v1.ApiVersion
	60, // 92: anytty.api.v1.EventEnvelope.origin_session:type_name -> anytty.api.v1.EndpointSessionStamp
	9,  // 93: anytty.api.v1.EventEnvelope.subscription:type_name -> anytty.api.v1.ResourceHandle
	5,  // 94: anytty.api.v1.EventEnvelope.operation_cancelled:type_name -> anytty.api.v1.OperationCancelledEvent
	6,  // 95: anytty.api.v1.EventEnvelope.resource_released:type_name -> anytty.api.v1.ResourceReleasedEvent
	95, // 96: anytty.api.v1.EventEnvelope.terminal_lifecycle:type_name -> anytty.api.v1.TerminalLifecycleEvent
	96, // 97: anytty.api.v1.EventEnvelope.storage_changed:type_name -> anytty.api.v1.StorageChangedEvent
	97, // 98: anytty.api.v1.EventEnvelope.file_transfer_completed:type_name -> anytty.api.v1.FileTransferCompletedEvent
	99, // [99:99] is the sub-list for method output_type
	99, // [99:99] is the sub-list for method input_type
	99, // [99:99] is the sub-list for extension type_name
	99, // [99:99] is the sub-list for extension extendee
	0,  // [0:99] is the sub-list for field type_name
}

func init() { file_apipb_application_proto_init() }
func file_apipb_application_proto_init() {
	if File_apipb_application_proto != nil {
		return
	}
	file_apipb_common_proto_init()
	file_apipb_access_remote_proto_init()
	file_apipb_events_proto_init()
	file_apipb_file_proto_init()
	file_apipb_history_proto_init()
	file_apipb_storage_proto_init()
	file_apipb_terminal_proto_init()
	file_apipb_application_proto_msgTypes[2].OneofWrappers = []any{
		(*CommandEnvelope_CancelOperation)(nil),
		(*CommandEnvelope_ReleaseResource)(nil),
		(*CommandEnvelope_TerminalDefaults)(nil),
		(*CommandEnvelope_TerminalCreate)(nil),
		(*CommandEnvelope_TerminalList)(nil),
		(*CommandEnvelope_TerminalGet)(nil),
		(*CommandEnvelope_TerminalRestart)(nil),
		(*CommandEnvelope_TerminalKill)(nil),
		(*CommandEnvelope_TerminalRemove)(nil),
		(*CommandEnvelope_TerminalSetMetadata)(nil),
		(*CommandEnvelope_TerminalSetTags)(nil),
		(*CommandEnvelope_TerminalAttach)(nil),
		(*CommandEnvelope_TerminalDetach)(nil),
		(*CommandEnvelope_TerminalInput)(nil),
		(*CommandEnvelope_TerminalResize)(nil),
		(*CommandEnvelope_TerminalResizeLock)(nil),
		(*CommandEnvelope_PathListDirectories)(nil),
		(*CommandEnvelope_HistoryWindow)(nil),
		(*CommandEnvelope_HistoryCopy)(nil),
		(*CommandEnvelope_HistoryRelease)(nil),
		(*CommandEnvelope_HistoryBacklogStatus)(nil),
		(*CommandEnvelope_LiveScreenNext)(nil),
		(*CommandEnvelope_HistorySearch)(nil),
		(*CommandEnvelope_EventSubscribe)(nil),
		(*CommandEnvelope_FileList)(nil),
		(*CommandEnvelope_FileStat)(nil),
		(*CommandEnvelope_FilePreview)(nil),
		(*CommandEnvelope_FileMkdir)(nil),
		(*CommandEnvelope_FileRename)(nil),
		(*CommandEnvelope_FileDelete)(nil),
		(*CommandEnvelope_FileCopy)(nil),
		(*CommandEnvelope_FileMove)(nil),
		(*CommandEnvelope_FileDownloadOpen)(nil),
		(*CommandEnvelope_FileUploadOpen)(nil),
		(*CommandEnvelope_FileTransferCancel)(nil),
		(*CommandEnvelope_StorageGet)(nil),
		(*CommandEnvelope_StoragePut)(nil),
		(*CommandEnvelope_StorageDelete)(nil),
		(*CommandEnvelope_StorageList)(nil),
		(*CommandEnvelope_ClientAccessIdentity)(nil),
		(*CommandEnvelope_ClientAccessList)(nil),
		(*CommandEnvelope_ClientAccessTicketCreate)(nil),
		(*CommandEnvelope_ClientAccessRevoke)(nil),
		(*CommandEnvelope_RemoteStatus)(nil),
		(*CommandEnvelope_RemotePairStart)(nil),
		(*CommandEnvelope_RemoteLocalEnable)(nil),
		(*CommandEnvelope_RemoteLocalStatus)(nil),
		(*CommandEnvelope_RemoteLocalDisable)(nil),
		(*CommandEnvelope_RemoteCloudEdges)(nil),
		(*CommandEnvelope_RemoteCloudPreferEdge)(nil),
		(*CommandEnvelope_RemoteCloudReselectEdge)(nil),
	}
	file_apipb_application_proto_msgTypes[4].OneofWrappers = []any{
		(*ResultEnvelope_Acknowledge)(nil),
		(*ResultEnvelope_Error)(nil),
		(*ResultEnvelope_TerminalDefaults)(nil),
		(*ResultEnvelope_TerminalCreate)(nil),
		(*ResultEnvelope_TerminalList)(nil),
		(*ResultEnvelope_TerminalGet)(nil),
		(*ResultEnvelope_TerminalAttach)(nil),
		(*ResultEnvelope_TerminalResize)(nil),
		(*ResultEnvelope_PathListDirectories)(nil),
		(*ResultEnvelope_HistoryWindow)(nil),
		(*ResultEnvelope_HistoryCopy)(nil),
		(*ResultEnvelope_HistoryBacklogStatus)(nil),
		(*ResultEnvelope_LiveScreen)(nil),
		(*ResultEnvelope_HistorySearch)(nil),
		(*ResultEnvelope_EventSubscription)(nil),
		(*ResultEnvelope_FileList)(nil),
		(*ResultEnvelope_FileStat)(nil),
		(*ResultEnvelope_FilePreview)(nil),
		(*ResultEnvelope_FileOperation)(nil),
		(*ResultEnvelope_FileBatch)(nil),
		(*ResultEnvelope_FileTransferOpen)(nil),
		(*ResultEnvelope_FileTransferCancel)(nil),
		(*ResultEnvelope_StorageGet)(nil),
		(*ResultEnvelope_StoragePut)(nil),
		(*ResultEnvelope_StorageDelete)(nil),
		(*ResultEnvelope_StorageList)(nil),
		(*ResultEnvelope_ClientAccessIdentity)(nil),
		(*ResultEnvelope_ClientAccessList)(nil),
		(*ResultEnvelope_ClientAccessTicketCreate)(nil),
		(*ResultEnvelope_ClientAccessRevoke)(nil),
		(*ResultEnvelope_RemoteStatus)(nil),
		(*ResultEnvelope_RemotePairStart)(nil),
		(*ResultEnvelope_RemoteLocalStatus)(nil),
		(*ResultEnvelope_RemoteCloudEdges)(nil),
	}
	file_apipb_application_proto_msgTypes[7].OneofWrappers = []any{
		(*EventEnvelope_OperationCancelled)(nil),
		(*EventEnvelope_ResourceReleased)(nil),
		(*EventEnvelope_TerminalLifecycle)(nil),
		(*EventEnvelope_StorageChanged)(nil),
		(*EventEnvelope_FileTransferCompleted)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apipb_application_proto_rawDesc), len(file_apipb_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_apipb_application_proto_goTypes,
		DependencyIndexes: file_apipb_application_proto_depIdxs,
		MessageInfos:      file_apipb_application_proto_msgTypes,
	}.Build()
	File_apipb_application_proto = out.File
	file_apipb_application_proto_goTypes = nil
	file_apipb_application_proto_depIdxs = nil
}
