package input

type ActionKind string

const (
	ActionFocusPane                   ActionKind = "focus-pane"
	ActionFocusPaneLeft               ActionKind = "focus-pane-left"
	ActionFocusPaneRight              ActionKind = "focus-pane-right"
	ActionFocusPaneUp                 ActionKind = "focus-pane-up"
	ActionFocusPaneDown               ActionKind = "focus-pane-down"
	ActionSplitPane                   ActionKind = "split-pane"
	ActionSplitPaneHorizontal         ActionKind = "split-pane-horizontal"
	ActionClosePane                   ActionKind = "close-pane"
	ActionClosePaneKill               ActionKind = "close-pane-kill"
	ActionDetachPane                  ActionKind = "detach-pane"
	ActionReconnectPane               ActionKind = "reconnect-pane"
	ActionRestartTerminal             ActionKind = "restart-terminal"
	ActionSwapPaneLeft                ActionKind = "swap-pane-left"
	ActionEnterPaneMode               ActionKind = "enter-pane-mode"
	ActionEnterResizeMode             ActionKind = "enter-resize-mode"
	ActionEnterTabMode                ActionKind = "enter-tab-mode"
	ActionEnterWorkspaceMode          ActionKind = "enter-workspace-mode"
	ActionEnterFloatingMode           ActionKind = "enter-floating-mode"
	ActionEnterDisplayMode            ActionKind = "enter-display-mode"
	ActionEnterGlobalMode             ActionKind = "enter-global-mode"
	ActionOpenPicker                  ActionKind = "open-picker"
	ActionOpenWorkspacePicker         ActionKind = "open-workspace-picker"
	ActionOpenFloatingOverview        ActionKind = "open-floating-overview"
	ActionOpenHelp                    ActionKind = "open-help"
	ActionOpenTerminalManager         ActionKind = "open-terminal-manager"
	ActionOpenPrompt                  ActionKind = "open-prompt"
	ActionSubmitPrompt                ActionKind = "submit-prompt"
	ActionCancelMode                  ActionKind = "cancel-mode"
	ActionPickerUp                    ActionKind = "picker-up"
	ActionPickerDown                  ActionKind = "picker-down"
	ActionPickerAttachSplit           ActionKind = "picker-attach-split"
	ActionEditTerminal                ActionKind = "edit-terminal"
	ActionAttachTab                   ActionKind = "attach-tab"
	ActionAttachFloating              ActionKind = "attach-floating"
	ActionScrollUp                    ActionKind = "scroll-up"
	ActionScrollDown                  ActionKind = "scroll-down"
	ActionCopyModeCursorLeft          ActionKind = "copy-mode-cursor-left"
	ActionCopyModeCursorRight         ActionKind = "copy-mode-cursor-right"
	ActionCopyModeCursorUp            ActionKind = "copy-mode-cursor-up"
	ActionCopyModeCursorDown          ActionKind = "copy-mode-cursor-down"
	ActionCopyModePageUp              ActionKind = "copy-mode-page-up"
	ActionCopyModePageDown            ActionKind = "copy-mode-page-down"
	ActionCopyModeHalfPageUp          ActionKind = "copy-mode-half-page-up"
	ActionCopyModeHalfPageDown        ActionKind = "copy-mode-half-page-down"
	ActionCopyModeStartOfLine         ActionKind = "copy-mode-start-of-line"
	ActionCopyModeEndOfLine           ActionKind = "copy-mode-end-of-line"
	ActionCopyModeTop                 ActionKind = "copy-mode-top"
	ActionCopyModeBottom              ActionKind = "copy-mode-bottom"
	ActionCopyModeBeginSelection      ActionKind = "copy-mode-begin-selection"
	ActionCopyModeCopySelection       ActionKind = "copy-mode-copy-selection"
	ActionCopyModeCopySelectionExit   ActionKind = "copy-mode-copy-selection-exit"
	ActionPasteBuffer                 ActionKind = "paste-buffer"
	ActionPasteClipboard              ActionKind = "paste-clipboard"
	ActionOpenClipboardHistory        ActionKind = "open-clipboard-history"
	ActionZoomPane                    ActionKind = "zoom-pane"
	ActionQuit                        ActionKind = "quit"
	ActionCreateWorkspace             ActionKind = "create-workspace"
	ActionSwitchWorkspace             ActionKind = "switch-workspace"
	ActionDeleteWorkspace             ActionKind = "delete-workspace"
	ActionRenameWorkspace             ActionKind = "rename-workspace"
	ActionPrevWorkspace               ActionKind = "prev-workspace"
	ActionNextWorkspace               ActionKind = "next-workspace"
	ActionCreateTab                   ActionKind = "create-tab"
	ActionCloseTab                    ActionKind = "close-tab"
	ActionKillTab                     ActionKind = "kill-tab"
	ActionNextTab                     ActionKind = "next-tab"
	ActionPrevTab                     ActionKind = "prev-tab"
	ActionJumpTab                     ActionKind = "jump-tab"
	ActionRenameTab                   ActionKind = "rename-tab"
	ActionKillTerminal                ActionKind = "kill-terminal"
	ActionRemoveTerminal              ActionKind = "remove-terminal"
	ActionBecomeOwner                 ActionKind = "become-owner"
	ActionResizePaneLeft              ActionKind = "resize-pane-left"
	ActionResizePaneRight             ActionKind = "resize-pane-right"
	ActionResizePaneUp                ActionKind = "resize-pane-up"
	ActionResizePaneDown              ActionKind = "resize-pane-down"
	ActionCreateFloatingPane          ActionKind = "create-floating-pane"
	ActionMoveFloatingLeft            ActionKind = "move-floating-left"
	ActionMoveFloatingDown            ActionKind = "move-floating-down"
	ActionMoveFloatingUp              ActionKind = "move-floating-up"
	ActionMoveFloatingRight           ActionKind = "move-floating-right"
	ActionFocusPrevFloatingPane       ActionKind = "focus-prev-floating-pane"
	ActionFocusNextFloatingPane       ActionKind = "focus-next-floating-pane"
	ActionResizeFloatingLeft          ActionKind = "resize-floating-left"
	ActionResizeFloatingDown          ActionKind = "resize-floating-down"
	ActionResizeFloatingUp            ActionKind = "resize-floating-up"
	ActionResizeFloatingRight         ActionKind = "resize-floating-right"
	ActionCenterFloatingPane          ActionKind = "center-floating-pane"
	ActionToggleFloatingPaneCollapsed ActionKind = "toggle-floating-pane-collapsed"
	ActionToggleFloatingPaneAutoFit   ActionKind = "toggle-floating-pane-auto-fit"
	ActionShowAllFloatingPanes        ActionKind = "show-all-floating-panes"
	ActionFocusFloatingPaneByIndex    ActionKind = "focus-floating-pane-by-index"
	ActionToggleFloatingVisibility    ActionKind = "toggle-floating-visibility"
	ActionCloseFloatingPane           ActionKind = "close-floating-pane"
	ActionCollapseFloatingPane        ActionKind = "collapse-floating-pane"
	ActionExpandAllFloatingPanes      ActionKind = "expand-all-floating-panes"
	ActionCollapseAllFloatingPanes    ActionKind = "collapse-all-floating-panes"
	ActionSummonFloatingPane          ActionKind = "summon-floating-pane"
	ActionAutoFitFloatingPane         ActionKind = "auto-fit-floating-pane"
	ActionToggleFloatingAutoFit       ActionKind = "toggle-floating-auto-fit"
	ActionResizePaneLargeLeft         ActionKind = "resize-pane-large-left"
	ActionResizePaneLargeRight        ActionKind = "resize-pane-large-right"
	ActionResizePaneLargeUp           ActionKind = "resize-pane-large-up"
	ActionResizePaneLargeDown         ActionKind = "resize-pane-large-down"
	ActionBalancePanes                ActionKind = "balance-panes"
	ActionCycleLayout                 ActionKind = "cycle-layout"
)

type SemanticAction struct {
	Kind      ActionKind
	Workspace string
	TabID     string
	PaneID    string
	TargetID  string
	Text      string
}
