// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cloud/v1/agent_gateway.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentTicket     *SignedEnvelope        `protobuf:"bytes,1,opt,name=agent_ticket,json=agentTicket,proto3" json:"agent_ticket,omitempty"`
	DeviceProof     []byte                 `protobuf:"bytes,2,opt,name=device_proof,json=deviceProof,proto3" json:"device_proof,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentHello) Reset() {
	*x = AgentHello{}
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHello) ProtoMessage() {}

func (x *AgentHello) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHello.ProtoReflect.Descriptor instead.
func (*AgentHello) Descriptor() ([]byte, []int) {
	return file_cloud_v1_agent_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AgentHello) GetAgentTicket() *SignedEnvelope {
	if x != nil {
		return x.AgentTicket
	}
	return nil
}

func (x *AgentHello) GetDeviceProof() []byte {
	if x != nil {
		return x.DeviceProof
	}
	return nil
}

func (x *AgentHello) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

type AgentHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentHeartbeat) Reset() {
	*x = AgentHeartbeat{}
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHeartbeat) ProtoMessage() {}

func (x *AgentHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHeartbeat.ProtoReflect.Descriptor instead.
func (*AgentHeartbeat) Descriptor() ([]byte, []int) {
	return file_cloud_v1_agent_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AgentHeartbeat) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type AgentReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    uint64                 `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Heartbeat     *HeartbeatPolicy       `protobuf:"bytes,2,opt,name=heartbeat,proto3" json:"heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentReady) Reset() {
	*x = AgentReady{}
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentReady) ProtoMessage() {}

func (x *AgentReady) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentReady.ProtoReflect.Descriptor instead.
func (*AgentReady) Descriptor() ([]byte, []int) {
	return file_cloud_v1_agent_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *AgentReady) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *AgentReady) GetHeartbeat() *HeartbeatPolicy {
	if x != nil {
		return x.Heartbeat
	}
	return nil
}

type AgentEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	BootId          string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	StreamSeq       uint64                 `protobuf:"varint,6,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEvent_Hello
	//	*AgentEvent_Heartbeat
	Payload       isAgentEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_cloud_v1_agent_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *AgentEvent) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AgentEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentEvent) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *AgentEvent) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AgentEvent) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *AgentEvent) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *AgentEvent) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *AgentEvent) GetPayload() isAgentEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEvent) GetHello() *AgentHello {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentEvent) GetHeartbeat() *AgentHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isAgentEvent_Payload interface {
	isAgentEvent_Payload()
}

type AgentEvent_Hello struct {
	Hello *AgentHello `protobuf:"bytes,20,opt,name=hello,proto3,oneof"`
}

type AgentEvent_Heartbeat struct {
	Heartbeat *AgentHeartbeat `protobuf:"bytes,21,opt,name=heartbeat,proto3,oneof"`
}

func (*AgentEvent_Hello) isAgentEvent_Payload() {}

func (*AgentEvent_Heartbeat) isAgentEvent_Payload() {}

type EdgeCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	BootId          string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	StreamSeq       uint64                 `protobuf:"varint,6,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EdgeCommand_Ready
	Payload       isEdgeCommand_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeCommand) Reset() {
	*x = EdgeCommand{}
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeCommand) ProtoMessage() {}

func (x *EdgeCommand) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_agent_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeCommand.ProtoReflect.Descriptor instead.
func (*EdgeCommand) Descriptor() ([]byte, []int) {
	return file_cloud_v1_agent_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *EdgeCommand) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EdgeCommand) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EdgeCommand) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EdgeCommand) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *EdgeCommand) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *EdgeCommand) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *EdgeCommand) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *EdgeCommand) GetPayload() isEdgeCommand_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EdgeCommand) GetReady() *AgentReady {
	if x != nil {
		if x, ok := x.Payload.(*EdgeCommand_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

type isEdgeCommand_Payload interface {
	isEdgeCommand_Payload()
}

type EdgeCommand_Ready struct {
	Ready *AgentReady `protobuf:"bytes,20,opt,name=ready,proto3,oneof"`
}

func (*EdgeCommand_Ready) isEdgeCommand_Payload() {}

var File_cloud_v1_agent_gateway_proto protoreflect.FileDescriptor

const file_cloud_v1_agent_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1ccloud/v1/agent_gateway.proto\x12\x0fmuxvia.cloud.v1\x1a\x15cloud/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9e\x01\n" +
	"\n" +
	"AgentHello\x12B\n" +
	"\fagent_ticket\x18\x01 \x01(\v2\x1f.muxvia.cloud.v1.SignedEnvelopeR\vagentTicket\x12!\n" +
	"\fdevice_proof\x18\x02 \x01(\fR\vdeviceProof\x12)\n" +
	"\x10software_version\x18\x03 \x01(\tR\x0fsoftwareVersion\"0\n" +
	"\x0eAgentHeartbeat\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\"l\n" +
	"\n" +
	"AgentReady\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12>\n" +
	"\theartbeat\x18\x02 \x01(\v2 .muxvia.cloud.v1.HeartbeatPolicyR\theartbeat\"\x86\x03\n" +
	"\n" +
	"AgentEvent\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x06 \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x123\n" +
	"\x05hello\x18\x14 \x01(\v2\x1b.muxvia.cloud.v1.AgentHelloH\x00R\x05hello\x12?\n" +
	"\theartbeat\x18\x15 \x01(\v2\x1f.muxvia.cloud.v1.AgentHeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\xc6\x02\n" +
	"\vEdgeCommand\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x06 \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x123\n" +
	"\x05ready\x18\x14 \x01(\v2\x1b.muxvia.cloud.v1.AgentReadyH\x00R\x05readyB\t\n" +
	"\apayload2X\n" +
	"\fAgentGateway\x12H\n" +
	"\aConnect\x12\x1b.muxvia.cloud.v1.AgentEvent\x1a\x1c.muxvia.cloud.v1.EdgeCommand(\x010\x01B1Z/github.com/muxvia/muxvia/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_agent_gateway_proto_rawDescOnce sync.Once
	file_cloud_v1_agent_gateway_proto_rawDescData []byte
)

func file_cloud_v1_agent_gateway_proto_rawDescGZIP() []byte {
	file_cloud_v1_agent_gateway_proto_rawDescOnce.Do(func() {
		file_cloud_v1_agent_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_agent_gateway_proto_rawDesc), len(file_cloud_v1_agent_gateway_proto_rawDesc)))
	})
	return file_cloud_v1_agent_gateway_proto_rawDescData
}

var file_cloud_v1_agent_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cloud_v1_agent_gateway_proto_goTypes = []any{
	(*AgentHello)(nil),            // 0: muxvia.cloud.v1.AgentHello
	(*AgentHeartbeat)(nil),        // 1: muxvia.cloud.v1.AgentHeartbeat
	(*AgentReady)(nil),            // 2: muxvia.cloud.v1.AgentReady
	(*AgentEvent)(nil),            // 3: muxvia.cloud.v1.AgentEvent
	(*EdgeCommand)(nil),           // 4: muxvia.cloud.v1.EdgeCommand
	(*SignedEnvelope)(nil),        // 5: muxvia.cloud.v1.SignedEnvelope
	(*HeartbeatPolicy)(nil),       // 6: muxvia.cloud.v1.HeartbeatPolicy
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_cloud_v1_agent_gateway_proto_depIdxs = []int32{
	5, // 0: muxvia.cloud.v1.AgentHello.agent_ticket:type_name -> muxvia.cloud.v1.SignedEnvelope
	6, // 1: muxvia.cloud.v1.AgentReady.heartbeat:type_name -> muxvia.cloud.v1.HeartbeatPolicy
	7, // 2: muxvia.cloud.v1.AgentEvent.sent_at:type_name -> google.protobuf.Timestamp
	0, // 3: muxvia.cloud.v1.AgentEvent.hello:type_name -> muxvia.cloud.v1.AgentHello
	1, // 4: muxvia.cloud.v1.AgentEvent.heartbeat:type_name -> muxvia.cloud.v1.AgentHeartbeat
	7, // 5: muxvia.cloud.v1.EdgeCommand.sent_at:type_name -> google.protobuf.Timestamp
	2, // 6: muxvia.cloud.v1.EdgeCommand.ready:type_name -> muxvia.cloud.v1.AgentReady
	3, // 7: muxvia.cloud.v1.AgentGateway.Connect:input_type -> muxvia.cloud.v1.AgentEvent
	4, // 8: muxvia.cloud.v1.AgentGateway.Connect:output_type -> muxvia.cloud.v1.EdgeCommand
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_cloud_v1_agent_gateway_proto_init() }
func file_cloud_v1_agent_gateway_proto_init() {
	if File_cloud_v1_agent_gateway_proto != nil {
		return
	}
	file_cloud_v1_common_proto_init()
	file_cloud_v1_agent_gateway_proto_msgTypes[3].OneofWrappers = []any{
		(*AgentEvent_Hello)(nil),
		(*AgentEvent_Heartbeat)(nil),
	}
	file_cloud_v1_agent_gateway_proto_msgTypes[4].OneofWrappers = []any{
		(*EdgeCommand_Ready)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_agent_gateway_proto_rawDesc), len(file_cloud_v1_agent_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_v1_agent_gateway_proto_goTypes,
		DependencyIndexes: file_cloud_v1_agent_gateway_proto_depIdxs,
		MessageInfos:      file_cloud_v1_agent_gateway_proto_msgTypes,
	}.Build()
	File_cloud_v1_agent_gateway_proto = out.File
	file_cloud_v1_agent_gateway_proto_goTypes = nil
	file_cloud_v1_agent_gateway_proto_depIdxs = nil
}
