// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cloud/v1/client_gateway.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectedCloudPath int32

const (
	SelectedCloudPath_SELECTED_CLOUD_PATH_UNSPECIFIED SelectedCloudPath = 0
	SelectedCloudPath_SELECTED_CLOUD_PATH_DIRECT      SelectedCloudPath = 1
	SelectedCloudPath_SELECTED_CLOUD_PATH_RELAY       SelectedCloudPath = 2
)

// Enum value maps for SelectedCloudPath.
var (
	SelectedCloudPath_name = map[int32]string{
		0: "SELECTED_CLOUD_PATH_UNSPECIFIED",
		1: "SELECTED_CLOUD_PATH_DIRECT",
		2: "SELECTED_CLOUD_PATH_RELAY",
	}
	SelectedCloudPath_value = map[string]int32{
		"SELECTED_CLOUD_PATH_UNSPECIFIED": 0,
		"SELECTED_CLOUD_PATH_DIRECT":      1,
		"SELECTED_CLOUD_PATH_RELAY":       2,
	}
)

func (x SelectedCloudPath) Enum() *SelectedCloudPath {
	p := new(SelectedCloudPath)
	*p = x
	return p
}

func (x SelectedCloudPath) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectedCloudPath) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_client_gateway_proto_enumTypes[0].Descriptor()
}

func (SelectedCloudPath) Type() protoreflect.EnumType {
	return &file_cloud_v1_client_gateway_proto_enumTypes[0]
}

func (x SelectedCloudPath) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectedCloudPath.Descriptor instead.
func (SelectedCloudPath) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{0}
}

// CloudICECandidate 是 Cloud 信令的中性 candidate；不携带授权或 terminal 数据。
type CloudICECandidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex    uint32                 `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	UsernameFragment string                 `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CloudICECandidate) Reset() {
	*x = CloudICECandidate{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudICECandidate) ProtoMessage() {}

func (x *CloudICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudICECandidate.ProtoReflect.Descriptor instead.
func (*CloudICECandidate) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CloudICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *CloudICECandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *CloudICECandidate) GetSdpMlineIndex() uint32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *CloudICECandidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

// PairingAdmission 是二维码材料的网络投影。Edge 必须将其与当前在线 daemon binding 对齐，
// 再向该 daemon 实时请求授权；它自身不是 grant，也不能兑换 capability。
type PairingAdmission struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DaemonId           string                 `protobuf:"bytes,1,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	DeviceId           string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DevicePublicKey    []byte                 `protobuf:"bytes,3,opt,name=device_public_key,json=devicePublicKey,proto3" json:"device_public_key,omitempty"`
	PairingClaimSha256 []byte                 `protobuf:"bytes,4,opt,name=pairing_claim_sha256,json=pairingClaimSha256,proto3" json:"pairing_claim_sha256,omitempty"`
	ExpiresAtUnixNano  int64                  `protobuf:"varint,5,opt,name=expires_at_unix_nano,json=expiresAtUnixNano,proto3" json:"expires_at_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PairingAdmission) Reset() {
	*x = PairingAdmission{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingAdmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingAdmission) ProtoMessage() {}

func (x *PairingAdmission) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingAdmission.ProtoReflect.Descriptor instead.
func (*PairingAdmission) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PairingAdmission) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *PairingAdmission) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PairingAdmission) GetDevicePublicKey() []byte {
	if x != nil {
		return x.DevicePublicKey
	}
	return nil
}

func (x *PairingAdmission) GetPairingClaimSha256() []byte {
	if x != nil {
		return x.PairingClaimSha256
	}
	return nil
}

func (x *PairingAdmission) GetExpiresAtUnixNano() int64 {
	if x != nil {
		return x.ExpiresAtUnixNano
	}
	return 0
}

type ClientHello struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientPublicKey   []byte                 `protobuf:"bytes,2,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	ClientProof       []byte                 `protobuf:"bytes,3,opt,name=client_proof,json=clientProof,proto3" json:"client_proof,omitempty"`
	Product           ClientProduct          `protobuf:"varint,4,opt,name=product,proto3,enum=anytty.cloud.v1.ClientProduct" json:"product,omitempty"`
	SoftwareVersion   string                 `protobuf:"bytes,5,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	AttemptGeneration uint64                 `protobuf:"varint,6,opt,name=attempt_generation,json=attemptGeneration,proto3" json:"attempt_generation,omitempty"`
	RelayPreference   RelayPreference        `protobuf:"varint,7,opt,name=relay_preference,json=relayPreference,proto3,enum=anytty.cloud.v1.RelayPreference" json:"relay_preference,omitempty"`
	// Types that are valid to be assigned to Authorization:
	//
	//	*ClientHello_CloudRouteGrant
	//	*ClientHello_PairingAdmission
	Authorization isClientHello_Authorization `protobuf_oneof:"authorization"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *ClientHello) GetClientProof() []byte {
	if x != nil {
		return x.ClientProof
	}
	return nil
}

func (x *ClientHello) GetProduct() ClientProduct {
	if x != nil {
		return x.Product
	}
	return ClientProduct_CLIENT_PRODUCT_UNSPECIFIED
}

func (x *ClientHello) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *ClientHello) GetAttemptGeneration() uint64 {
	if x != nil {
		return x.AttemptGeneration
	}
	return 0
}

func (x *ClientHello) GetRelayPreference() RelayPreference {
	if x != nil {
		return x.RelayPreference
	}
	return RelayPreference_RELAY_PREFERENCE_UNSPECIFIED
}

func (x *ClientHello) GetAuthorization() isClientHello_Authorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

func (x *ClientHello) GetCloudRouteGrant() *SignedEnvelope {
	if x != nil {
		if x, ok := x.Authorization.(*ClientHello_CloudRouteGrant); ok {
			return x.CloudRouteGrant
		}
	}
	return nil
}

func (x *ClientHello) GetPairingAdmission() *PairingAdmission {
	if x != nil {
		if x, ok := x.Authorization.(*ClientHello_PairingAdmission); ok {
			return x.PairingAdmission
		}
	}
	return nil
}

type isClientHello_Authorization interface {
	isClientHello_Authorization()
}

type ClientHello_CloudRouteGrant struct {
	// cloud_route_grant 是 owning daemon 签发给已配对 ClientAccessIdentity 的长期发现和信令授权。
	CloudRouteGrant *SignedEnvelope `protobuf:"bytes,10,opt,name=cloud_route_grant,json=cloudRouteGrant,proto3,oneof"`
}

type ClientHello_PairingAdmission struct {
	// pairing_admission 只允许 Edge 向在线 daemon 请求一次性 pairing 预检。
	PairingAdmission *PairingAdmission `protobuf:"bytes,11,opt,name=pairing_admission,json=pairingAdmission,proto3,oneof"`
}

func (*ClientHello_CloudRouteGrant) isClientHello_Authorization() {}

func (*ClientHello_PairingAdmission) isClientHello_Authorization() {}

type ClientReady struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SessionId  string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Generation uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Relay      *RelayICEConfig        `protobuf:"bytes,3,opt,name=relay,proto3" json:"relay,omitempty"`
	// AUTO 可以继续纯 P2P；只有 P2P 最终也失败时客户端才展示该原因。
	RelayFailure  *CloudEntitlementFailure `protobuf:"bytes,4,opt,name=relay_failure,json=relayFailure,proto3" json:"relay_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReady) Reset() {
	*x = ClientReady{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReady) ProtoMessage() {}

func (x *ClientReady) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReady.ProtoReflect.Descriptor instead.
func (*ClientReady) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ClientReady) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientReady) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ClientReady) GetRelay() *RelayICEConfig {
	if x != nil {
		return x.Relay
	}
	return nil
}

func (x *ClientReady) GetRelayFailure() *CloudEntitlementFailure {
	if x != nil {
		return x.RelayFailure
	}
	return nil
}

// ClientPathSelected 在 ICE/DataChannel ready 后确认实际路径，使 Edge 能立即释放未使用的 Relay 预留。
type ClientPathSelected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Path          SelectedCloudPath      `protobuf:"varint,2,opt,name=path,proto3,enum=anytty.cloud.v1.SelectedCloudPath" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPathSelected) Reset() {
	*x = ClientPathSelected{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPathSelected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPathSelected) ProtoMessage() {}

func (x *ClientPathSelected) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPathSelected.ProtoReflect.Descriptor instead.
func (*ClientPathSelected) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ClientPathSelected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientPathSelected) GetPath() SelectedCloudPath {
	if x != nil {
		return x.Path
	}
	return SelectedCloudPath_SELECTED_CLOUD_PATH_UNSPECIFIED
}

type ClientOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OfferSdp      string                 `protobuf:"bytes,2,opt,name=offer_sdp,json=offerSdp,proto3" json:"offer_sdp,omitempty"`
	Candidates    []*CloudICECandidate   `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientOffer) Reset() {
	*x = ClientOffer{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOffer) ProtoMessage() {}

func (x *ClientOffer) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOffer.ProtoReflect.Descriptor instead.
func (*ClientOffer) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *ClientOffer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientOffer) GetOfferSdp() string {
	if x != nil {
		return x.OfferSdp
	}
	return ""
}

func (x *ClientOffer) GetCandidates() []*CloudICECandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type EdgeAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AnswerSdp     string                 `protobuf:"bytes,2,opt,name=answer_sdp,json=answerSdp,proto3" json:"answer_sdp,omitempty"`
	Candidates    []*CloudICECandidate   `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeAnswer) Reset() {
	*x = EdgeAnswer{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeAnswer) ProtoMessage() {}

func (x *EdgeAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeAnswer.ProtoReflect.Descriptor instead.
func (*EdgeAnswer) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *EdgeAnswer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeAnswer) GetAnswerSdp() string {
	if x != nil {
		return x.AnswerSdp
	}
	return ""
}

func (x *EdgeAnswer) GetCandidates() []*CloudICECandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SignalRejected struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	SessionId          string                   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code               string                   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message            string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EntitlementFailure *CloudEntitlementFailure `protobuf:"bytes,4,opt,name=entitlement_failure,json=entitlementFailure,proto3" json:"entitlement_failure,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignalRejected) Reset() {
	*x = SignalRejected{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRejected) ProtoMessage() {}

func (x *SignalRejected) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRejected.ProtoReflect.Descriptor instead.
func (*SignalRejected) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *SignalRejected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignalRejected) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SignalRejected) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignalRejected) GetEntitlementFailure() *CloudEntitlementFailure {
	if x != nil {
		return x.EntitlementFailure
	}
	return nil
}

type ClientSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	BootId          string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	StreamSeq       uint64                 `protobuf:"varint,6,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientSignal_Hello
	//	*ClientSignal_Offer
	//	*ClientSignal_PathSelected
	Payload       isClientSignal_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSignal) Reset() {
	*x = ClientSignal{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSignal) ProtoMessage() {}

func (x *ClientSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSignal.ProtoReflect.Descriptor instead.
func (*ClientSignal) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ClientSignal) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ClientSignal) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ClientSignal) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ClientSignal) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *ClientSignal) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ClientSignal) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *ClientSignal) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *ClientSignal) GetPayload() isClientSignal_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientSignal) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientSignal) GetOffer() *ClientOffer {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_Offer); ok {
			return x.Offer
		}
	}
	return nil
}

func (x *ClientSignal) GetPathSelected() *ClientPathSelected {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_PathSelected); ok {
			return x.PathSelected
		}
	}
	return nil
}

type isClientSignal_Payload interface {
	isClientSignal_Payload()
}

type ClientSignal_Hello struct {
	Hello *ClientHello `protobuf:"bytes,20,opt,name=hello,proto3,oneof"`
}

type ClientSignal_Offer struct {
	Offer *ClientOffer `protobuf:"bytes,21,opt,name=offer,proto3,oneof"`
}

type ClientSignal_PathSelected struct {
	PathSelected *ClientPathSelected `protobuf:"bytes,22,opt,name=path_selected,json=pathSelected,proto3,oneof"`
}

func (*ClientSignal_Hello) isClientSignal_Payload() {}

func (*ClientSignal_Offer) isClientSignal_Payload() {}

func (*ClientSignal_PathSelected) isClientSignal_Payload() {}

type EdgeSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	BootId          string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	StreamSeq       uint64                 `protobuf:"varint,6,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EdgeSignal_Ready
	//	*EdgeSignal_Answer
	//	*EdgeSignal_Rejected
	//	*EdgeSignal_Challenge
	Payload       isEdgeSignal_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeSignal) Reset() {
	*x = EdgeSignal{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeSignal) ProtoMessage() {}

func (x *EdgeSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeSignal.ProtoReflect.Descriptor instead.
func (*EdgeSignal) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *EdgeSignal) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EdgeSignal) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EdgeSignal) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EdgeSignal) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *EdgeSignal) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *EdgeSignal) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *EdgeSignal) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *EdgeSignal) GetPayload() isEdgeSignal_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EdgeSignal) GetReady() *ClientReady {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *EdgeSignal) GetAnswer() *EdgeAnswer {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *EdgeSignal) GetRejected() *SignalRejected {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *EdgeSignal) GetChallenge() *EdgeChallenge {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

type isEdgeSignal_Payload interface {
	isEdgeSignal_Payload()
}

type EdgeSignal_Ready struct {
	Ready *ClientReady `protobuf:"bytes,20,opt,name=ready,proto3,oneof"`
}

type EdgeSignal_Answer struct {
	Answer *EdgeAnswer `protobuf:"bytes,21,opt,name=answer,proto3,oneof"`
}

type EdgeSignal_Rejected struct {
	Rejected *SignalRejected `protobuf:"bytes,22,opt,name=rejected,proto3,oneof"`
}

type EdgeSignal_Challenge struct {
	Challenge *EdgeChallenge `protobuf:"bytes,23,opt,name=challenge,proto3,oneof"`
}

func (*EdgeSignal_Ready) isEdgeSignal_Payload() {}

func (*EdgeSignal_Answer) isEdgeSignal_Payload() {}

func (*EdgeSignal_Rejected) isEdgeSignal_Payload() {}

func (*EdgeSignal_Challenge) isEdgeSignal_Payload() {}

var File_cloud_v1_client_gateway_proto protoreflect.FileDescriptor

const file_cloud_v1_client_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1dcloud/v1/client_gateway.proto\x12\x0fanytty.cloud.v1\x1a\x15cloud/v1/common.proto\x1a\x16cloud/v1/runtime.proto\x1a\x14cloud/v1/usage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\x11CloudICECandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\rR\rsdpMlineIndex\x12+\n" +
	"\x11username_fragment\x18\x04 \x01(\tR\x10usernameFragment\"\xdb\x01\n" +
	"\x10PairingAdmission\x12\x1b\n" +
	"\tdaemon_id\x18\x01 \x01(\tR\bdaemonId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12*\n" +
	"\x11device_public_key\x18\x03 \x01(\fR\x0fdevicePublicKey\x120\n" +
	"\x14pairing_claim_sha256\x18\x04 \x01(\fR\x12pairingClaimSha256\x12/\n" +
	"\x14expires_at_unix_nano\x18\x05 \x01(\x03R\x11expiresAtUnixNano\"\xef\x03\n" +
	"\vClientHello\x12*\n" +
	"\x11client_public_key\x18\x02 \x01(\fR\x0fclientPublicKey\x12!\n" +
	"\fclient_proof\x18\x03 \x01(\fR\vclientProof\x128\n" +
	"\aproduct\x18\x04 \x01(\x0e2\x1e.anytty.cloud.v1.ClientProductR\aproduct\x12)\n" +
	"\x10software_version\x18\x05 \x01(\tR\x0fsoftwareVersion\x12-\n" +
	"\x12attempt_generation\x18\x06 \x01(\x04R\x11attemptGeneration\x12K\n" +
	"\x10relay_preference\x18\a \x01(\x0e2 .anytty.cloud.v1.RelayPreferenceR\x0frelayPreference\x12M\n" +
	"\x11cloud_route_grant\x18\n" +
	" \x01(\v2\x1f.anytty.cloud.v1.SignedEnvelopeH\x00R\x0fcloudRouteGrant\x12P\n" +
	"\x11pairing_admission\x18\v \x01(\v2!.anytty.cloud.v1.PairingAdmissionH\x00R\x10pairingAdmissionB\x0f\n" +
	"\rauthorization\"\xd2\x01\n" +
	"\vClientReady\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x125\n" +
	"\x05relay\x18\x03 \x01(\v2\x1f.anytty.cloud.v1.RelayICEConfigR\x05relay\x12M\n" +
	"\rrelay_failure\x18\x04 \x01(\v2(.anytty.cloud.v1.CloudEntitlementFailureR\frelayFailure\"k\n" +
	"\x12ClientPathSelected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x126\n" +
	"\x04path\x18\x02 \x01(\x0e2\".anytty.cloud.v1.SelectedCloudPathR\x04path\"\x8d\x01\n" +
	"\vClientOffer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\toffer_sdp\x18\x02 \x01(\tR\bofferSdp\x12B\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\".anytty.cloud.v1.CloudICECandidateR\n" +
	"candidates\"\x8e\x01\n" +
	"\n" +
	"EdgeAnswer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"answer_sdp\x18\x02 \x01(\tR\tanswerSdp\x12B\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\".anytty.cloud.v1.CloudICECandidateR\n" +
	"candidates\"\xb8\x01\n" +
	"\x0eSignalRejected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12Y\n" +
	"\x13entitlement_failure\x18\x04 \x01(\v2(.anytty.cloud.v1.CloudEntitlementFailureR\x12entitlementFailure\"\xca\x03\n" +
	"\fClientSignal\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x06 \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x124\n" +
	"\x05hello\x18\x14 \x01(\v2\x1c.anytty.cloud.v1.ClientHelloH\x00R\x05hello\x124\n" +
	"\x05offer\x18\x15 \x01(\v2\x1c.anytty.cloud.v1.ClientOfferH\x00R\x05offer\x12J\n" +
	"\rpath_selected\x18\x16 \x01(\v2#.anytty.cloud.v1.ClientPathSelectedH\x00R\fpathSelectedB\t\n" +
	"\apayload\"\xfc\x03\n" +
	"\n" +
	"EdgeSignal\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x06 \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x124\n" +
	"\x05ready\x18\x14 \x01(\v2\x1c.anytty.cloud.v1.ClientReadyH\x00R\x05ready\x125\n" +
	"\x06answer\x18\x15 \x01(\v2\x1b.anytty.cloud.v1.EdgeAnswerH\x00R\x06answer\x12=\n" +
	"\brejected\x18\x16 \x01(\v2\x1f.anytty.cloud.v1.SignalRejectedH\x00R\brejected\x12>\n" +
	"\tchallenge\x18\x17 \x01(\v2\x1e.anytty.cloud.v1.EdgeChallengeH\x00R\tchallengeB\t\n" +
	"\apayload*w\n" +
	"\x11SelectedCloudPath\x12#\n" +
	"\x1fSELECTED_CLOUD_PATH_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSELECTED_CLOUD_PATH_DIRECT\x10\x01\x12\x1d\n" +
	"\x19SELECTED_CLOUD_PATH_RELAY\x10\x022Z\n" +
	"\rClientGateway\x12I\n" +
	"\aConnect\x12\x1d.anytty.cloud.v1.ClientSignal\x1a\x1b.anytty.cloud.v1.EdgeSignal(\x010\x01B1Z/github.com/anytty/anytty/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_client_gateway_proto_rawDescOnce sync.Once
	file_cloud_v1_client_gateway_proto_rawDescData []byte
)

func file_cloud_v1_client_gateway_proto_rawDescGZIP() []byte {
	file_cloud_v1_client_gateway_proto_rawDescOnce.Do(func() {
		file_cloud_v1_client_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_client_gateway_proto_rawDesc), len(file_cloud_v1_client_gateway_proto_rawDesc)))
	})
	return file_cloud_v1_client_gateway_proto_rawDescData
}

var file_cloud_v1_client_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_v1_client_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_cloud_v1_client_gateway_proto_goTypes = []any{
	(SelectedCloudPath)(0),          // 0: anytty.cloud.v1.SelectedCloudPath
	(*CloudICECandidate)(nil),       // 1: anytty.cloud.v1.CloudICECandidate
	(*PairingAdmission)(nil),        // 2: anytty.cloud.v1.PairingAdmission
	(*ClientHello)(nil),             // 3: anytty.cloud.v1.ClientHello
	(*ClientReady)(nil),             // 4: anytty.cloud.v1.ClientReady
	(*ClientPathSelected)(nil),      // 5: anytty.cloud.v1.ClientPathSelected
	(*ClientOffer)(nil),             // 6: anytty.cloud.v1.ClientOffer
	(*EdgeAnswer)(nil),              // 7: anytty.cloud.v1.EdgeAnswer
	(*SignalRejected)(nil),          // 8: anytty.cloud.v1.SignalRejected
	(*ClientSignal)(nil),            // 9: anytty.cloud.v1.ClientSignal
	(*EdgeSignal)(nil),              // 10: anytty.cloud.v1.EdgeSignal
	(ClientProduct)(0),              // 11: anytty.cloud.v1.ClientProduct
	(RelayPreference)(0),            // 12: anytty.cloud.v1.RelayPreference
	(*SignedEnvelope)(nil),          // 13: anytty.cloud.v1.SignedEnvelope
	(*RelayICEConfig)(nil),          // 14: anytty.cloud.v1.RelayICEConfig
	(*CloudEntitlementFailure)(nil), // 15: anytty.cloud.v1.CloudEntitlementFailure
	(*timestamppb.Timestamp)(nil),   // 16: google.protobuf.Timestamp
	(*EdgeChallenge)(nil),           // 17: anytty.cloud.v1.EdgeChallenge
}
var file_cloud_v1_client_gateway_proto_depIdxs = []int32{
	11, // 0: anytty.cloud.v1.ClientHello.product:type_name -> anytty.cloud.v1.ClientProduct
	12, // 1: anytty.cloud.v1.ClientHello.relay_preference:type_name -> anytty.cloud.v1.RelayPreference
	13, // 2: anytty.cloud.v1.ClientHello.cloud_route_grant:type_name -> anytty.cloud.v1.SignedEnvelope
	2,  // 3: anytty.cloud.v1.ClientHello.pairing_admission:type_name -> anytty.cloud.v1.PairingAdmission
	14, // 4: anytty.cloud.v1.ClientReady.relay:type_name -> anytty.cloud.v1.RelayICEConfig
	15, // 5: anytty.cloud.v1.ClientReady.relay_failure:type_name -> anytty.cloud.v1.CloudEntitlementFailure
	0,  // 6: anytty.cloud.v1.ClientPathSelected.path:type_name -> anytty.cloud.v1.SelectedCloudPath
	1,  // 7: anytty.cloud.v1.ClientOffer.candidates:type_name -> anytty.cloud.v1.CloudICECandidate
	1,  // 8: anytty.cloud.v1.EdgeAnswer.candidates:type_name -> anytty.cloud.v1.CloudICECandidate
	15, // 9: anytty.cloud.v1.SignalRejected.entitlement_failure:type_name -> anytty.cloud.v1.CloudEntitlementFailure
	16, // 10: anytty.cloud.v1.ClientSignal.sent_at:type_name -> google.protobuf.Timestamp
	3,  // 11: anytty.cloud.v1.ClientSignal.hello:type_name -> anytty.cloud.v1.ClientHello
	6,  // 12: anytty.cloud.v1.ClientSignal.offer:type_name -> anytty.cloud.v1.ClientOffer
	5,  // 13: anytty.cloud.v1.ClientSignal.path_selected:type_name -> anytty.cloud.v1.ClientPathSelected
	16, // 14: anytty.cloud.v1.EdgeSignal.sent_at:type_name -> google.protobuf.Timestamp
	4,  // 15: anytty.cloud.v1.EdgeSignal.ready:type_name -> anytty.cloud.v1.ClientReady
	7,  // 16: anytty.cloud.v1.EdgeSignal.answer:type_name -> anytty.cloud.v1.EdgeAnswer
	8,  // 17: anytty.cloud.v1.EdgeSignal.rejected:type_name -> anytty.cloud.v1.SignalRejected
	17, // 18: anytty.cloud.v1.EdgeSignal.challenge:type_name -> anytty.cloud.v1.EdgeChallenge
	9,  // 19: anytty.cloud.v1.ClientGateway.Connect:input_type -> anytty.cloud.v1.ClientSignal
	10, // 20: anytty.cloud.v1.ClientGateway.Connect:output_type -> anytty.cloud.v1.EdgeSignal
	20, // [20:21] is the sub-list for method output_type
	19, // [19:20] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_cloud_v1_client_gateway_proto_init() }
func file_cloud_v1_client_gateway_proto_init() {
	if File_cloud_v1_client_gateway_proto != nil {
		return
	}
	file_cloud_v1_common_proto_init()
	file_cloud_v1_runtime_proto_init()
	file_cloud_v1_usage_proto_init()
	file_cloud_v1_client_gateway_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientHello_CloudRouteGrant)(nil),
		(*ClientHello_PairingAdmission)(nil),
	}
	file_cloud_v1_client_gateway_proto_msgTypes[8].OneofWrappers = []any{
		(*ClientSignal_Hello)(nil),
		(*ClientSignal_Offer)(nil),
		(*ClientSignal_PathSelected)(nil),
	}
	file_cloud_v1_client_gateway_proto_msgTypes[9].OneofWrappers = []any{
		(*EdgeSignal_Ready)(nil),
		(*EdgeSignal_Answer)(nil),
		(*EdgeSignal_Rejected)(nil),
		(*EdgeSignal_Challenge)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_client_gateway_proto_rawDesc), len(file_cloud_v1_client_gateway_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_v1_client_gateway_proto_goTypes,
		DependencyIndexes: file_cloud_v1_client_gateway_proto_depIdxs,
		EnumInfos:         file_cloud_v1_client_gateway_proto_enumTypes,
		MessageInfos:      file_cloud_v1_client_gateway_proto_msgTypes,
	}.Build()
	File_cloud_v1_client_gateway_proto = out.File
	file_cloud_v1_client_gateway_proto_goTypes = nil
	file_cloud_v1_client_gateway_proto_depIdxs = nil
}
