// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cloud/v1/client_gateway.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CloudICECandidate 是 Cloud 信令的中性 candidate；不携带授权或 terminal 数据。
type CloudICECandidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex    uint32                 `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	UsernameFragment string                 `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CloudICECandidate) Reset() {
	*x = CloudICECandidate{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudICECandidate) ProtoMessage() {}

func (x *CloudICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudICECandidate.ProtoReflect.Descriptor instead.
func (*CloudICECandidate) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CloudICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *CloudICECandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *CloudICECandidate) GetSdpMlineIndex() uint32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *CloudICECandidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

type ClientHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// route_grant 是 owning daemon 签发的 capability 或 pairing RouteGrant；Controller 不签客户端准入票。
	RouteGrant        *SignedEnvelope       `protobuf:"bytes,1,opt,name=route_grant,json=routeGrant,proto3" json:"route_grant,omitempty"`
	ClientPublicKey   []byte                `protobuf:"bytes,2,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	ClientProof       []byte                `protobuf:"bytes,3,opt,name=client_proof,json=clientProof,proto3" json:"client_proof,omitempty"`
	Product           ClientProduct         `protobuf:"varint,4,opt,name=product,proto3,enum=anytty.cloud.v1.ClientProduct" json:"product,omitempty"`
	SoftwareVersion   string                `protobuf:"bytes,5,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	AttemptGeneration uint64                `protobuf:"varint,6,opt,name=attempt_generation,json=attemptGeneration,proto3" json:"attempt_generation,omitempty"`
	RelayPreference   RelayPreference       `protobuf:"varint,7,opt,name=relay_preference,json=relayPreference,proto3,enum=anytty.cloud.v1.RelayPreference" json:"relay_preference,omitempty"`
	AccessMode        CloudClientAccessMode `protobuf:"varint,8,opt,name=access_mode,json=accessMode,proto3,enum=anytty.cloud.v1.CloudClientAccessMode" json:"access_mode,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *ClientHello) GetRouteGrant() *SignedEnvelope {
	if x != nil {
		return x.RouteGrant
	}
	return nil
}

func (x *ClientHello) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *ClientHello) GetClientProof() []byte {
	if x != nil {
		return x.ClientProof
	}
	return nil
}

func (x *ClientHello) GetProduct() ClientProduct {
	if x != nil {
		return x.Product
	}
	return ClientProduct_CLIENT_PRODUCT_UNSPECIFIED
}

func (x *ClientHello) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *ClientHello) GetAttemptGeneration() uint64 {
	if x != nil {
		return x.AttemptGeneration
	}
	return 0
}

func (x *ClientHello) GetRelayPreference() RelayPreference {
	if x != nil {
		return x.RelayPreference
	}
	return RelayPreference_RELAY_PREFERENCE_UNSPECIFIED
}

func (x *ClientHello) GetAccessMode() CloudClientAccessMode {
	if x != nil {
		return x.AccessMode
	}
	return CloudClientAccessMode_CLOUD_CLIENT_ACCESS_MODE_UNSPECIFIED
}

type ClientReady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Generation    uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Relay         *RelayICEConfig        `protobuf:"bytes,3,opt,name=relay,proto3" json:"relay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReady) Reset() {
	*x = ClientReady{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReady) ProtoMessage() {}

func (x *ClientReady) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReady.ProtoReflect.Descriptor instead.
func (*ClientReady) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ClientReady) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientReady) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ClientReady) GetRelay() *RelayICEConfig {
	if x != nil {
		return x.Relay
	}
	return nil
}

type ClientOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OfferSdp      string                 `protobuf:"bytes,2,opt,name=offer_sdp,json=offerSdp,proto3" json:"offer_sdp,omitempty"`
	Candidates    []*CloudICECandidate   `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientOffer) Reset() {
	*x = ClientOffer{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOffer) ProtoMessage() {}

func (x *ClientOffer) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOffer.ProtoReflect.Descriptor instead.
func (*ClientOffer) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ClientOffer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientOffer) GetOfferSdp() string {
	if x != nil {
		return x.OfferSdp
	}
	return ""
}

func (x *ClientOffer) GetCandidates() []*CloudICECandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type EdgeAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AnswerSdp     string                 `protobuf:"bytes,2,opt,name=answer_sdp,json=answerSdp,proto3" json:"answer_sdp,omitempty"`
	Candidates    []*CloudICECandidate   `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeAnswer) Reset() {
	*x = EdgeAnswer{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeAnswer) ProtoMessage() {}

func (x *EdgeAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeAnswer.ProtoReflect.Descriptor instead.
func (*EdgeAnswer) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *EdgeAnswer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeAnswer) GetAnswerSdp() string {
	if x != nil {
		return x.AnswerSdp
	}
	return ""
}

func (x *EdgeAnswer) GetCandidates() []*CloudICECandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SignalRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalRejected) Reset() {
	*x = SignalRejected{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRejected) ProtoMessage() {}

func (x *SignalRejected) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRejected.ProtoReflect.Descriptor instead.
func (*SignalRejected) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *SignalRejected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignalRejected) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SignalRejected) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	BootId          string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	StreamSeq       uint64                 `protobuf:"varint,6,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientSignal_Hello
	//	*ClientSignal_Offer
	Payload       isClientSignal_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSignal) Reset() {
	*x = ClientSignal{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSignal) ProtoMessage() {}

func (x *ClientSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSignal.ProtoReflect.Descriptor instead.
func (*ClientSignal) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ClientSignal) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ClientSignal) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ClientSignal) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ClientSignal) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *ClientSignal) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ClientSignal) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *ClientSignal) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *ClientSignal) GetPayload() isClientSignal_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientSignal) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientSignal) GetOffer() *ClientOffer {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_Offer); ok {
			return x.Offer
		}
	}
	return nil
}

type isClientSignal_Payload interface {
	isClientSignal_Payload()
}

type ClientSignal_Hello struct {
	Hello *ClientHello `protobuf:"bytes,20,opt,name=hello,proto3,oneof"`
}

type ClientSignal_Offer struct {
	Offer *ClientOffer `protobuf:"bytes,21,opt,name=offer,proto3,oneof"`
}

func (*ClientSignal_Hello) isClientSignal_Payload() {}

func (*ClientSignal_Offer) isClientSignal_Payload() {}

type EdgeSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	BootId          string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	StreamSeq       uint64                 `protobuf:"varint,6,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EdgeSignal_Ready
	//	*EdgeSignal_Answer
	//	*EdgeSignal_Rejected
	Payload       isEdgeSignal_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeSignal) Reset() {
	*x = EdgeSignal{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeSignal) ProtoMessage() {}

func (x *EdgeSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeSignal.ProtoReflect.Descriptor instead.
func (*EdgeSignal) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *EdgeSignal) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EdgeSignal) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EdgeSignal) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EdgeSignal) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *EdgeSignal) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *EdgeSignal) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *EdgeSignal) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *EdgeSignal) GetPayload() isEdgeSignal_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EdgeSignal) GetReady() *ClientReady {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *EdgeSignal) GetAnswer() *EdgeAnswer {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *EdgeSignal) GetRejected() *SignalRejected {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

type isEdgeSignal_Payload interface {
	isEdgeSignal_Payload()
}

type EdgeSignal_Ready struct {
	Ready *ClientReady `protobuf:"bytes,20,opt,name=ready,proto3,oneof"`
}

type EdgeSignal_Answer struct {
	Answer *EdgeAnswer `protobuf:"bytes,21,opt,name=answer,proto3,oneof"`
}

type EdgeSignal_Rejected struct {
	Rejected *SignalRejected `protobuf:"bytes,22,opt,name=rejected,proto3,oneof"`
}

func (*EdgeSignal_Ready) isEdgeSignal_Payload() {}

func (*EdgeSignal_Answer) isEdgeSignal_Payload() {}

func (*EdgeSignal_Rejected) isEdgeSignal_Payload() {}

var File_cloud_v1_client_gateway_proto protoreflect.FileDescriptor

const file_cloud_v1_client_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1dcloud/v1/client_gateway.proto\x12\x0fanytty.cloud.v1\x1a\x15cloud/v1/common.proto\x1a\x16cloud/v1/runtime.proto\x1a\x14cloud/v1/usage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\x11CloudICECandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\rR\rsdpMlineIndex\x12+\n" +
	"\x11username_fragment\x18\x04 \x01(\tR\x10usernameFragment\"\xc8\x03\n" +
	"\vClientHello\x12@\n" +
	"\vroute_grant\x18\x01 \x01(\v2\x1f.anytty.cloud.v1.SignedEnvelopeR\n" +
	"routeGrant\x12*\n" +
	"\x11client_public_key\x18\x02 \x01(\fR\x0fclientPublicKey\x12!\n" +
	"\fclient_proof\x18\x03 \x01(\fR\vclientProof\x128\n" +
	"\aproduct\x18\x04 \x01(\x0e2\x1e.anytty.cloud.v1.ClientProductR\aproduct\x12)\n" +
	"\x10software_version\x18\x05 \x01(\tR\x0fsoftwareVersion\x12-\n" +
	"\x12attempt_generation\x18\x06 \x01(\x04R\x11attemptGeneration\x12K\n" +
	"\x10relay_preference\x18\a \x01(\x0e2 .anytty.cloud.v1.RelayPreferenceR\x0frelayPreference\x12G\n" +
	"\vaccess_mode\x18\b \x01(\x0e2&.anytty.cloud.v1.CloudClientAccessModeR\n" +
	"accessMode\"\x83\x01\n" +
	"\vClientReady\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x125\n" +
	"\x05relay\x18\x03 \x01(\v2\x1f.anytty.cloud.v1.RelayICEConfigR\x05relay\"\x8d\x01\n" +
	"\vClientOffer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\toffer_sdp\x18\x02 \x01(\tR\bofferSdp\x12B\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\".anytty.cloud.v1.CloudICECandidateR\n" +
	"candidates\"\x8e\x01\n" +
	"\n" +
	"EdgeAnswer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"answer_sdp\x18\x02 \x01(\tR\tanswerSdp\x12B\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\".anytty.cloud.v1.CloudICECandidateR\n" +
	"candidates\"]\n" +
	"\x0eSignalRejected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xfe\x02\n" +
	"\fClientSignal\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x06 \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x124\n" +
	"\x05hello\x18\x14 \x01(\v2\x1c.anytty.cloud.v1.ClientHelloH\x00R\x05hello\x124\n" +
	"\x05offer\x18\x15 \x01(\v2\x1c.anytty.cloud.v1.ClientOfferH\x00R\x05offerB\t\n" +
	"\apayload\"\xbc\x03\n" +
	"\n" +
	"EdgeSignal\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x06 \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x124\n" +
	"\x05ready\x18\x14 \x01(\v2\x1c.anytty.cloud.v1.ClientReadyH\x00R\x05ready\x125\n" +
	"\x06answer\x18\x15 \x01(\v2\x1b.anytty.cloud.v1.EdgeAnswerH\x00R\x06answer\x12=\n" +
	"\brejected\x18\x16 \x01(\v2\x1f.anytty.cloud.v1.SignalRejectedH\x00R\brejectedB\t\n" +
	"\apayload2Z\n" +
	"\rClientGateway\x12I\n" +
	"\aConnect\x12\x1d.anytty.cloud.v1.ClientSignal\x1a\x1b.anytty.cloud.v1.EdgeSignal(\x010\x01B1Z/github.com/anytty/anytty/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_client_gateway_proto_rawDescOnce sync.Once
	file_cloud_v1_client_gateway_proto_rawDescData []byte
)

func file_cloud_v1_client_gateway_proto_rawDescGZIP() []byte {
	file_cloud_v1_client_gateway_proto_rawDescOnce.Do(func() {
		file_cloud_v1_client_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_client_gateway_proto_rawDesc), len(file_cloud_v1_client_gateway_proto_rawDesc)))
	})
	return file_cloud_v1_client_gateway_proto_rawDescData
}

var file_cloud_v1_client_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cloud_v1_client_gateway_proto_goTypes = []any{
	(*CloudICECandidate)(nil),     // 0: anytty.cloud.v1.CloudICECandidate
	(*ClientHello)(nil),           // 1: anytty.cloud.v1.ClientHello
	(*ClientReady)(nil),           // 2: anytty.cloud.v1.ClientReady
	(*ClientOffer)(nil),           // 3: anytty.cloud.v1.ClientOffer
	(*EdgeAnswer)(nil),            // 4: anytty.cloud.v1.EdgeAnswer
	(*SignalRejected)(nil),        // 5: anytty.cloud.v1.SignalRejected
	(*ClientSignal)(nil),          // 6: anytty.cloud.v1.ClientSignal
	(*EdgeSignal)(nil),            // 7: anytty.cloud.v1.EdgeSignal
	(*SignedEnvelope)(nil),        // 8: anytty.cloud.v1.SignedEnvelope
	(ClientProduct)(0),            // 9: anytty.cloud.v1.ClientProduct
	(RelayPreference)(0),          // 10: anytty.cloud.v1.RelayPreference
	(CloudClientAccessMode)(0),    // 11: anytty.cloud.v1.CloudClientAccessMode
	(*RelayICEConfig)(nil),        // 12: anytty.cloud.v1.RelayICEConfig
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_cloud_v1_client_gateway_proto_depIdxs = []int32{
	8,  // 0: anytty.cloud.v1.ClientHello.route_grant:type_name -> anytty.cloud.v1.SignedEnvelope
	9,  // 1: anytty.cloud.v1.ClientHello.product:type_name -> anytty.cloud.v1.ClientProduct
	10, // 2: anytty.cloud.v1.ClientHello.relay_preference:type_name -> anytty.cloud.v1.RelayPreference
	11, // 3: anytty.cloud.v1.ClientHello.access_mode:type_name -> anytty.cloud.v1.CloudClientAccessMode
	12, // 4: anytty.cloud.v1.ClientReady.relay:type_name -> anytty.cloud.v1.RelayICEConfig
	0,  // 5: anytty.cloud.v1.ClientOffer.candidates:type_name -> anytty.cloud.v1.CloudICECandidate
	0,  // 6: anytty.cloud.v1.EdgeAnswer.candidates:type_name -> anytty.cloud.v1.CloudICECandidate
	13, // 7: anytty.cloud.v1.ClientSignal.sent_at:type_name -> google.protobuf.Timestamp
	1,  // 8: anytty.cloud.v1.ClientSignal.hello:type_name -> anytty.cloud.v1.ClientHello
	3,  // 9: anytty.cloud.v1.ClientSignal.offer:type_name -> anytty.cloud.v1.ClientOffer
	13, // 10: anytty.cloud.v1.EdgeSignal.sent_at:type_name -> google.protobuf.Timestamp
	2,  // 11: anytty.cloud.v1.EdgeSignal.ready:type_name -> anytty.cloud.v1.ClientReady
	4,  // 12: anytty.cloud.v1.EdgeSignal.answer:type_name -> anytty.cloud.v1.EdgeAnswer
	5,  // 13: anytty.cloud.v1.EdgeSignal.rejected:type_name -> anytty.cloud.v1.SignalRejected
	6,  // 14: anytty.cloud.v1.ClientGateway.Connect:input_type -> anytty.cloud.v1.ClientSignal
	7,  // 15: anytty.cloud.v1.ClientGateway.Connect:output_type -> anytty.cloud.v1.EdgeSignal
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_cloud_v1_client_gateway_proto_init() }
func file_cloud_v1_client_gateway_proto_init() {
	if File_cloud_v1_client_gateway_proto != nil {
		return
	}
	file_cloud_v1_common_proto_init()
	file_cloud_v1_runtime_proto_init()
	file_cloud_v1_usage_proto_init()
	file_cloud_v1_client_gateway_proto_msgTypes[6].OneofWrappers = []any{
		(*ClientSignal_Hello)(nil),
		(*ClientSignal_Offer)(nil),
	}
	file_cloud_v1_client_gateway_proto_msgTypes[7].OneofWrappers = []any{
		(*EdgeSignal_Ready)(nil),
		(*EdgeSignal_Answer)(nil),
		(*EdgeSignal_Rejected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_client_gateway_proto_rawDesc), len(file_cloud_v1_client_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_v1_client_gateway_proto_goTypes,
		DependencyIndexes: file_cloud_v1_client_gateway_proto_depIdxs,
		MessageInfos:      file_cloud_v1_client_gateway_proto_msgTypes,
	}.Build()
	File_cloud_v1_client_gateway_proto = out.File
	file_cloud_v1_client_gateway_proto_goTypes = nil
	file_cloud_v1_client_gateway_proto_depIdxs = nil
}
