// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cloud/v1/common.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EdgeChallengeTarget 把一次 challenge 限定到唯一 Gateway 协议，禁止跨流类型复用。
type EdgeChallengeTarget int32

const (
	EdgeChallengeTarget_EDGE_CHALLENGE_TARGET_UNSPECIFIED    EdgeChallengeTarget = 0
	EdgeChallengeTarget_EDGE_CHALLENGE_TARGET_AGENT_GATEWAY  EdgeChallengeTarget = 1
	EdgeChallengeTarget_EDGE_CHALLENGE_TARGET_CLIENT_GATEWAY EdgeChallengeTarget = 2
)

// Enum value maps for EdgeChallengeTarget.
var (
	EdgeChallengeTarget_name = map[int32]string{
		0: "EDGE_CHALLENGE_TARGET_UNSPECIFIED",
		1: "EDGE_CHALLENGE_TARGET_AGENT_GATEWAY",
		2: "EDGE_CHALLENGE_TARGET_CLIENT_GATEWAY",
	}
	EdgeChallengeTarget_value = map[string]int32{
		"EDGE_CHALLENGE_TARGET_UNSPECIFIED":    0,
		"EDGE_CHALLENGE_TARGET_AGENT_GATEWAY":  1,
		"EDGE_CHALLENGE_TARGET_CLIENT_GATEWAY": 2,
	}
)

func (x EdgeChallengeTarget) Enum() *EdgeChallengeTarget {
	p := new(EdgeChallengeTarget)
	*p = x
	return p
}

func (x EdgeChallengeTarget) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeChallengeTarget) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_common_proto_enumTypes[0].Descriptor()
}

func (EdgeChallengeTarget) Type() protoreflect.EnumType {
	return &file_cloud_v1_common_proto_enumTypes[0]
}

func (x EdgeChallengeTarget) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeChallengeTarget.Descriptor instead.
func (EdgeChallengeTarget) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_common_proto_rawDescGZIP(), []int{0}
}

// VerificationKey 是 Controller 下发给 Edge 的公开验签密钥。
// public_key 只能包含公钥编码，不得携带私钥或 KMS 凭据。
type VerificationKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerificationKey) Reset() {
	*x = VerificationKey{}
	mi := &file_cloud_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerificationKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerificationKey) ProtoMessage() {}

func (x *VerificationKey) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerificationKey.ProtoReflect.Descriptor instead.
func (*VerificationKey) Descriptor() ([]byte, []int) {
	return file_cloud_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *VerificationKey) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *VerificationKey) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *VerificationKey) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

// KeyBundle 是 Controller 发布并由 Edge 原子持久化的完整 binding 验签 keyset。
// revision 只随 keyset owner 单调变化；issued_at/expires_at 限制离线 admission 窗口。
type KeyBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revision      uint64                 `protobuf:"varint,1,opt,name=revision,proto3" json:"revision,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Keys          []*VerificationKey     `protobuf:"bytes,4,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyBundle) Reset() {
	*x = KeyBundle{}
	mi := &file_cloud_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyBundle) ProtoMessage() {}

func (x *KeyBundle) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyBundle.ProtoReflect.Descriptor instead.
func (*KeyBundle) Descriptor() ([]byte, []int) {
	return file_cloud_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *KeyBundle) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *KeyBundle) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *KeyBundle) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *KeyBundle) GetKeys() []*VerificationKey {
	if x != nil {
		return x.Keys
	}
	return nil
}

// HeartbeatPolicy 约束 EdgeControl 的心跳频率和 Controller 失联判定。
type HeartbeatPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interval      *durationpb.Duration   `protobuf:"bytes,1,opt,name=interval,proto3" json:"interval,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatPolicy) Reset() {
	*x = HeartbeatPolicy{}
	mi := &file_cloud_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatPolicy) ProtoMessage() {}

func (x *HeartbeatPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatPolicy.ProtoReflect.Descriptor instead.
func (*HeartbeatPolicy) Descriptor() ([]byte, []int) {
	return file_cloud_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatPolicy) GetInterval() *durationpb.Duration {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *HeartbeatPolicy) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

// SignedEnvelope 使用 domain-separated Ed25519 签名保护确定性 Proto payload。
type SignedEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedEnvelope) Reset() {
	*x = SignedEnvelope{}
	mi := &file_cloud_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedEnvelope) ProtoMessage() {}

func (x *SignedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedEnvelope.ProtoReflect.Descriptor instead.
func (*SignedEnvelope) Descriptor() ([]byte, []int) {
	return file_cloud_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *SignedEnvelope) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *SignedEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// EdgeChallenge 是 Edge 在每条 Gateway stream 上先发的单次新鲜度证明材料。
// nonce 固定为 32 bytes，stream_id 由 Edge 为该 stream 唯一生成，期限固定为 10 秒。
type EdgeChallenge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	EdgeId        string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	EdgeBootId    string                 `protobuf:"bytes,3,opt,name=edge_boot_id,json=edgeBootId,proto3" json:"edge_boot_id,omitempty"`
	StreamId      string                 `protobuf:"bytes,4,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Target        EdgeChallengeTarget    `protobuf:"varint,7,opt,name=target,proto3,enum=anytty.cloud.v1.EdgeChallengeTarget" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeChallenge) Reset() {
	*x = EdgeChallenge{}
	mi := &file_cloud_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeChallenge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeChallenge) ProtoMessage() {}

func (x *EdgeChallenge) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeChallenge.ProtoReflect.Descriptor instead.
func (*EdgeChallenge) Descriptor() ([]byte, []int) {
	return file_cloud_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *EdgeChallenge) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EdgeChallenge) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *EdgeChallenge) GetEdgeBootId() string {
	if x != nil {
		return x.EdgeBootId
	}
	return ""
}

func (x *EdgeChallenge) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *EdgeChallenge) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *EdgeChallenge) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *EdgeChallenge) GetTarget() EdgeChallengeTarget {
	if x != nil {
		return x.Target
	}
	return EdgeChallengeTarget_EDGE_CHALLENGE_TARGET_UNSPECIFIED
}

var File_cloud_v1_common_proto protoreflect.FileDescriptor

const file_cloud_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x15cloud/v1/common.proto\x12\x0fanytty.cloud.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"e\n" +
	"\x0fVerificationKey\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\fR\tpublicKey\"\xd1\x01\n" +
	"\tKeyBundle\x12\x1a\n" +
	"\brevision\x18\x01 \x01(\x04R\brevision\x127\n" +
	"\tissued_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x124\n" +
	"\x04keys\x18\x04 \x03(\v2 .anytty.cloud.v1.VerificationKeyR\x04keys\"}\n" +
	"\x0fHeartbeatPolicy\x125\n" +
	"\binterval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\binterval\x123\n" +
	"\atimeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\atimeout\"_\n" +
	"\x0eSignedEnvelope\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\"\xaf\x02\n" +
	"\rEdgeChallenge\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12 \n" +
	"\fedge_boot_id\x18\x03 \x01(\tR\n" +
	"edgeBootId\x12\x1b\n" +
	"\tstream_id\x18\x04 \x01(\tR\bstreamId\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12<\n" +
	"\x06target\x18\a \x01(\x0e2$.anytty.cloud.v1.EdgeChallengeTargetR\x06target*\x8f\x01\n" +
	"\x13EdgeChallengeTarget\x12%\n" +
	"!EDGE_CHALLENGE_TARGET_UNSPECIFIED\x10\x00\x12'\n" +
	"#EDGE_CHALLENGE_TARGET_AGENT_GATEWAY\x10\x01\x12(\n" +
	"$EDGE_CHALLENGE_TARGET_CLIENT_GATEWAY\x10\x02B1Z/github.com/anytty/anytty/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_common_proto_rawDescOnce sync.Once
	file_cloud_v1_common_proto_rawDescData []byte
)

func file_cloud_v1_common_proto_rawDescGZIP() []byte {
	file_cloud_v1_common_proto_rawDescOnce.Do(func() {
		file_cloud_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_common_proto_rawDesc), len(file_cloud_v1_common_proto_rawDesc)))
	})
	return file_cloud_v1_common_proto_rawDescData
}

var file_cloud_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cloud_v1_common_proto_goTypes = []any{
	(EdgeChallengeTarget)(0),      // 0: anytty.cloud.v1.EdgeChallengeTarget
	(*VerificationKey)(nil),       // 1: anytty.cloud.v1.VerificationKey
	(*KeyBundle)(nil),             // 2: anytty.cloud.v1.KeyBundle
	(*HeartbeatPolicy)(nil),       // 3: anytty.cloud.v1.HeartbeatPolicy
	(*SignedEnvelope)(nil),        // 4: anytty.cloud.v1.SignedEnvelope
	(*EdgeChallenge)(nil),         // 5: anytty.cloud.v1.EdgeChallenge
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 7: google.protobuf.Duration
}
var file_cloud_v1_common_proto_depIdxs = []int32{
	6, // 0: anytty.cloud.v1.KeyBundle.issued_at:type_name -> google.protobuf.Timestamp
	6, // 1: anytty.cloud.v1.KeyBundle.expires_at:type_name -> google.protobuf.Timestamp
	1, // 2: anytty.cloud.v1.KeyBundle.keys:type_name -> anytty.cloud.v1.VerificationKey
	7, // 3: anytty.cloud.v1.HeartbeatPolicy.interval:type_name -> google.protobuf.Duration
	7, // 4: anytty.cloud.v1.HeartbeatPolicy.timeout:type_name -> google.protobuf.Duration
	6, // 5: anytty.cloud.v1.EdgeChallenge.issued_at:type_name -> google.protobuf.Timestamp
	6, // 6: anytty.cloud.v1.EdgeChallenge.expires_at:type_name -> google.protobuf.Timestamp
	0, // 7: anytty.cloud.v1.EdgeChallenge.target:type_name -> anytty.cloud.v1.EdgeChallengeTarget
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_cloud_v1_common_proto_init() }
func file_cloud_v1_common_proto_init() {
	if File_cloud_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_common_proto_rawDesc), len(file_cloud_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_v1_common_proto_goTypes,
		DependencyIndexes: file_cloud_v1_common_proto_depIdxs,
		EnumInfos:         file_cloud_v1_common_proto_enumTypes,
		MessageInfos:      file_cloud_v1_common_proto_msgTypes,
	}.Build()
	File_cloud_v1_common_proto = out.File
	file_cloud_v1_common_proto_goTypes = nil
	file_cloud_v1_common_proto_depIdxs = nil
}
