// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: cloud/v1/commerce.proto

package cloudv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CommerceService_ListPlans_FullMethodName              = "/muxvia.cloud.v1.CommerceService/ListPlans"
	CommerceService_CreatePlanVersion_FullMethodName      = "/muxvia.cloud.v1.CommerceService/CreatePlanVersion"
	CommerceService_PublishPlanVersion_FullMethodName     = "/muxvia.cloud.v1.CommerceService/PublishPlanVersion"
	CommerceService_CreateOrder_FullMethodName            = "/muxvia.cloud.v1.CommerceService/CreateOrder"
	CommerceService_ApplyPaymentEvent_FullMethodName      = "/muxvia.cloud.v1.CommerceService/ApplyPaymentEvent"
	CommerceService_TransitionSubscription_FullMethodName = "/muxvia.cloud.v1.CommerceService/TransitionSubscription"
	CommerceService_GetAccountCommerce_FullMethodName     = "/muxvia.cloud.v1.CommerceService/GetAccountCommerce"
)

// CommerceServiceClient is the client API for CommerceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CommerceService 拥有套餐、订单、支付、订阅和 Entitlement 状态机。
type CommerceServiceClient interface {
	ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (*ListPlansResponse, error)
	CreatePlanVersion(ctx context.Context, in *CreatePlanVersionRequest, opts ...grpc.CallOption) (*CreatePlanVersionResponse, error)
	PublishPlanVersion(ctx context.Context, in *PublishPlanVersionRequest, opts ...grpc.CallOption) (*PublishPlanVersionResponse, error)
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	ApplyPaymentEvent(ctx context.Context, in *ApplyPaymentEventRequest, opts ...grpc.CallOption) (*ApplyPaymentEventResponse, error)
	TransitionSubscription(ctx context.Context, in *TransitionSubscriptionRequest, opts ...grpc.CallOption) (*TransitionSubscriptionResponse, error)
	GetAccountCommerce(ctx context.Context, in *GetAccountCommerceRequest, opts ...grpc.CallOption) (*GetAccountCommerceResponse, error)
}

type commerceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCommerceServiceClient(cc grpc.ClientConnInterface) CommerceServiceClient {
	return &commerceServiceClient{cc}
}

func (c *commerceServiceClient) ListPlans(ctx context.Context, in *ListPlansRequest, opts ...grpc.CallOption) (*ListPlansResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPlansResponse)
	err := c.cc.Invoke(ctx, CommerceService_ListPlans_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commerceServiceClient) CreatePlanVersion(ctx context.Context, in *CreatePlanVersionRequest, opts ...grpc.CallOption) (*CreatePlanVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePlanVersionResponse)
	err := c.cc.Invoke(ctx, CommerceService_CreatePlanVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commerceServiceClient) PublishPlanVersion(ctx context.Context, in *PublishPlanVersionRequest, opts ...grpc.CallOption) (*PublishPlanVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishPlanVersionResponse)
	err := c.cc.Invoke(ctx, CommerceService_PublishPlanVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commerceServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, CommerceService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commerceServiceClient) ApplyPaymentEvent(ctx context.Context, in *ApplyPaymentEventRequest, opts ...grpc.CallOption) (*ApplyPaymentEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyPaymentEventResponse)
	err := c.cc.Invoke(ctx, CommerceService_ApplyPaymentEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commerceServiceClient) TransitionSubscription(ctx context.Context, in *TransitionSubscriptionRequest, opts ...grpc.CallOption) (*TransitionSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionSubscriptionResponse)
	err := c.cc.Invoke(ctx, CommerceService_TransitionSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commerceServiceClient) GetAccountCommerce(ctx context.Context, in *GetAccountCommerceRequest, opts ...grpc.CallOption) (*GetAccountCommerceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountCommerceResponse)
	err := c.cc.Invoke(ctx, CommerceService_GetAccountCommerce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommerceServiceServer is the server API for CommerceService service.
// All implementations must embed UnimplementedCommerceServiceServer
// for forward compatibility.
//
// CommerceService 拥有套餐、订单、支付、订阅和 Entitlement 状态机。
type CommerceServiceServer interface {
	ListPlans(context.Context, *ListPlansRequest) (*ListPlansResponse, error)
	CreatePlanVersion(context.Context, *CreatePlanVersionRequest) (*CreatePlanVersionResponse, error)
	PublishPlanVersion(context.Context, *PublishPlanVersionRequest) (*PublishPlanVersionResponse, error)
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	ApplyPaymentEvent(context.Context, *ApplyPaymentEventRequest) (*ApplyPaymentEventResponse, error)
	TransitionSubscription(context.Context, *TransitionSubscriptionRequest) (*TransitionSubscriptionResponse, error)
	GetAccountCommerce(context.Context, *GetAccountCommerceRequest) (*GetAccountCommerceResponse, error)
	mustEmbedUnimplementedCommerceServiceServer()
}

// UnimplementedCommerceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCommerceServiceServer struct{}

func (UnimplementedCommerceServiceServer) ListPlans(context.Context, *ListPlansRequest) (*ListPlansResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPlans not implemented")
}
func (UnimplementedCommerceServiceServer) CreatePlanVersion(context.Context, *CreatePlanVersionRequest) (*CreatePlanVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePlanVersion not implemented")
}
func (UnimplementedCommerceServiceServer) PublishPlanVersion(context.Context, *PublishPlanVersionRequest) (*PublishPlanVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishPlanVersion not implemented")
}
func (UnimplementedCommerceServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedCommerceServiceServer) ApplyPaymentEvent(context.Context, *ApplyPaymentEventRequest) (*ApplyPaymentEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyPaymentEvent not implemented")
}
func (UnimplementedCommerceServiceServer) TransitionSubscription(context.Context, *TransitionSubscriptionRequest) (*TransitionSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransitionSubscription not implemented")
}
func (UnimplementedCommerceServiceServer) GetAccountCommerce(context.Context, *GetAccountCommerceRequest) (*GetAccountCommerceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountCommerce not implemented")
}
func (UnimplementedCommerceServiceServer) mustEmbedUnimplementedCommerceServiceServer() {}
func (UnimplementedCommerceServiceServer) testEmbeddedByValue()                         {}

// UnsafeCommerceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommerceServiceServer will
// result in compilation errors.
type UnsafeCommerceServiceServer interface {
	mustEmbedUnimplementedCommerceServiceServer()
}

func RegisterCommerceServiceServer(s grpc.ServiceRegistrar, srv CommerceServiceServer) {
	// If the following call panics, it indicates UnimplementedCommerceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CommerceService_ServiceDesc, srv)
}

func _CommerceService_ListPlans_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPlansRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceServiceServer).ListPlans(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceService_ListPlans_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceServiceServer).ListPlans(ctx, req.(*ListPlansRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommerceService_CreatePlanVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePlanVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceServiceServer).CreatePlanVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceService_CreatePlanVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceServiceServer).CreatePlanVersion(ctx, req.(*CreatePlanVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommerceService_PublishPlanVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPlanVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceServiceServer).PublishPlanVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceService_PublishPlanVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceServiceServer).PublishPlanVersion(ctx, req.(*PublishPlanVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommerceService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommerceService_ApplyPaymentEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyPaymentEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceServiceServer).ApplyPaymentEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceService_ApplyPaymentEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceServiceServer).ApplyPaymentEvent(ctx, req.(*ApplyPaymentEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommerceService_TransitionSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceServiceServer).TransitionSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceService_TransitionSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceServiceServer).TransitionSubscription(ctx, req.(*TransitionSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommerceService_GetAccountCommerce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountCommerceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommerceServiceServer).GetAccountCommerce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CommerceService_GetAccountCommerce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommerceServiceServer).GetAccountCommerce(ctx, req.(*GetAccountCommerceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommerceService_ServiceDesc is the grpc.ServiceDesc for CommerceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommerceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxvia.cloud.v1.CommerceService",
	HandlerType: (*CommerceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPlans",
			Handler:    _CommerceService_ListPlans_Handler,
		},
		{
			MethodName: "CreatePlanVersion",
			Handler:    _CommerceService_CreatePlanVersion_Handler,
		},
		{
			MethodName: "PublishPlanVersion",
			Handler:    _CommerceService_PublishPlanVersion_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _CommerceService_CreateOrder_Handler,
		},
		{
			MethodName: "ApplyPaymentEvent",
			Handler:    _CommerceService_ApplyPaymentEvent_Handler,
		},
		{
			MethodName: "TransitionSubscription",
			Handler:    _CommerceService_TransitionSubscription_Handler,
		},
		{
			MethodName: "GetAccountCommerce",
			Handler:    _CommerceService_GetAccountCommerce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud/v1/commerce.proto",
}
