// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: cloud/v1/operator.proto

package cloudv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperatorService_GetOverview_FullMethodName                = "/anytty.cloud.v1.OperatorService/GetOverview"
	OperatorService_ListAccounts_FullMethodName               = "/anytty.cloud.v1.OperatorService/ListAccounts"
	OperatorService_GetAccount_FullMethodName                 = "/anytty.cloud.v1.OperatorService/GetAccount"
	OperatorService_ProvisionAccount_FullMethodName           = "/anytty.cloud.v1.OperatorService/ProvisionAccount"
	OperatorService_ResetAccountSetup_FullMethodName          = "/anytty.cloud.v1.OperatorService/ResetAccountSetup"
	OperatorService_ListRuntimeSessions_FullMethodName        = "/anytty.cloud.v1.OperatorService/ListRuntimeSessions"
	OperatorService_ListOrders_FullMethodName                 = "/anytty.cloud.v1.OperatorService/ListOrders"
	OperatorService_ListSubscriptions_FullMethodName          = "/anytty.cloud.v1.OperatorService/ListSubscriptions"
	OperatorService_ListUsage_FullMethodName                  = "/anytty.cloud.v1.OperatorService/ListUsage"
	OperatorService_ListAudit_FullMethodName                  = "/anytty.cloud.v1.OperatorService/ListAudit"
	OperatorService_SetAccountState_FullMethodName            = "/anytty.cloud.v1.OperatorService/SetAccountState"
	OperatorService_SetAccountRole_FullMethodName             = "/anytty.cloud.v1.OperatorService/SetAccountRole"
	OperatorService_DisconnectDaemon_FullMethodName           = "/anytty.cloud.v1.OperatorService/DisconnectDaemon"
	OperatorService_DisconnectSession_FullMethodName          = "/anytty.cloud.v1.OperatorService/DisconnectSession"
	OperatorService_DeleteEdge_FullMethodName                 = "/anytty.cloud.v1.OperatorService/DeleteEdge"
	OperatorService_ListCertificateProfiles_FullMethodName    = "/anytty.cloud.v1.OperatorService/ListCertificateProfiles"
	OperatorService_UploadCertificateProfile_FullMethodName   = "/anytty.cloud.v1.OperatorService/UploadCertificateProfile"
	OperatorService_BindCertificateProfile_FullMethodName     = "/anytty.cloud.v1.OperatorService/BindCertificateProfile"
	OperatorService_CreateEdgeIdentityRecovery_FullMethodName = "/anytty.cloud.v1.OperatorService/CreateEdgeIdentityRecovery"
)

// OperatorServiceClient is the client API for OperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OperatorService 是中文运营后台的唯一查询、持久 mutation 与实时控制 API。
type OperatorServiceClient interface {
	GetOverview(ctx context.Context, in *GetOperatorOverviewRequest, opts ...grpc.CallOption) (*GetOperatorOverviewResponse, error)
	ListAccounts(ctx context.Context, in *ListOperatorAccountsRequest, opts ...grpc.CallOption) (*ListOperatorAccountsResponse, error)
	GetAccount(ctx context.Context, in *GetOperatorAccountRequest, opts ...grpc.CallOption) (*GetOperatorAccountResponse, error)
	ProvisionAccount(ctx context.Context, in *ProvisionAccountRequest, opts ...grpc.CallOption) (*ProvisionAccountResponse, error)
	ResetAccountSetup(ctx context.Context, in *ResetAccountSetupRequest, opts ...grpc.CallOption) (*ResetAccountSetupResponse, error)
	ListRuntimeSessions(ctx context.Context, in *ListRuntimeSessionsRequest, opts ...grpc.CallOption) (*ListRuntimeSessionsResponse, error)
	ListOrders(ctx context.Context, in *ListOperatorOrdersRequest, opts ...grpc.CallOption) (*ListOperatorOrdersResponse, error)
	ListSubscriptions(ctx context.Context, in *ListOperatorSubscriptionsRequest, opts ...grpc.CallOption) (*ListOperatorSubscriptionsResponse, error)
	ListUsage(ctx context.Context, in *ListOperatorUsageRequest, opts ...grpc.CallOption) (*ListOperatorUsageResponse, error)
	ListAudit(ctx context.Context, in *ListOperatorAuditRequest, opts ...grpc.CallOption) (*ListOperatorAuditResponse, error)
	SetAccountState(ctx context.Context, in *SetAccountStateRequest, opts ...grpc.CallOption) (*SetAccountStateResponse, error)
	SetAccountRole(ctx context.Context, in *SetAccountRoleRequest, opts ...grpc.CallOption) (*SetAccountRoleResponse, error)
	DisconnectDaemon(ctx context.Context, in *DisconnectDaemonRequest, opts ...grpc.CallOption) (*DisconnectDaemonResponse, error)
	DisconnectSession(ctx context.Context, in *DisconnectSessionRequest, opts ...grpc.CallOption) (*DisconnectSessionResponse, error)
	DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteEdgeResponse, error)
	ListCertificateProfiles(ctx context.Context, in *ListCertificateProfilesRequest, opts ...grpc.CallOption) (*ListCertificateProfilesResponse, error)
	UploadCertificateProfile(ctx context.Context, in *UploadCertificateProfileRequest, opts ...grpc.CallOption) (*UploadCertificateProfileResponse, error)
	BindCertificateProfile(ctx context.Context, in *BindCertificateProfileRequest, opts ...grpc.CallOption) (*BindCertificateProfileResponse, error)
	CreateEdgeIdentityRecovery(ctx context.Context, in *CreateEdgeIdentityRecoveryRequest, opts ...grpc.CallOption) (*CreateEdgeIdentityRecoveryResponse, error)
}

type operatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorServiceClient(cc grpc.ClientConnInterface) OperatorServiceClient {
	return &operatorServiceClient{cc}
}

func (c *operatorServiceClient) GetOverview(ctx context.Context, in *GetOperatorOverviewRequest, opts ...grpc.CallOption) (*GetOperatorOverviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperatorOverviewResponse)
	err := c.cc.Invoke(ctx, OperatorService_GetOverview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListAccounts(ctx context.Context, in *ListOperatorAccountsRequest, opts ...grpc.CallOption) (*ListOperatorAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatorAccountsResponse)
	err := c.cc.Invoke(ctx, OperatorService_ListAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) GetAccount(ctx context.Context, in *GetOperatorAccountRequest, opts ...grpc.CallOption) (*GetOperatorAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperatorAccountResponse)
	err := c.cc.Invoke(ctx, OperatorService_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ProvisionAccount(ctx context.Context, in *ProvisionAccountRequest, opts ...grpc.CallOption) (*ProvisionAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProvisionAccountResponse)
	err := c.cc.Invoke(ctx, OperatorService_ProvisionAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ResetAccountSetup(ctx context.Context, in *ResetAccountSetupRequest, opts ...grpc.CallOption) (*ResetAccountSetupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetAccountSetupResponse)
	err := c.cc.Invoke(ctx, OperatorService_ResetAccountSetup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListRuntimeSessions(ctx context.Context, in *ListRuntimeSessionsRequest, opts ...grpc.CallOption) (*ListRuntimeSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimeSessionsResponse)
	err := c.cc.Invoke(ctx, OperatorService_ListRuntimeSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListOrders(ctx context.Context, in *ListOperatorOrdersRequest, opts ...grpc.CallOption) (*ListOperatorOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatorOrdersResponse)
	err := c.cc.Invoke(ctx, OperatorService_ListOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListSubscriptions(ctx context.Context, in *ListOperatorSubscriptionsRequest, opts ...grpc.CallOption) (*ListOperatorSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatorSubscriptionsResponse)
	err := c.cc.Invoke(ctx, OperatorService_ListSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListUsage(ctx context.Context, in *ListOperatorUsageRequest, opts ...grpc.CallOption) (*ListOperatorUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatorUsageResponse)
	err := c.cc.Invoke(ctx, OperatorService_ListUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListAudit(ctx context.Context, in *ListOperatorAuditRequest, opts ...grpc.CallOption) (*ListOperatorAuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOperatorAuditResponse)
	err := c.cc.Invoke(ctx, OperatorService_ListAudit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) SetAccountState(ctx context.Context, in *SetAccountStateRequest, opts ...grpc.CallOption) (*SetAccountStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAccountStateResponse)
	err := c.cc.Invoke(ctx, OperatorService_SetAccountState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) SetAccountRole(ctx context.Context, in *SetAccountRoleRequest, opts ...grpc.CallOption) (*SetAccountRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAccountRoleResponse)
	err := c.cc.Invoke(ctx, OperatorService_SetAccountRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) DisconnectDaemon(ctx context.Context, in *DisconnectDaemonRequest, opts ...grpc.CallOption) (*DisconnectDaemonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectDaemonResponse)
	err := c.cc.Invoke(ctx, OperatorService_DisconnectDaemon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) DisconnectSession(ctx context.Context, in *DisconnectSessionRequest, opts ...grpc.CallOption) (*DisconnectSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectSessionResponse)
	err := c.cc.Invoke(ctx, OperatorService_DisconnectSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) DeleteEdge(ctx context.Context, in *DeleteEdgeRequest, opts ...grpc.CallOption) (*DeleteEdgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEdgeResponse)
	err := c.cc.Invoke(ctx, OperatorService_DeleteEdge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListCertificateProfiles(ctx context.Context, in *ListCertificateProfilesRequest, opts ...grpc.CallOption) (*ListCertificateProfilesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCertificateProfilesResponse)
	err := c.cc.Invoke(ctx, OperatorService_ListCertificateProfiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) UploadCertificateProfile(ctx context.Context, in *UploadCertificateProfileRequest, opts ...grpc.CallOption) (*UploadCertificateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadCertificateProfileResponse)
	err := c.cc.Invoke(ctx, OperatorService_UploadCertificateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) BindCertificateProfile(ctx context.Context, in *BindCertificateProfileRequest, opts ...grpc.CallOption) (*BindCertificateProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindCertificateProfileResponse)
	err := c.cc.Invoke(ctx, OperatorService_BindCertificateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) CreateEdgeIdentityRecovery(ctx context.Context, in *CreateEdgeIdentityRecoveryRequest, opts ...grpc.CallOption) (*CreateEdgeIdentityRecoveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEdgeIdentityRecoveryResponse)
	err := c.cc.Invoke(ctx, OperatorService_CreateEdgeIdentityRecovery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorServiceServer is the server API for OperatorService service.
// All implementations must embed UnimplementedOperatorServiceServer
// for forward compatibility.
//
// OperatorService 是中文运营后台的唯一查询、持久 mutation 与实时控制 API。
type OperatorServiceServer interface {
	GetOverview(context.Context, *GetOperatorOverviewRequest) (*GetOperatorOverviewResponse, error)
	ListAccounts(context.Context, *ListOperatorAccountsRequest) (*ListOperatorAccountsResponse, error)
	GetAccount(context.Context, *GetOperatorAccountRequest) (*GetOperatorAccountResponse, error)
	ProvisionAccount(context.Context, *ProvisionAccountRequest) (*ProvisionAccountResponse, error)
	ResetAccountSetup(context.Context, *ResetAccountSetupRequest) (*ResetAccountSetupResponse, error)
	ListRuntimeSessions(context.Context, *ListRuntimeSessionsRequest) (*ListRuntimeSessionsResponse, error)
	ListOrders(context.Context, *ListOperatorOrdersRequest) (*ListOperatorOrdersResponse, error)
	ListSubscriptions(context.Context, *ListOperatorSubscriptionsRequest) (*ListOperatorSubscriptionsResponse, error)
	ListUsage(context.Context, *ListOperatorUsageRequest) (*ListOperatorUsageResponse, error)
	ListAudit(context.Context, *ListOperatorAuditRequest) (*ListOperatorAuditResponse, error)
	SetAccountState(context.Context, *SetAccountStateRequest) (*SetAccountStateResponse, error)
	SetAccountRole(context.Context, *SetAccountRoleRequest) (*SetAccountRoleResponse, error)
	DisconnectDaemon(context.Context, *DisconnectDaemonRequest) (*DisconnectDaemonResponse, error)
	DisconnectSession(context.Context, *DisconnectSessionRequest) (*DisconnectSessionResponse, error)
	DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error)
	ListCertificateProfiles(context.Context, *ListCertificateProfilesRequest) (*ListCertificateProfilesResponse, error)
	UploadCertificateProfile(context.Context, *UploadCertificateProfileRequest) (*UploadCertificateProfileResponse, error)
	BindCertificateProfile(context.Context, *BindCertificateProfileRequest) (*BindCertificateProfileResponse, error)
	CreateEdgeIdentityRecovery(context.Context, *CreateEdgeIdentityRecoveryRequest) (*CreateEdgeIdentityRecoveryResponse, error)
	mustEmbedUnimplementedOperatorServiceServer()
}

// UnimplementedOperatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorServiceServer struct{}

func (UnimplementedOperatorServiceServer) GetOverview(context.Context, *GetOperatorOverviewRequest) (*GetOperatorOverviewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOverview not implemented")
}
func (UnimplementedOperatorServiceServer) ListAccounts(context.Context, *ListOperatorAccountsRequest) (*ListOperatorAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedOperatorServiceServer) GetAccount(context.Context, *GetOperatorAccountRequest) (*GetOperatorAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedOperatorServiceServer) ProvisionAccount(context.Context, *ProvisionAccountRequest) (*ProvisionAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProvisionAccount not implemented")
}
func (UnimplementedOperatorServiceServer) ResetAccountSetup(context.Context, *ResetAccountSetupRequest) (*ResetAccountSetupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetAccountSetup not implemented")
}
func (UnimplementedOperatorServiceServer) ListRuntimeSessions(context.Context, *ListRuntimeSessionsRequest) (*ListRuntimeSessionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuntimeSessions not implemented")
}
func (UnimplementedOperatorServiceServer) ListOrders(context.Context, *ListOperatorOrdersRequest) (*ListOperatorOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListOrders not implemented")
}
func (UnimplementedOperatorServiceServer) ListSubscriptions(context.Context, *ListOperatorSubscriptionsRequest) (*ListOperatorSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (UnimplementedOperatorServiceServer) ListUsage(context.Context, *ListOperatorUsageRequest) (*ListOperatorUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUsage not implemented")
}
func (UnimplementedOperatorServiceServer) ListAudit(context.Context, *ListOperatorAuditRequest) (*ListOperatorAuditResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudit not implemented")
}
func (UnimplementedOperatorServiceServer) SetAccountState(context.Context, *SetAccountStateRequest) (*SetAccountStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAccountState not implemented")
}
func (UnimplementedOperatorServiceServer) SetAccountRole(context.Context, *SetAccountRoleRequest) (*SetAccountRoleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAccountRole not implemented")
}
func (UnimplementedOperatorServiceServer) DisconnectDaemon(context.Context, *DisconnectDaemonRequest) (*DisconnectDaemonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectDaemon not implemented")
}
func (UnimplementedOperatorServiceServer) DisconnectSession(context.Context, *DisconnectSessionRequest) (*DisconnectSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectSession not implemented")
}
func (UnimplementedOperatorServiceServer) DeleteEdge(context.Context, *DeleteEdgeRequest) (*DeleteEdgeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEdge not implemented")
}
func (UnimplementedOperatorServiceServer) ListCertificateProfiles(context.Context, *ListCertificateProfilesRequest) (*ListCertificateProfilesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCertificateProfiles not implemented")
}
func (UnimplementedOperatorServiceServer) UploadCertificateProfile(context.Context, *UploadCertificateProfileRequest) (*UploadCertificateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadCertificateProfile not implemented")
}
func (UnimplementedOperatorServiceServer) BindCertificateProfile(context.Context, *BindCertificateProfileRequest) (*BindCertificateProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindCertificateProfile not implemented")
}
func (UnimplementedOperatorServiceServer) CreateEdgeIdentityRecovery(context.Context, *CreateEdgeIdentityRecoveryRequest) (*CreateEdgeIdentityRecoveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEdgeIdentityRecovery not implemented")
}
func (UnimplementedOperatorServiceServer) mustEmbedUnimplementedOperatorServiceServer() {}
func (UnimplementedOperatorServiceServer) testEmbeddedByValue()                         {}

// UnsafeOperatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorServiceServer will
// result in compilation errors.
type UnsafeOperatorServiceServer interface {
	mustEmbedUnimplementedOperatorServiceServer()
}

func RegisterOperatorServiceServer(s grpc.ServiceRegistrar, srv OperatorServiceServer) {
	// If the following call panics, it indicates UnimplementedOperatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorService_ServiceDesc, srv)
}

func _OperatorService_GetOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperatorOverviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).GetOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_GetOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).GetOverview(ctx, req.(*GetOperatorOverviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListAccounts(ctx, req.(*ListOperatorAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperatorAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).GetAccount(ctx, req.(*GetOperatorAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ProvisionAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProvisionAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ProvisionAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ProvisionAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ProvisionAccount(ctx, req.(*ProvisionAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ResetAccountSetup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetAccountSetupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ResetAccountSetup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ResetAccountSetup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ResetAccountSetup(ctx, req.(*ResetAccountSetupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListRuntimeSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimeSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListRuntimeSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListRuntimeSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListRuntimeSessions(ctx, req.(*ListRuntimeSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListOrders(ctx, req.(*ListOperatorOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListSubscriptions(ctx, req.(*ListOperatorSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListUsage(ctx, req.(*ListOperatorUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListAudit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorAuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListAudit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListAudit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListAudit(ctx, req.(*ListOperatorAuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_SetAccountState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccountStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).SetAccountState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_SetAccountState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).SetAccountState(ctx, req.(*SetAccountStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_SetAccountRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAccountRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).SetAccountRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_SetAccountRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).SetAccountRole(ctx, req.(*SetAccountRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_DisconnectDaemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectDaemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).DisconnectDaemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_DisconnectDaemon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).DisconnectDaemon(ctx, req.(*DisconnectDaemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_DisconnectSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).DisconnectSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_DisconnectSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).DisconnectSession(ctx, req.(*DisconnectSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEdgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_DeleteEdge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).DeleteEdge(ctx, req.(*DeleteEdgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListCertificateProfiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCertificateProfilesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListCertificateProfiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListCertificateProfiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListCertificateProfiles(ctx, req.(*ListCertificateProfilesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_UploadCertificateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadCertificateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).UploadCertificateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_UploadCertificateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).UploadCertificateProfile(ctx, req.(*UploadCertificateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_BindCertificateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindCertificateProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).BindCertificateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_BindCertificateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).BindCertificateProfile(ctx, req.(*BindCertificateProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_CreateEdgeIdentityRecovery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEdgeIdentityRecoveryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).CreateEdgeIdentityRecovery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_CreateEdgeIdentityRecovery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).CreateEdgeIdentityRecovery(ctx, req.(*CreateEdgeIdentityRecoveryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OperatorService_ServiceDesc is the grpc.ServiceDesc for OperatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anytty.cloud.v1.OperatorService",
	HandlerType: (*OperatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOverview",
			Handler:    _OperatorService_GetOverview_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _OperatorService_ListAccounts_Handler,
		},
		{
			MethodName: "GetAccount",
			Handler:    _OperatorService_GetAccount_Handler,
		},
		{
			MethodName: "ProvisionAccount",
			Handler:    _OperatorService_ProvisionAccount_Handler,
		},
		{
			MethodName: "ResetAccountSetup",
			Handler:    _OperatorService_ResetAccountSetup_Handler,
		},
		{
			MethodName: "ListRuntimeSessions",
			Handler:    _OperatorService_ListRuntimeSessions_Handler,
		},
		{
			MethodName: "ListOrders",
			Handler:    _OperatorService_ListOrders_Handler,
		},
		{
			MethodName: "ListSubscriptions",
			Handler:    _OperatorService_ListSubscriptions_Handler,
		},
		{
			MethodName: "ListUsage",
			Handler:    _OperatorService_ListUsage_Handler,
		},
		{
			MethodName: "ListAudit",
			Handler:    _OperatorService_ListAudit_Handler,
		},
		{
			MethodName: "SetAccountState",
			Handler:    _OperatorService_SetAccountState_Handler,
		},
		{
			MethodName: "SetAccountRole",
			Handler:    _OperatorService_SetAccountRole_Handler,
		},
		{
			MethodName: "DisconnectDaemon",
			Handler:    _OperatorService_DisconnectDaemon_Handler,
		},
		{
			MethodName: "DisconnectSession",
			Handler:    _OperatorService_DisconnectSession_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _OperatorService_DeleteEdge_Handler,
		},
		{
			MethodName: "ListCertificateProfiles",
			Handler:    _OperatorService_ListCertificateProfiles_Handler,
		},
		{
			MethodName: "UploadCertificateProfile",
			Handler:    _OperatorService_UploadCertificateProfile_Handler,
		},
		{
			MethodName: "BindCertificateProfile",
			Handler:    _OperatorService_BindCertificateProfile_Handler,
		},
		{
			MethodName: "CreateEdgeIdentityRecovery",
			Handler:    _OperatorService_CreateEdgeIdentityRecovery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cloud/v1/operator.proto",
}
