// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cloud/v1/ticket.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentCapability 是 AgentTicket 冻结的 Edge 侧准入能力，不表达 terminal 权限。
type AgentCapability int32

const (
	AgentCapability_AGENT_CAPABILITY_UNSPECIFIED AgentCapability = 0
	AgentCapability_AGENT_CAPABILITY_SIGNALING   AgentCapability = 1
)

// Enum value maps for AgentCapability.
var (
	AgentCapability_name = map[int32]string{
		0: "AGENT_CAPABILITY_UNSPECIFIED",
		1: "AGENT_CAPABILITY_SIGNALING",
	}
	AgentCapability_value = map[string]int32{
		"AGENT_CAPABILITY_UNSPECIFIED": 0,
		"AGENT_CAPABILITY_SIGNALING":   1,
	}
)

func (x AgentCapability) Enum() *AgentCapability {
	p := new(AgentCapability)
	*p = x
	return p
}

func (x AgentCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_ticket_proto_enumTypes[0].Descriptor()
}

func (AgentCapability) Type() protoreflect.EnumType {
	return &file_cloud_v1_ticket_proto_enumTypes[0]
}

func (x AgentCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentCapability.Descriptor instead.
func (AgentCapability) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{0}
}

// AgentRelayDelegation 是 Controller 在 daemon 接入时冻结给 Edge 的 Relay 上限。
// EdgeControl 中断后，Edge 只能在这些上限内为已由 daemon 批准的客户端创建短租约。
type AgentRelayDelegation struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	MaxBytesPerLease         uint64                 `protobuf:"varint,1,opt,name=max_bytes_per_lease,json=maxBytesPerLease,proto3" json:"max_bytes_per_lease,omitempty"`
	MaxRateBytesPerSecond    uint64                 `protobuf:"varint,2,opt,name=max_rate_bytes_per_second,json=maxRateBytesPerSecond,proto3" json:"max_rate_bytes_per_second,omitempty"`
	MaxConcurrentAllocations uint32                 `protobuf:"varint,3,opt,name=max_concurrent_allocations,json=maxConcurrentAllocations,proto3" json:"max_concurrent_allocations,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AgentRelayDelegation) Reset() {
	*x = AgentRelayDelegation{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentRelayDelegation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentRelayDelegation) ProtoMessage() {}

func (x *AgentRelayDelegation) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentRelayDelegation.ProtoReflect.Descriptor instead.
func (*AgentRelayDelegation) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *AgentRelayDelegation) GetMaxBytesPerLease() uint64 {
	if x != nil {
		return x.MaxBytesPerLease
	}
	return 0
}

func (x *AgentRelayDelegation) GetMaxRateBytesPerSecond() uint64 {
	if x != nil {
		return x.MaxRateBytesPerSecond
	}
	return 0
}

func (x *AgentRelayDelegation) GetMaxConcurrentAllocations() uint32 {
	if x != nil {
		return x.MaxConcurrentAllocations
	}
	return 0
}

// AgentTicketClaims 把一次 daemon 到 Edge 的连接绑定到持久身份和短有效期。
type AgentTicketClaims struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TicketId        string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	DaemonId        string                 `protobuf:"bytes,2,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	AccountId       string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	EdgeId          string                 `protobuf:"bytes,4,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	DeviceId        string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DevicePublicKey []byte                 `protobuf:"bytes,6,opt,name=device_public_key,json=devicePublicKey,proto3" json:"device_public_key,omitempty"`
	Capabilities    []AgentCapability      `protobuf:"varint,7,rep,packed,name=capabilities,proto3,enum=anytty.cloud.v1.AgentCapability" json:"capabilities,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	RelayDelegation *AgentRelayDelegation  `protobuf:"bytes,10,opt,name=relay_delegation,json=relayDelegation,proto3" json:"relay_delegation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentTicketClaims) Reset() {
	*x = AgentTicketClaims{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentTicketClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentTicketClaims) ProtoMessage() {}

func (x *AgentTicketClaims) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentTicketClaims.ProtoReflect.Descriptor instead.
func (*AgentTicketClaims) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *AgentTicketClaims) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *AgentTicketClaims) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *AgentTicketClaims) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AgentTicketClaims) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *AgentTicketClaims) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AgentTicketClaims) GetDevicePublicKey() []byte {
	if x != nil {
		return x.DevicePublicKey
	}
	return nil
}

func (x *AgentTicketClaims) GetCapabilities() []AgentCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *AgentTicketClaims) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *AgentTicketClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AgentTicketClaims) GetRelayDelegation() *AgentRelayDelegation {
	if x != nil {
		return x.RelayDelegation
	}
	return nil
}

// AgentHelloProofInput 把 DeviceIdentity proof 绑定到票据和当前 stream generation。
type AgentHelloProofInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TicketPayloadSha256 []byte                 `protobuf:"bytes,1,opt,name=ticket_payload_sha256,json=ticketPayloadSha256,proto3" json:"ticket_payload_sha256,omitempty"`
	DaemonId            string                 `protobuf:"bytes,2,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	BootId              string                 `protobuf:"bytes,3,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId        string                 `protobuf:"bytes,4,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AgentHelloProofInput) Reset() {
	*x = AgentHelloProofInput{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHelloProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHelloProofInput) ProtoMessage() {}

func (x *AgentHelloProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHelloProofInput.ProtoReflect.Descriptor instead.
func (*AgentHelloProofInput) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *AgentHelloProofInput) GetTicketPayloadSha256() []byte {
	if x != nil {
		return x.TicketPayloadSha256
	}
	return nil
}

func (x *AgentHelloProofInput) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *AgentHelloProofInput) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *AgentHelloProofInput) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

// CloudRouteGrantClaims 由 owning daemon 的 DeviceIdentity 签发，只授权发现和信令。
// 该消息不得出现 terminal、scope、CapabilityGrant、命令或文件字段。
type CloudRouteGrantClaims struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GrantId         string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	DaemonId        string                 `protobuf:"bytes,2,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	ClientPublicKey []byte                 `protobuf:"bytes,3,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	Product         ClientProduct          `protobuf:"varint,4,opt,name=product,proto3,enum=anytty.cloud.v1.ClientProduct" json:"product,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloudRouteGrantClaims) Reset() {
	*x = CloudRouteGrantClaims{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudRouteGrantClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudRouteGrantClaims) ProtoMessage() {}

func (x *CloudRouteGrantClaims) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudRouteGrantClaims.ProtoReflect.Descriptor instead.
func (*CloudRouteGrantClaims) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *CloudRouteGrantClaims) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *CloudRouteGrantClaims) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *CloudRouteGrantClaims) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *CloudRouteGrantClaims) GetProduct() ClientProduct {
	if x != nil {
		return x.Product
	}
	return ClientProduct_CLIENT_PRODUCT_UNSPECIFIED
}

func (x *CloudRouteGrantClaims) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *CloudRouteGrantClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// PairingRouteGrantClaims 由 owning daemon 签发，只允许 Cloud 为一个活动 claim 建立 pairing-only signaling。
// pairing_claim_sha256 不足以兑换 claim，Cloud 不接收 128-bit claim 本体。
type PairingRouteGrantClaims struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GrantId            string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	DaemonId           string                 `protobuf:"bytes,2,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	DeviceId           string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	PairingClaimSha256 []byte                 `protobuf:"bytes,4,opt,name=pairing_claim_sha256,json=pairingClaimSha256,proto3" json:"pairing_claim_sha256,omitempty"`
	IssuedAt           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PairingRouteGrantClaims) Reset() {
	*x = PairingRouteGrantClaims{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRouteGrantClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRouteGrantClaims) ProtoMessage() {}

func (x *PairingRouteGrantClaims) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRouteGrantClaims.ProtoReflect.Descriptor instead.
func (*PairingRouteGrantClaims) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *PairingRouteGrantClaims) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *PairingRouteGrantClaims) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *PairingRouteGrantClaims) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PairingRouteGrantClaims) GetPairingClaimSha256() []byte {
	if x != nil {
		return x.PairingClaimSha256
	}
	return nil
}

func (x *PairingRouteGrantClaims) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *PairingRouteGrantClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ClientRouteProofInput 把客户端 proof 绑定到 Controller nonce、grant 和本次解析请求。
type ClientRouteProofInput struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId        string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Challenge          []byte                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	GrantPayloadSha256 []byte                 `protobuf:"bytes,3,opt,name=grant_payload_sha256,json=grantPayloadSha256,proto3" json:"grant_payload_sha256,omitempty"`
	RequestId          string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientRouteProofInput) Reset() {
	*x = ClientRouteProofInput{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRouteProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRouteProofInput) ProtoMessage() {}

func (x *ClientRouteProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRouteProofInput.ProtoReflect.Descriptor instead.
func (*ClientRouteProofInput) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{5}
}

func (x *ClientRouteProofInput) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ClientRouteProofInput) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *ClientRouteProofInput) GetGrantPayloadSha256() []byte {
	if x != nil {
		return x.GrantPayloadSha256
	}
	return nil
}

func (x *ClientRouteProofInput) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// PairingRouteProofInput 证明首次配对请求持有即将绑定到 claim 的 ClientAccessIdentity。
// Controller 只看到 daemon 签名 bootstrap grant 的摘要；真正的 claim 仍只在端到端 DataChannel 内由 daemon 消费。
type PairingRouteProofInput struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId                    string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Challenge                      []byte                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	PairingRouteGrantPayloadSha256 []byte                 `protobuf:"bytes,3,opt,name=pairing_route_grant_payload_sha256,json=pairingRouteGrantPayloadSha256,proto3" json:"pairing_route_grant_payload_sha256,omitempty"`
	RequestId                      string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *PairingRouteProofInput) Reset() {
	*x = PairingRouteProofInput{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingRouteProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingRouteProofInput) ProtoMessage() {}

func (x *PairingRouteProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingRouteProofInput.ProtoReflect.Descriptor instead.
func (*PairingRouteProofInput) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{6}
}

func (x *PairingRouteProofInput) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *PairingRouteProofInput) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *PairingRouteProofInput) GetPairingRouteGrantPayloadSha256() []byte {
	if x != nil {
		return x.PairingRouteGrantPayloadSha256
	}
	return nil
}

func (x *PairingRouteProofInput) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// CloudRouteHelloProofInput 把 daemon 签名的长期 Route grant 绑定到当前 Edge 和单次 stream generation。
// grant 可复用，但每次连接都必须由同一 ClientAccessIdentity 重新签名，复制 grant 本身不能建立连接。
type CloudRouteHelloProofInput struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	RouteGrantPayloadSha256 []byte                 `protobuf:"bytes,1,opt,name=route_grant_payload_sha256,json=routeGrantPayloadSha256,proto3" json:"route_grant_payload_sha256,omitempty"`
	EdgeId                  string                 `protobuf:"bytes,2,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	SessionId               string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AttemptGeneration       uint64                 `protobuf:"varint,4,opt,name=attempt_generation,json=attemptGeneration,proto3" json:"attempt_generation,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CloudRouteHelloProofInput) Reset() {
	*x = CloudRouteHelloProofInput{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudRouteHelloProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudRouteHelloProofInput) ProtoMessage() {}

func (x *CloudRouteHelloProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudRouteHelloProofInput.ProtoReflect.Descriptor instead.
func (*CloudRouteHelloProofInput) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{7}
}

func (x *CloudRouteHelloProofInput) GetRouteGrantPayloadSha256() []byte {
	if x != nil {
		return x.RouteGrantPayloadSha256
	}
	return nil
}

func (x *CloudRouteHelloProofInput) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *CloudRouteHelloProofInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CloudRouteHelloProofInput) GetAttemptGeneration() uint64 {
	if x != nil {
		return x.AttemptGeneration
	}
	return 0
}

var File_cloud_v1_ticket_proto protoreflect.FileDescriptor

const file_cloud_v1_ticket_proto_rawDesc = "" +
	"\n" +
	"\x15cloud/v1/ticket.proto\x12\x0fanytty.cloud.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16cloud/v1/runtime.proto\"\xbd\x01\n" +
	"\x14AgentRelayDelegation\x12-\n" +
	"\x13max_bytes_per_lease\x18\x01 \x01(\x04R\x10maxBytesPerLease\x128\n" +
	"\x19max_rate_bytes_per_second\x18\x02 \x01(\x04R\x15maxRateBytesPerSecond\x12<\n" +
	"\x1amax_concurrent_allocations\x18\x03 \x01(\rR\x18maxConcurrentAllocations\"\xda\x03\n" +
	"\x11AgentTicketClaims\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12\x1b\n" +
	"\tdaemon_id\x18\x02 \x01(\tR\bdaemonId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x17\n" +
	"\aedge_id\x18\x04 \x01(\tR\x06edgeId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12*\n" +
	"\x11device_public_key\x18\x06 \x01(\fR\x0fdevicePublicKey\x12D\n" +
	"\fcapabilities\x18\a \x03(\x0e2 .anytty.cloud.v1.AgentCapabilityR\fcapabilities\x127\n" +
	"\tissued_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12P\n" +
	"\x10relay_delegation\x18\n" +
	" \x01(\v2%.anytty.cloud.v1.AgentRelayDelegationR\x0frelayDelegation\"\xa5\x01\n" +
	"\x14AgentHelloProofInput\x122\n" +
	"\x15ticket_payload_sha256\x18\x01 \x01(\fR\x13ticketPayloadSha256\x12\x1b\n" +
	"\tdaemon_id\x18\x02 \x01(\tR\bdaemonId\x12\x17\n" +
	"\aboot_id\x18\x03 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x04 \x01(\tR\fconnectionId\"\xa9\x02\n" +
	"\x15CloudRouteGrantClaims\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x1b\n" +
	"\tdaemon_id\x18\x02 \x01(\tR\bdaemonId\x12*\n" +
	"\x11client_public_key\x18\x03 \x01(\fR\x0fclientPublicKey\x128\n" +
	"\aproduct\x18\x04 \x01(\x0e2\x1e.anytty.cloud.v1.ClientProductR\aproduct\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x94\x02\n" +
	"\x17PairingRouteGrantClaims\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x1b\n" +
	"\tdaemon_id\x18\x02 \x01(\tR\bdaemonId\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x120\n" +
	"\x14pairing_claim_sha256\x18\x04 \x01(\fR\x12pairingClaimSha256\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa9\x01\n" +
	"\x15ClientRouteProofInput\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\fR\tchallenge\x120\n" +
	"\x14grant_payload_sha256\x18\x03 \x01(\fR\x12grantPayloadSha256\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xc4\x01\n" +
	"\x16PairingRouteProofInput\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\fR\tchallenge\x12J\n" +
	"\"pairing_route_grant_payload_sha256\x18\x03 \x01(\fR\x1epairingRouteGrantPayloadSha256\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xbf\x01\n" +
	"\x19CloudRouteHelloProofInput\x12;\n" +
	"\x1aroute_grant_payload_sha256\x18\x01 \x01(\fR\x17routeGrantPayloadSha256\x12\x17\n" +
	"\aedge_id\x18\x02 \x01(\tR\x06edgeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12-\n" +
	"\x12attempt_generation\x18\x04 \x01(\x04R\x11attemptGeneration*S\n" +
	"\x0fAgentCapability\x12 \n" +
	"\x1cAGENT_CAPABILITY_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aAGENT_CAPABILITY_SIGNALING\x10\x01B1Z/github.com/anytty/anytty/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_ticket_proto_rawDescOnce sync.Once
	file_cloud_v1_ticket_proto_rawDescData []byte
)

func file_cloud_v1_ticket_proto_rawDescGZIP() []byte {
	file_cloud_v1_ticket_proto_rawDescOnce.Do(func() {
		file_cloud_v1_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_ticket_proto_rawDesc), len(file_cloud_v1_ticket_proto_rawDesc)))
	})
	return file_cloud_v1_ticket_proto_rawDescData
}

var file_cloud_v1_ticket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_v1_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cloud_v1_ticket_proto_goTypes = []any{
	(AgentCapability)(0),              // 0: anytty.cloud.v1.AgentCapability
	(*AgentRelayDelegation)(nil),      // 1: anytty.cloud.v1.AgentRelayDelegation
	(*AgentTicketClaims)(nil),         // 2: anytty.cloud.v1.AgentTicketClaims
	(*AgentHelloProofInput)(nil),      // 3: anytty.cloud.v1.AgentHelloProofInput
	(*CloudRouteGrantClaims)(nil),     // 4: anytty.cloud.v1.CloudRouteGrantClaims
	(*PairingRouteGrantClaims)(nil),   // 5: anytty.cloud.v1.PairingRouteGrantClaims
	(*ClientRouteProofInput)(nil),     // 6: anytty.cloud.v1.ClientRouteProofInput
	(*PairingRouteProofInput)(nil),    // 7: anytty.cloud.v1.PairingRouteProofInput
	(*CloudRouteHelloProofInput)(nil), // 8: anytty.cloud.v1.CloudRouteHelloProofInput
	(*timestamppb.Timestamp)(nil),     // 9: google.protobuf.Timestamp
	(ClientProduct)(0),                // 10: anytty.cloud.v1.ClientProduct
}
var file_cloud_v1_ticket_proto_depIdxs = []int32{
	0,  // 0: anytty.cloud.v1.AgentTicketClaims.capabilities:type_name -> anytty.cloud.v1.AgentCapability
	9,  // 1: anytty.cloud.v1.AgentTicketClaims.issued_at:type_name -> google.protobuf.Timestamp
	9,  // 2: anytty.cloud.v1.AgentTicketClaims.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 3: anytty.cloud.v1.AgentTicketClaims.relay_delegation:type_name -> anytty.cloud.v1.AgentRelayDelegation
	10, // 4: anytty.cloud.v1.CloudRouteGrantClaims.product:type_name -> anytty.cloud.v1.ClientProduct
	9,  // 5: anytty.cloud.v1.CloudRouteGrantClaims.issued_at:type_name -> google.protobuf.Timestamp
	9,  // 6: anytty.cloud.v1.CloudRouteGrantClaims.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 7: anytty.cloud.v1.PairingRouteGrantClaims.issued_at:type_name -> google.protobuf.Timestamp
	9,  // 8: anytty.cloud.v1.PairingRouteGrantClaims.expires_at:type_name -> google.protobuf.Timestamp
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_cloud_v1_ticket_proto_init() }
func file_cloud_v1_ticket_proto_init() {
	if File_cloud_v1_ticket_proto != nil {
		return
	}
	file_cloud_v1_runtime_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_ticket_proto_rawDesc), len(file_cloud_v1_ticket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_v1_ticket_proto_goTypes,
		DependencyIndexes: file_cloud_v1_ticket_proto_depIdxs,
		EnumInfos:         file_cloud_v1_ticket_proto_enumTypes,
		MessageInfos:      file_cloud_v1_ticket_proto_msgTypes,
	}.Build()
	File_cloud_v1_ticket_proto = out.File
	file_cloud_v1_ticket_proto_goTypes = nil
	file_cloud_v1_ticket_proto_depIdxs = nil
}
