// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: cloud/v1/ticket.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DaemonCapability 是 enrollment 时授予 daemon 的 Edge 侧能力，不表达 terminal 权限。
type DaemonCapability int32

const (
	DaemonCapability_DAEMON_CAPABILITY_UNSPECIFIED DaemonCapability = 0
	DaemonCapability_DAEMON_CAPABILITY_SIGNALING   DaemonCapability = 1
)

// Enum value maps for DaemonCapability.
var (
	DaemonCapability_name = map[int32]string{
		0: "DAEMON_CAPABILITY_UNSPECIFIED",
		1: "DAEMON_CAPABILITY_SIGNALING",
	}
	DaemonCapability_value = map[string]int32{
		"DAEMON_CAPABILITY_UNSPECIFIED": 0,
		"DAEMON_CAPABILITY_SIGNALING":   1,
	}
)

func (x DaemonCapability) Enum() *DaemonCapability {
	p := new(DaemonCapability)
	*p = x
	return p
}

func (x DaemonCapability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DaemonCapability) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_ticket_proto_enumTypes[0].Descriptor()
}

func (DaemonCapability) Type() protoreflect.EnumType {
	return &file_cloud_v1_ticket_proto_enumTypes[0]
}

func (x DaemonCapability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DaemonCapability.Descriptor instead.
func (DaemonCapability) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{0}
}

// DaemonBindingClaims 是 enrollment 的持久结果。它只绑定 daemon 身份和目标 Edge，
// 不是 bearer token；每次 AgentGateway 连接仍必须证明 DeviceIdentity 私钥持有权。
type DaemonBindingClaims struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BindingId         string                 `protobuf:"bytes,1,opt,name=binding_id,json=bindingId,proto3" json:"binding_id,omitempty"`
	DaemonId          string                 `protobuf:"bytes,2,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	AccountId         string                 `protobuf:"bytes,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	EdgeId            string                 `protobuf:"bytes,4,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	DeviceId          string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DevicePublicKey   []byte                 `protobuf:"bytes,6,opt,name=device_public_key,json=devicePublicKey,proto3" json:"device_public_key,omitempty"`
	Capabilities      []DaemonCapability     `protobuf:"varint,7,rep,packed,name=capabilities,proto3,enum=anytty.cloud.v1.DaemonCapability" json:"capabilities,omitempty"`
	IssuedAt          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	EdgeLocatorSha256 []byte                 `protobuf:"bytes,12,opt,name=edge_locator_sha256,json=edgeLocatorSha256,proto3" json:"edge_locator_sha256,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DaemonBindingClaims) Reset() {
	*x = DaemonBindingClaims{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonBindingClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonBindingClaims) ProtoMessage() {}

func (x *DaemonBindingClaims) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonBindingClaims.ProtoReflect.Descriptor instead.
func (*DaemonBindingClaims) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{0}
}

func (x *DaemonBindingClaims) GetBindingId() string {
	if x != nil {
		return x.BindingId
	}
	return ""
}

func (x *DaemonBindingClaims) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *DaemonBindingClaims) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *DaemonBindingClaims) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *DaemonBindingClaims) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DaemonBindingClaims) GetDevicePublicKey() []byte {
	if x != nil {
		return x.DevicePublicKey
	}
	return nil
}

func (x *DaemonBindingClaims) GetCapabilities() []DaemonCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DaemonBindingClaims) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *DaemonBindingClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *DaemonBindingClaims) GetEdgeLocatorSha256() []byte {
	if x != nil {
		return x.EdgeLocatorSha256
	}
	return nil
}

// AgentHelloProofInput 覆盖 Edge 单次 challenge、完整 binding envelope 摘要和 AgentHello 中除 proof 自身外的全部字段。
type AgentHelloProofInput struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	BindingEnvelopeSha256 []byte                 `protobuf:"bytes,1,opt,name=binding_envelope_sha256,json=bindingEnvelopeSha256,proto3" json:"binding_envelope_sha256,omitempty"`
	DaemonId              string                 `protobuf:"bytes,2,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	DaemonBootId          string                 `protobuf:"bytes,3,opt,name=daemon_boot_id,json=daemonBootId,proto3" json:"daemon_boot_id,omitempty"`
	DaemonSessionId       string                 `protobuf:"bytes,4,opt,name=daemon_session_id,json=daemonSessionId,proto3" json:"daemon_session_id,omitempty"`
	Challenge             *EdgeChallenge         `protobuf:"bytes,5,opt,name=challenge,proto3" json:"challenge,omitempty"`
	ProtocolVersion       uint32                 `protobuf:"varint,6,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId             string                 `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	StreamSeq             uint64                 `protobuf:"varint,8,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt                *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	SoftwareVersion       string                 `protobuf:"bytes,10,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	AttemptGeneration     uint64                 `protobuf:"varint,11,opt,name=attempt_generation,json=attemptGeneration,proto3" json:"attempt_generation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AgentHelloProofInput) Reset() {
	*x = AgentHelloProofInput{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentHelloProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentHelloProofInput) ProtoMessage() {}

func (x *AgentHelloProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentHelloProofInput.ProtoReflect.Descriptor instead.
func (*AgentHelloProofInput) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{1}
}

func (x *AgentHelloProofInput) GetBindingEnvelopeSha256() []byte {
	if x != nil {
		return x.BindingEnvelopeSha256
	}
	return nil
}

func (x *AgentHelloProofInput) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *AgentHelloProofInput) GetDaemonBootId() string {
	if x != nil {
		return x.DaemonBootId
	}
	return ""
}

func (x *AgentHelloProofInput) GetDaemonSessionId() string {
	if x != nil {
		return x.DaemonSessionId
	}
	return ""
}

func (x *AgentHelloProofInput) GetChallenge() *EdgeChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *AgentHelloProofInput) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *AgentHelloProofInput) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *AgentHelloProofInput) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *AgentHelloProofInput) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *AgentHelloProofInput) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *AgentHelloProofInput) GetAttemptGeneration() uint64 {
	if x != nil {
		return x.AttemptGeneration
	}
	return 0
}

// CloudRouteGrantClaims 由 owning daemon 的 DeviceIdentity 签发，只授权发现和信令。
// 该消息不得出现 terminal、scope、CapabilityGrant、命令或文件字段。
type CloudRouteGrantClaims struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GrantId         string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	DaemonId        string                 `protobuf:"bytes,2,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	ClientPublicKey []byte                 `protobuf:"bytes,3,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	Product         ClientProduct          `protobuf:"varint,4,opt,name=product,proto3,enum=anytty.cloud.v1.ClientProduct" json:"product,omitempty"`
	IssuedAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CloudRouteGrantClaims) Reset() {
	*x = CloudRouteGrantClaims{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudRouteGrantClaims) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudRouteGrantClaims) ProtoMessage() {}

func (x *CloudRouteGrantClaims) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudRouteGrantClaims.ProtoReflect.Descriptor instead.
func (*CloudRouteGrantClaims) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{2}
}

func (x *CloudRouteGrantClaims) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *CloudRouteGrantClaims) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *CloudRouteGrantClaims) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *CloudRouteGrantClaims) GetProduct() ClientProduct {
	if x != nil {
		return x.Product
	}
	return ClientProduct_CLIENT_PRODUCT_UNSPECIFIED
}

func (x *CloudRouteGrantClaims) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *CloudRouteGrantClaims) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// ClientRouteProofInput 把客户端 proof 绑定到 Controller nonce、grant 和本次解析请求。
type ClientRouteProofInput struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ChallengeId        string                 `protobuf:"bytes,1,opt,name=challenge_id,json=challengeId,proto3" json:"challenge_id,omitempty"`
	Challenge          []byte                 `protobuf:"bytes,2,opt,name=challenge,proto3" json:"challenge,omitempty"`
	GrantPayloadSha256 []byte                 `protobuf:"bytes,3,opt,name=grant_payload_sha256,json=grantPayloadSha256,proto3" json:"grant_payload_sha256,omitempty"`
	RequestId          string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ClientRouteProofInput) Reset() {
	*x = ClientRouteProofInput{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRouteProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRouteProofInput) ProtoMessage() {}

func (x *ClientRouteProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRouteProofInput.ProtoReflect.Descriptor instead.
func (*ClientRouteProofInput) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{3}
}

func (x *ClientRouteProofInput) GetChallengeId() string {
	if x != nil {
		return x.ChallengeId
	}
	return ""
}

func (x *ClientRouteProofInput) GetChallenge() []byte {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *ClientRouteProofInput) GetGrantPayloadSha256() []byte {
	if x != nil {
		return x.GrantPayloadSha256
	}
	return nil
}

func (x *ClientRouteProofInput) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// GatewayClientHelloProofInput 对两种 authorization 使用同一 v2 transcript。
// authorization_sha256 是对应 SignedEnvelope 或 PairingAdmission 的确定性 protobuf 摘要。
type GatewayClientHelloProofInput struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Challenge           *EdgeChallenge         `protobuf:"bytes,1,opt,name=challenge,proto3" json:"challenge,omitempty"`
	AuthorizationSha256 []byte                 `protobuf:"bytes,2,opt,name=authorization_sha256,json=authorizationSha256,proto3" json:"authorization_sha256,omitempty"`
	AccessMode          CloudClientAccessMode  `protobuf:"varint,3,opt,name=access_mode,json=accessMode,proto3,enum=anytty.cloud.v1.CloudClientAccessMode" json:"access_mode,omitempty"`
	ProtocolVersion     uint32                 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId           string                 `protobuf:"bytes,5,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ClientId            string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientBootId        string                 `protobuf:"bytes,7,opt,name=client_boot_id,json=clientBootId,proto3" json:"client_boot_id,omitempty"`
	ClientSessionId     string                 `protobuf:"bytes,8,opt,name=client_session_id,json=clientSessionId,proto3" json:"client_session_id,omitempty"`
	StreamSeq           uint64                 `protobuf:"varint,9,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt              *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	ClientPublicKey     []byte                 `protobuf:"bytes,11,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	Product             ClientProduct          `protobuf:"varint,12,opt,name=product,proto3,enum=anytty.cloud.v1.ClientProduct" json:"product,omitempty"`
	SoftwareVersion     string                 `protobuf:"bytes,13,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	AttemptGeneration   uint64                 `protobuf:"varint,14,opt,name=attempt_generation,json=attemptGeneration,proto3" json:"attempt_generation,omitempty"`
	RelayPreference     RelayPreference        `protobuf:"varint,15,opt,name=relay_preference,json=relayPreference,proto3,enum=anytty.cloud.v1.RelayPreference" json:"relay_preference,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GatewayClientHelloProofInput) Reset() {
	*x = GatewayClientHelloProofInput{}
	mi := &file_cloud_v1_ticket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayClientHelloProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayClientHelloProofInput) ProtoMessage() {}

func (x *GatewayClientHelloProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_ticket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayClientHelloProofInput.ProtoReflect.Descriptor instead.
func (*GatewayClientHelloProofInput) Descriptor() ([]byte, []int) {
	return file_cloud_v1_ticket_proto_rawDescGZIP(), []int{4}
}

func (x *GatewayClientHelloProofInput) GetChallenge() *EdgeChallenge {
	if x != nil {
		return x.Challenge
	}
	return nil
}

func (x *GatewayClientHelloProofInput) GetAuthorizationSha256() []byte {
	if x != nil {
		return x.AuthorizationSha256
	}
	return nil
}

func (x *GatewayClientHelloProofInput) GetAccessMode() CloudClientAccessMode {
	if x != nil {
		return x.AccessMode
	}
	return CloudClientAccessMode_CLOUD_CLIENT_ACCESS_MODE_UNSPECIFIED
}

func (x *GatewayClientHelloProofInput) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *GatewayClientHelloProofInput) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *GatewayClientHelloProofInput) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *GatewayClientHelloProofInput) GetClientBootId() string {
	if x != nil {
		return x.ClientBootId
	}
	return ""
}

func (x *GatewayClientHelloProofInput) GetClientSessionId() string {
	if x != nil {
		return x.ClientSessionId
	}
	return ""
}

func (x *GatewayClientHelloProofInput) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *GatewayClientHelloProofInput) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *GatewayClientHelloProofInput) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *GatewayClientHelloProofInput) GetProduct() ClientProduct {
	if x != nil {
		return x.Product
	}
	return ClientProduct_CLIENT_PRODUCT_UNSPECIFIED
}

func (x *GatewayClientHelloProofInput) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *GatewayClientHelloProofInput) GetAttemptGeneration() uint64 {
	if x != nil {
		return x.AttemptGeneration
	}
	return 0
}

func (x *GatewayClientHelloProofInput) GetRelayPreference() RelayPreference {
	if x != nil {
		return x.RelayPreference
	}
	return RelayPreference_RELAY_PREFERENCE_UNSPECIFIED
}

var File_cloud_v1_ticket_proto protoreflect.FileDescriptor

const file_cloud_v1_ticket_proto_rawDesc = "" +
	"\n" +
	"\x15cloud/v1/ticket.proto\x12\x0fanytty.cloud.v1\x1a\x15cloud/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16cloud/v1/runtime.proto\x1a\x14cloud/v1/usage.proto\"\xc9\x03\n" +
	"\x13DaemonBindingClaims\x12\x1d\n" +
	"\n" +
	"binding_id\x18\x01 \x01(\tR\tbindingId\x12\x1b\n" +
	"\tdaemon_id\x18\x02 \x01(\tR\bdaemonId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\tR\taccountId\x12\x17\n" +
	"\aedge_id\x18\x04 \x01(\tR\x06edgeId\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\x12*\n" +
	"\x11device_public_key\x18\x06 \x01(\fR\x0fdevicePublicKey\x12E\n" +
	"\fcapabilities\x18\a \x03(\x0e2!.anytty.cloud.v1.DaemonCapabilityR\fcapabilities\x127\n" +
	"\tissued_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12.\n" +
	"\x13edge_locator_sha256\x18\f \x01(\fR\x11edgeLocatorSha256J\x04\b\n" +
	"\x10\vJ\x04\b\v\x10\f\"\xf3\x03\n" +
	"\x14AgentHelloProofInput\x126\n" +
	"\x17binding_envelope_sha256\x18\x01 \x01(\fR\x15bindingEnvelopeSha256\x12\x1b\n" +
	"\tdaemon_id\x18\x02 \x01(\tR\bdaemonId\x12$\n" +
	"\x0edaemon_boot_id\x18\x03 \x01(\tR\fdaemonBootId\x12*\n" +
	"\x11daemon_session_id\x18\x04 \x01(\tR\x0fdaemonSessionId\x12<\n" +
	"\tchallenge\x18\x05 \x01(\v2\x1e.anytty.cloud.v1.EdgeChallengeR\tchallenge\x12)\n" +
	"\x10protocol_version\x18\x06 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\b \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12)\n" +
	"\x10software_version\x18\n" +
	" \x01(\tR\x0fsoftwareVersion\x12-\n" +
	"\x12attempt_generation\x18\v \x01(\x04R\x11attemptGeneration\"\xa9\x02\n" +
	"\x15CloudRouteGrantClaims\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x12\x1b\n" +
	"\tdaemon_id\x18\x02 \x01(\tR\bdaemonId\x12*\n" +
	"\x11client_public_key\x18\x03 \x01(\fR\x0fclientPublicKey\x128\n" +
	"\aproduct\x18\x04 \x01(\x0e2\x1e.anytty.cloud.v1.ClientProductR\aproduct\x127\n" +
	"\tissued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xa9\x01\n" +
	"\x15ClientRouteProofInput\x12!\n" +
	"\fchallenge_id\x18\x01 \x01(\tR\vchallengeId\x12\x1c\n" +
	"\tchallenge\x18\x02 \x01(\fR\tchallenge\x120\n" +
	"\x14grant_payload_sha256\x18\x03 \x01(\fR\x12grantPayloadSha256\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\xf2\x05\n" +
	"\x1cGatewayClientHelloProofInput\x12<\n" +
	"\tchallenge\x18\x01 \x01(\v2\x1e.anytty.cloud.v1.EdgeChallengeR\tchallenge\x121\n" +
	"\x14authorization_sha256\x18\x02 \x01(\fR\x13authorizationSha256\x12G\n" +
	"\vaccess_mode\x18\x03 \x01(\x0e2&.anytty.cloud.v1.CloudClientAccessModeR\n" +
	"accessMode\x12)\n" +
	"\x10protocol_version\x18\x04 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x05 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12$\n" +
	"\x0eclient_boot_id\x18\a \x01(\tR\fclientBootId\x12*\n" +
	"\x11client_session_id\x18\b \x01(\tR\x0fclientSessionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\t \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12*\n" +
	"\x11client_public_key\x18\v \x01(\fR\x0fclientPublicKey\x128\n" +
	"\aproduct\x18\f \x01(\x0e2\x1e.anytty.cloud.v1.ClientProductR\aproduct\x12)\n" +
	"\x10software_version\x18\r \x01(\tR\x0fsoftwareVersion\x12-\n" +
	"\x12attempt_generation\x18\x0e \x01(\x04R\x11attemptGeneration\x12K\n" +
	"\x10relay_preference\x18\x0f \x01(\x0e2 .anytty.cloud.v1.RelayPreferenceR\x0frelayPreference*V\n" +
	"\x10DaemonCapability\x12!\n" +
	"\x1dDAEMON_CAPABILITY_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bDAEMON_CAPABILITY_SIGNALING\x10\x01B1Z/github.com/anytty/anytty/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_ticket_proto_rawDescOnce sync.Once
	file_cloud_v1_ticket_proto_rawDescData []byte
)

func file_cloud_v1_ticket_proto_rawDescGZIP() []byte {
	file_cloud_v1_ticket_proto_rawDescOnce.Do(func() {
		file_cloud_v1_ticket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_ticket_proto_rawDesc), len(file_cloud_v1_ticket_proto_rawDesc)))
	})
	return file_cloud_v1_ticket_proto_rawDescData
}

var file_cloud_v1_ticket_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_cloud_v1_ticket_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_cloud_v1_ticket_proto_goTypes = []any{
	(DaemonCapability)(0),                // 0: anytty.cloud.v1.DaemonCapability
	(*DaemonBindingClaims)(nil),          // 1: anytty.cloud.v1.DaemonBindingClaims
	(*AgentHelloProofInput)(nil),         // 2: anytty.cloud.v1.AgentHelloProofInput
	(*CloudRouteGrantClaims)(nil),        // 3: anytty.cloud.v1.CloudRouteGrantClaims
	(*ClientRouteProofInput)(nil),        // 4: anytty.cloud.v1.ClientRouteProofInput
	(*GatewayClientHelloProofInput)(nil), // 5: anytty.cloud.v1.GatewayClientHelloProofInput
	(*timestamppb.Timestamp)(nil),        // 6: google.protobuf.Timestamp
	(*EdgeChallenge)(nil),                // 7: anytty.cloud.v1.EdgeChallenge
	(ClientProduct)(0),                   // 8: anytty.cloud.v1.ClientProduct
	(CloudClientAccessMode)(0),           // 9: anytty.cloud.v1.CloudClientAccessMode
	(RelayPreference)(0),                 // 10: anytty.cloud.v1.RelayPreference
}
var file_cloud_v1_ticket_proto_depIdxs = []int32{
	0,  // 0: anytty.cloud.v1.DaemonBindingClaims.capabilities:type_name -> anytty.cloud.v1.DaemonCapability
	6,  // 1: anytty.cloud.v1.DaemonBindingClaims.issued_at:type_name -> google.protobuf.Timestamp
	6,  // 2: anytty.cloud.v1.DaemonBindingClaims.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 3: anytty.cloud.v1.AgentHelloProofInput.challenge:type_name -> anytty.cloud.v1.EdgeChallenge
	6,  // 4: anytty.cloud.v1.AgentHelloProofInput.sent_at:type_name -> google.protobuf.Timestamp
	8,  // 5: anytty.cloud.v1.CloudRouteGrantClaims.product:type_name -> anytty.cloud.v1.ClientProduct
	6,  // 6: anytty.cloud.v1.CloudRouteGrantClaims.issued_at:type_name -> google.protobuf.Timestamp
	6,  // 7: anytty.cloud.v1.CloudRouteGrantClaims.expires_at:type_name -> google.protobuf.Timestamp
	7,  // 8: anytty.cloud.v1.GatewayClientHelloProofInput.challenge:type_name -> anytty.cloud.v1.EdgeChallenge
	9,  // 9: anytty.cloud.v1.GatewayClientHelloProofInput.access_mode:type_name -> anytty.cloud.v1.CloudClientAccessMode
	6,  // 10: anytty.cloud.v1.GatewayClientHelloProofInput.sent_at:type_name -> google.protobuf.Timestamp
	8,  // 11: anytty.cloud.v1.GatewayClientHelloProofInput.product:type_name -> anytty.cloud.v1.ClientProduct
	10, // 12: anytty.cloud.v1.GatewayClientHelloProofInput.relay_preference:type_name -> anytty.cloud.v1.RelayPreference
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_cloud_v1_ticket_proto_init() }
func file_cloud_v1_ticket_proto_init() {
	if File_cloud_v1_ticket_proto != nil {
		return
	}
	file_cloud_v1_common_proto_init()
	file_cloud_v1_runtime_proto_init()
	file_cloud_v1_usage_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_ticket_proto_rawDesc), len(file_cloud_v1_ticket_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_v1_ticket_proto_goTypes,
		DependencyIndexes: file_cloud_v1_ticket_proto_depIdxs,
		EnumInfos:         file_cloud_v1_ticket_proto_enumTypes,
		MessageInfos:      file_cloud_v1_ticket_proto_msgTypes,
	}.Build()
	File_cloud_v1_ticket_proto = out.File
	file_cloud_v1_ticket_proto_goTypes = nil
	file_cloud_v1_ticket_proto_depIdxs = nil
}
