#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
mode="update"
public_only=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)
      mode="check"
      ;;
    --public-only)
      public_only=true
      ;;
    *)
      echo "usage: $0 [--check] [--public-only]" >&2
      exit 2
      ;;
  esac
  shift
done

tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/muxvia-go-notices.XXXXXX")"
trap 'rm -rf "$tmp_dir"' EXIT

go_licenses="${GO_LICENSES_BIN:-}"
if [[ -z "$go_licenses" ]]; then
  if command -v go-licenses >/dev/null 2>&1; then
    go_licenses="$(command -v go-licenses)"
  else
    mkdir -p "$tmp_dir/bin"
    GOBIN="$tmp_dir/bin" go install github.com/google/go-licenses/v2@v2.0.1
    go_licenses="$tmp_dir/bin/go-licenses"
  fi
fi
if [[ ! -x "$go_licenses" ]]; then
  echo "GO_LICENSES_BIN is not executable: $go_licenses" >&2
  exit 1
fi

validate_report() {
  local report="$1"
  local dependency_package ignored license
  while IFS=, read -r dependency_package ignored license; do
    [[ -n "$dependency_package" ]] || continue
    if [[ "$dependency_package" == github.com/muxvia/muxvia/* ]]; then
      continue
    fi
    case "$license" in
      Apache-2.0|BSD-2-Clause|BSD-3-Clause|MIT)
        ;;
      *)
        echo "unapproved Go dependency license: $dependency_package ($license)" >&2
        exit 1
        ;;
    esac
  done <"$report"
  return 0
}

merge_saved_licenses() {
  local source_root="$1"
  local merged_root="$2"
  local file relative target
  while IFS= read -r file; do
    relative="${file#$source_root/}"
    target="$merged_root/$relative"
    mkdir -p "$(dirname "$target")"
    if [[ -f "$target" ]] && ! cmp -s "$file" "$target"; then
      echo "conflicting Go license text for $relative" >&2
      exit 1
    fi
    [[ -f "$target" ]] || install -m 0644 "$file" "$target"
  done < <(find "$source_root" -type f | LC_ALL=C sort)
  return 0
}

normalize_text() {
  LC_ALL=C perl -0777 -pe 's/\r\n/\n/g; s/[ \t]+(?=\n)//g; s/[ \t\r\n]*\z/\n/s' "$1"
}

generate_artifact() {
  local artifact="$1"
  local workdir="$2"
  local package="$3"
  local relative_target="$4"
  local artifact_dir="$tmp_dir/$artifact"
  local reports_dir="$artifact_dir/reports"
  local merged_dir="$artifact_dir/licenses"
  mkdir -p "$reports_dir" "$merged_dir"

  local platform goos goarch report save_dir warnings
  for platform in darwin-arm64 linux-amd64 windows-amd64; do
    goos="${platform%-*}"
    goarch="${platform#*-}"
    report="$reports_dir/$platform.csv"
    save_dir="$artifact_dir/save-$platform"
    warnings="$artifact_dir/$platform.warnings"
    (
      cd "$workdir"
      CGO_ENABLED=0 GOOS="$goos" GOARCH="$goarch" "$go_licenses" report "$package"
    ) >"$report" 2>"$warnings"
    validate_report "$report"
    local save_status=0
    (
      cd "$workdir"
      CGO_ENABLED=0 GOOS="$goos" GOARCH="$goarch" "$go_licenses" save "$package" --save_path "$save_dir"
    ) 2>>"$warnings" || save_status=$?
    if [[ "$save_status" -ne 0 ]]; then
      if [[ "$save_status" -ne 1 ]] || ! grep -q 'one or more libraries have an incompatible/unknown license' "$warnings"; then
        cat "$warnings" >&2
        exit "$save_status"
      fi
    fi
    if [[ ! -d "$save_dir" ]] || [[ -z "$(find "$save_dir" -type f -print -quit)" ]]; then
      echo "go-licenses exported no license files for $artifact $platform" >&2
      cat "$warnings" >&2
      exit 1
    fi
    merge_saved_licenses "$save_dir" "$merged_dir"
  done

  cat "$reports_dir"/*.csv \
    | awk -F, '$1 !~ /^github.com\/lozzow\/muxvia\// || $1 == "github.com/muxvia/muxvia/vterm/internal/vt"' \
    | LC_ALL=C sort -u >"$artifact_dir/report.csv"

  local raw_output="$artifact_dir/THIRD_PARTY_NOTICES.raw.txt"
  local output="$artifact_dir/THIRD_PARTY_NOTICES.txt"
  {
    printf 'Muxvia %s Third-Party Notices\n\n' "$artifact"
    printf '%s\n' "Generated by scripts/generate-go-notices.sh with google/go-licenses v2.0.1"
    printf '%s\n\n' "for darwin/arm64, linux/amd64, and windows/amd64 release dependency graphs."
    printf '%s\n' "DEPENDENCY REPORT"
    cat "$artifact_dir/report.csv"
    printf '\n%s\n' "LICENSE FILES"
    local file relative
    while IFS= read -r file; do
      relative="${file#$merged_dir/}"
      printf '\n%s\n%s\n%s\n\n' "==============================================================================" "$relative" "=============================================================================="
      cat "$file"
      printf '\n'
    done < <(find "$merged_dir" -type f | LC_ALL=C sort)
  } >"$raw_output"
  normalize_text "$raw_output" >"$output"

  local target="$repo_root/$relative_target"
  if [[ "$mode" == "check" ]]; then
    if [[ ! -f "$target" ]] || ! cmp -s "$output" "$target"; then
      echo "stale or missing Go notices: $relative_target" >&2
      exit 1
    fi
  else
    mkdir -p "$(dirname "$target")"
    install -m 0644 "$output" "$target"
  fi
}

generate_artifact \
  "CLI" \
  "$repo_root" \
  "./cmd/muxvia" \
  "cmd/muxvia/THIRD_PARTY_NOTICES.txt"

if [[ "$public_only" == false ]]; then
  generate_artifact \
    "Cloud Companion" \
    "$repo_root/private/cloud/companion" \
    "./cmd/muxvia-cloud" \
    "private/cloud/companion/cmd/muxvia-cloud/THIRD_PARTY_NOTICES.txt"
fi

echo "Go notices are $mode"
