// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: remoteauthpb/remote_auth.proto

package remoteauthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthErrorCode 是端到端授权失败时允许返回给对端的稳定分类。
// detail 必须脱敏，不能暴露 grant 是否对应某个已存在 terminal。
type AuthErrorCode int32

const (
	AuthErrorCode_AUTH_ERROR_CODE_UNSPECIFIED              AuthErrorCode = 0
	AuthErrorCode_AUTH_ERROR_CODE_PROTOCOL                 AuthErrorCode = 1
	AuthErrorCode_AUTH_ERROR_CODE_DEVICE_IDENTITY_MISMATCH AuthErrorCode = 2
	AuthErrorCode_AUTH_ERROR_CODE_CAPABILITY_INVALID       AuthErrorCode = 3
	AuthErrorCode_AUTH_ERROR_CODE_CAPABILITY_EXPIRED       AuthErrorCode = 4
	AuthErrorCode_AUTH_ERROR_CODE_CAPABILITY_REVOKED       AuthErrorCode = 5
	AuthErrorCode_AUTH_ERROR_CODE_CAPABILITY_PROOF_INVALID AuthErrorCode = 6
	AuthErrorCode_AUTH_ERROR_CODE_SCOPE_INVALID            AuthErrorCode = 7
	AuthErrorCode_AUTH_ERROR_CODE_REPLAYED                 AuthErrorCode = 8
	AuthErrorCode_AUTH_ERROR_CODE_INTERNAL                 AuthErrorCode = 9
)

// Enum value maps for AuthErrorCode.
var (
	AuthErrorCode_name = map[int32]string{
		0: "AUTH_ERROR_CODE_UNSPECIFIED",
		1: "AUTH_ERROR_CODE_PROTOCOL",
		2: "AUTH_ERROR_CODE_DEVICE_IDENTITY_MISMATCH",
		3: "AUTH_ERROR_CODE_CAPABILITY_INVALID",
		4: "AUTH_ERROR_CODE_CAPABILITY_EXPIRED",
		5: "AUTH_ERROR_CODE_CAPABILITY_REVOKED",
		6: "AUTH_ERROR_CODE_CAPABILITY_PROOF_INVALID",
		7: "AUTH_ERROR_CODE_SCOPE_INVALID",
		8: "AUTH_ERROR_CODE_REPLAYED",
		9: "AUTH_ERROR_CODE_INTERNAL",
	}
	AuthErrorCode_value = map[string]int32{
		"AUTH_ERROR_CODE_UNSPECIFIED":              0,
		"AUTH_ERROR_CODE_PROTOCOL":                 1,
		"AUTH_ERROR_CODE_DEVICE_IDENTITY_MISMATCH": 2,
		"AUTH_ERROR_CODE_CAPABILITY_INVALID":       3,
		"AUTH_ERROR_CODE_CAPABILITY_EXPIRED":       4,
		"AUTH_ERROR_CODE_CAPABILITY_REVOKED":       5,
		"AUTH_ERROR_CODE_CAPABILITY_PROOF_INVALID": 6,
		"AUTH_ERROR_CODE_SCOPE_INVALID":            7,
		"AUTH_ERROR_CODE_REPLAYED":                 8,
		"AUTH_ERROR_CODE_INTERNAL":                 9,
	}
)

func (x AuthErrorCode) Enum() *AuthErrorCode {
	p := new(AuthErrorCode)
	*p = x
	return p
}

func (x AuthErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_remoteauthpb_remote_auth_proto_enumTypes[0].Descriptor()
}

func (AuthErrorCode) Type() protoreflect.EnumType {
	return &file_remoteauthpb_remote_auth_proto_enumTypes[0]
}

func (x AuthErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthErrorCode.Descriptor instead.
func (AuthErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{0}
}

// ScopeKind 是 capability 成功映射到 core-v2 前的规范化 scope 分类。
type ScopeKind int32

const (
	ScopeKind_SCOPE_KIND_UNSPECIFIED    ScopeKind = 0
	ScopeKind_SCOPE_KIND_DAEMON         ScopeKind = 1
	ScopeKind_SCOPE_KIND_TERMINAL       ScopeKind = 2
	ScopeKind_SCOPE_KIND_MACHINE_EVENTS ScopeKind = 3
)

// Enum value maps for ScopeKind.
var (
	ScopeKind_name = map[int32]string{
		0: "SCOPE_KIND_UNSPECIFIED",
		1: "SCOPE_KIND_DAEMON",
		2: "SCOPE_KIND_TERMINAL",
		3: "SCOPE_KIND_MACHINE_EVENTS",
	}
	ScopeKind_value = map[string]int32{
		"SCOPE_KIND_UNSPECIFIED":    0,
		"SCOPE_KIND_DAEMON":         1,
		"SCOPE_KIND_TERMINAL":       2,
		"SCOPE_KIND_MACHINE_EVENTS": 3,
	}
)

func (x ScopeKind) Enum() *ScopeKind {
	p := new(ScopeKind)
	*p = x
	return p
}

func (x ScopeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScopeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_remoteauthpb_remote_auth_proto_enumTypes[1].Descriptor()
}

func (ScopeKind) Type() protoreflect.EnumType {
	return &file_remoteauthpb_remote_auth_proto_enumTypes[1]
}

func (x ScopeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScopeKind.Descriptor instead.
func (ScopeKind) EnumDescriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{1}
}

// AuthEnvelope 是 DataChannel protocol 切换前唯一允许出现的 versioned frame。
// 每条 DataChannel 使用独立 auth_session_id；CapabilityAccepted 后该 envelope 不得再次出现。
type AuthEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Version       uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	AuthSessionId string                 `protobuf:"bytes,3,opt,name=auth_session_id,json=authSessionId,proto3" json:"auth_session_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AuthEnvelope_DeviceHello
	//	*AuthEnvelope_CapabilityOpen
	//	*AuthEnvelope_CapabilityAccepted
	//	*AuthEnvelope_CapabilityRejected
	Payload       isAuthEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthEnvelope) Reset() {
	*x = AuthEnvelope{}
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEnvelope) ProtoMessage() {}

func (x *AuthEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEnvelope.ProtoReflect.Descriptor instead.
func (*AuthEnvelope) Descriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthEnvelope) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AuthEnvelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *AuthEnvelope) GetAuthSessionId() string {
	if x != nil {
		return x.AuthSessionId
	}
	return ""
}

func (x *AuthEnvelope) GetPayload() isAuthEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AuthEnvelope) GetDeviceHello() *DeviceHello {
	if x != nil {
		if x, ok := x.Payload.(*AuthEnvelope_DeviceHello); ok {
			return x.DeviceHello
		}
	}
	return nil
}

func (x *AuthEnvelope) GetCapabilityOpen() *CapabilityOpen {
	if x != nil {
		if x, ok := x.Payload.(*AuthEnvelope_CapabilityOpen); ok {
			return x.CapabilityOpen
		}
	}
	return nil
}

func (x *AuthEnvelope) GetCapabilityAccepted() *CapabilityAccepted {
	if x != nil {
		if x, ok := x.Payload.(*AuthEnvelope_CapabilityAccepted); ok {
			return x.CapabilityAccepted
		}
	}
	return nil
}

func (x *AuthEnvelope) GetCapabilityRejected() *CapabilityRejected {
	if x != nil {
		if x, ok := x.Payload.(*AuthEnvelope_CapabilityRejected); ok {
			return x.CapabilityRejected
		}
	}
	return nil
}

type isAuthEnvelope_Payload interface {
	isAuthEnvelope_Payload()
}

type AuthEnvelope_DeviceHello struct {
	DeviceHello *DeviceHello `protobuf:"bytes,4,opt,name=device_hello,json=deviceHello,proto3,oneof"`
}

type AuthEnvelope_CapabilityOpen struct {
	CapabilityOpen *CapabilityOpen `protobuf:"bytes,5,opt,name=capability_open,json=capabilityOpen,proto3,oneof"`
}

type AuthEnvelope_CapabilityAccepted struct {
	CapabilityAccepted *CapabilityAccepted `protobuf:"bytes,6,opt,name=capability_accepted,json=capabilityAccepted,proto3,oneof"`
}

type AuthEnvelope_CapabilityRejected struct {
	CapabilityRejected *CapabilityRejected `protobuf:"bytes,7,opt,name=capability_rejected,json=capabilityRejected,proto3,oneof"`
}

func (*AuthEnvelope_DeviceHello) isAuthEnvelope_Payload() {}

func (*AuthEnvelope_CapabilityOpen) isAuthEnvelope_Payload() {}

func (*AuthEnvelope_CapabilityAccepted) isAuthEnvelope_Payload() {}

func (*AuthEnvelope_CapabilityRejected) isAuthEnvelope_Payload() {}

// DeviceHello 是 daemon 对长期 DeviceIdentity 和本次 DTLS channel 的联合证明。
type DeviceHello struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId                         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DevicePublicKey                  []byte                 `protobuf:"bytes,2,opt,name=device_public_key,json=devicePublicKey,proto3" json:"device_public_key,omitempty"`
	DeviceFingerprint                string                 `protobuf:"bytes,3,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	ServerNonce                      []byte                 `protobuf:"bytes,4,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	DaemonDtlsCertificateFingerprint string                 `protobuf:"bytes,5,opt,name=daemon_dtls_certificate_fingerprint,json=daemonDtlsCertificateFingerprint,proto3" json:"daemon_dtls_certificate_fingerprint,omitempty"`
	IssuedAtUnixNano                 int64                  `protobuf:"varint,6,opt,name=issued_at_unix_nano,json=issuedAtUnixNano,proto3" json:"issued_at_unix_nano,omitempty"`
	Signature                        []byte                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DeviceHello) Reset() {
	*x = DeviceHello{}
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHello) ProtoMessage() {}

func (x *DeviceHello) ProtoReflect() protoreflect.Message {
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHello.ProtoReflect.Descriptor instead.
func (*DeviceHello) Descriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{1}
}

func (x *DeviceHello) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceHello) GetDevicePublicKey() []byte {
	if x != nil {
		return x.DevicePublicKey
	}
	return nil
}

func (x *DeviceHello) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *DeviceHello) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *DeviceHello) GetDaemonDtlsCertificateFingerprint() string {
	if x != nil {
		return x.DaemonDtlsCertificateFingerprint
	}
	return ""
}

func (x *DeviceHello) GetIssuedAtUnixNano() int64 {
	if x != nil {
		return x.IssuedAtUnixNano
	}
	return 0
}

func (x *DeviceHello) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// CapabilityOpen 证明 client 当前持有完整 grant，并把它绑定到本次 daemon challenge。
// grant 只允许出现在端到端 DTLS DataChannel 内，不能进入 cloud signaling DTO。
type CapabilityOpen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         string                 `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	ClientNonce   []byte                 `protobuf:"bytes,2,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	Proof         []byte                 `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityOpen) Reset() {
	*x = CapabilityOpen{}
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityOpen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityOpen) ProtoMessage() {}

func (x *CapabilityOpen) ProtoReflect() protoreflect.Message {
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityOpen.ProtoReflect.Descriptor instead.
func (*CapabilityOpen) Descriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CapabilityOpen) GetGrant() string {
	if x != nil {
		return x.Grant
	}
	return ""
}

func (x *CapabilityOpen) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *CapabilityOpen) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

// ScopeSummary 是 daemon 已接受 capability 的最小无歧义投影。
type ScopeSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ScopeKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=termx.remote.auth.v1.ScopeKind" json:"kind,omitempty"`
	TerminalId    string                 `protobuf:"bytes,2,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScopeSummary) Reset() {
	*x = ScopeSummary{}
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeSummary) ProtoMessage() {}

func (x *ScopeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScopeSummary.ProtoReflect.Descriptor instead.
func (*ScopeSummary) Descriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ScopeSummary) GetKind() ScopeKind {
	if x != nil {
		return x.Kind
	}
	return ScopeKind_SCOPE_KIND_UNSPECIFIED
}

func (x *ScopeSummary) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

// CapabilityAccepted 是 remote auth 到 termx protocol 的单向切换点。
type CapabilityAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	Scope         *ScopeSummary          `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityAccepted) Reset() {
	*x = CapabilityAccepted{}
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityAccepted) ProtoMessage() {}

func (x *CapabilityAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityAccepted.ProtoReflect.Descriptor instead.
func (*CapabilityAccepted) Descriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilityAccepted) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

func (x *CapabilityAccepted) GetScope() *ScopeSummary {
	if x != nil {
		return x.Scope
	}
	return nil
}

// CapabilityRejected 返回稳定错误类别和固定脱敏消息，随后 channel 必须关闭。
type CapabilityRejected struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          AuthErrorCode          `protobuf:"varint,1,opt,name=code,proto3,enum=termx.remote.auth.v1.AuthErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilityRejected) Reset() {
	*x = CapabilityRejected{}
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityRejected) ProtoMessage() {}

func (x *CapabilityRejected) ProtoReflect() protoreflect.Message {
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityRejected.ProtoReflect.Descriptor instead.
func (*CapabilityRejected) Descriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CapabilityRejected) GetCode() AuthErrorCode {
	if x != nil {
		return x.Code
	}
	return AuthErrorCode_AUTH_ERROR_CODE_UNSPECIFIED
}

func (x *CapabilityRejected) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DeviceHelloSignatureInput 是 Ed25519 签名的跨平台 canonical protobuf。
// 所有实现必须拒绝 unknown field，并使用 deterministic protobuf bytes，不得改用 JSON 或字段拼接。
type DeviceHelloSignatureInput struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Protocol                         string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Version                          uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	AuthSessionId                    string                 `protobuf:"bytes,3,opt,name=auth_session_id,json=authSessionId,proto3" json:"auth_session_id,omitempty"`
	DeviceId                         string                 `protobuf:"bytes,4,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DevicePublicKey                  []byte                 `protobuf:"bytes,5,opt,name=device_public_key,json=devicePublicKey,proto3" json:"device_public_key,omitempty"`
	DeviceFingerprint                string                 `protobuf:"bytes,6,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	ServerNonce                      []byte                 `protobuf:"bytes,7,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	DaemonDtlsCertificateFingerprint string                 `protobuf:"bytes,8,opt,name=daemon_dtls_certificate_fingerprint,json=daemonDtlsCertificateFingerprint,proto3" json:"daemon_dtls_certificate_fingerprint,omitempty"`
	IssuedAtUnixNano                 int64                  `protobuf:"varint,9,opt,name=issued_at_unix_nano,json=issuedAtUnixNano,proto3" json:"issued_at_unix_nano,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *DeviceHelloSignatureInput) Reset() {
	*x = DeviceHelloSignatureInput{}
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHelloSignatureInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHelloSignatureInput) ProtoMessage() {}

func (x *DeviceHelloSignatureInput) ProtoReflect() protoreflect.Message {
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHelloSignatureInput.ProtoReflect.Descriptor instead.
func (*DeviceHelloSignatureInput) Descriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceHelloSignatureInput) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *DeviceHelloSignatureInput) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *DeviceHelloSignatureInput) GetAuthSessionId() string {
	if x != nil {
		return x.AuthSessionId
	}
	return ""
}

func (x *DeviceHelloSignatureInput) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceHelloSignatureInput) GetDevicePublicKey() []byte {
	if x != nil {
		return x.DevicePublicKey
	}
	return nil
}

func (x *DeviceHelloSignatureInput) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *DeviceHelloSignatureInput) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *DeviceHelloSignatureInput) GetDaemonDtlsCertificateFingerprint() string {
	if x != nil {
		return x.DaemonDtlsCertificateFingerprint
	}
	return ""
}

func (x *DeviceHelloSignatureInput) GetIssuedAtUnixNano() int64 {
	if x != nil {
		return x.IssuedAtUnixNano
	}
	return 0
}

// CapabilityProofInput 是 HMAC-SHA-256 proof 的跨平台 canonical protobuf。
// HMAC key 是去除首尾空白后的原始 grant UTF-8 bytes；grant_sha256 是同一规范化 grant 的 SHA-256。
type CapabilityProofInput struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	Protocol                         string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Version                          uint32                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	AuthSessionId                    string                 `protobuf:"bytes,3,opt,name=auth_session_id,json=authSessionId,proto3" json:"auth_session_id,omitempty"`
	ServerNonce                      []byte                 `protobuf:"bytes,4,opt,name=server_nonce,json=serverNonce,proto3" json:"server_nonce,omitempty"`
	ClientNonce                      []byte                 `protobuf:"bytes,5,opt,name=client_nonce,json=clientNonce,proto3" json:"client_nonce,omitempty"`
	DaemonDtlsCertificateFingerprint string                 `protobuf:"bytes,6,opt,name=daemon_dtls_certificate_fingerprint,json=daemonDtlsCertificateFingerprint,proto3" json:"daemon_dtls_certificate_fingerprint,omitempty"`
	GrantSha256                      []byte                 `protobuf:"bytes,7,opt,name=grant_sha256,json=grantSha256,proto3" json:"grant_sha256,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *CapabilityProofInput) Reset() {
	*x = CapabilityProofInput{}
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityProofInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityProofInput) ProtoMessage() {}

func (x *CapabilityProofInput) ProtoReflect() protoreflect.Message {
	mi := &file_remoteauthpb_remote_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityProofInput.ProtoReflect.Descriptor instead.
func (*CapabilityProofInput) Descriptor() ([]byte, []int) {
	return file_remoteauthpb_remote_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CapabilityProofInput) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *CapabilityProofInput) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *CapabilityProofInput) GetAuthSessionId() string {
	if x != nil {
		return x.AuthSessionId
	}
	return ""
}

func (x *CapabilityProofInput) GetServerNonce() []byte {
	if x != nil {
		return x.ServerNonce
	}
	return nil
}

func (x *CapabilityProofInput) GetClientNonce() []byte {
	if x != nil {
		return x.ClientNonce
	}
	return nil
}

func (x *CapabilityProofInput) GetDaemonDtlsCertificateFingerprint() string {
	if x != nil {
		return x.DaemonDtlsCertificateFingerprint
	}
	return ""
}

func (x *CapabilityProofInput) GetGrantSha256() []byte {
	if x != nil {
		return x.GrantSha256
	}
	return nil
}

var File_remoteauthpb_remote_auth_proto protoreflect.FileDescriptor

const file_remoteauthpb_remote_auth_proto_rawDesc = "" +
	"\n" +
	"\x1eremoteauthpb/remote_auth.proto\x12\x14termx.remote.auth.v1\"\xca\x03\n" +
	"\fAuthEnvelope\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12&\n" +
	"\x0fauth_session_id\x18\x03 \x01(\tR\rauthSessionId\x12F\n" +
	"\fdevice_hello\x18\x04 \x01(\v2!.termx.remote.auth.v1.DeviceHelloH\x00R\vdeviceHello\x12O\n" +
	"\x0fcapability_open\x18\x05 \x01(\v2$.termx.remote.auth.v1.CapabilityOpenH\x00R\x0ecapabilityOpen\x12[\n" +
	"\x13capability_accepted\x18\x06 \x01(\v2(.termx.remote.auth.v1.CapabilityAcceptedH\x00R\x12capabilityAccepted\x12[\n" +
	"\x13capability_rejected\x18\a \x01(\v2(.termx.remote.auth.v1.CapabilityRejectedH\x00R\x12capabilityRejectedB\t\n" +
	"\apayload\"\xc4\x02\n" +
	"\vDeviceHello\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12*\n" +
	"\x11device_public_key\x18\x02 \x01(\fR\x0fdevicePublicKey\x12-\n" +
	"\x12device_fingerprint\x18\x03 \x01(\tR\x11deviceFingerprint\x12!\n" +
	"\fserver_nonce\x18\x04 \x01(\fR\vserverNonce\x12M\n" +
	"#daemon_dtls_certificate_fingerprint\x18\x05 \x01(\tR daemonDtlsCertificateFingerprint\x12-\n" +
	"\x13issued_at_unix_nano\x18\x06 \x01(\x03R\x10issuedAtUnixNano\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\"_\n" +
	"\x0eCapabilityOpen\x12\x14\n" +
	"\x05grant\x18\x01 \x01(\tR\x05grant\x12!\n" +
	"\fclient_nonce\x18\x02 \x01(\fR\vclientNonce\x12\x14\n" +
	"\x05proof\x18\x03 \x01(\fR\x05proof\"d\n" +
	"\fScopeSummary\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.termx.remote.auth.v1.ScopeKindR\x04kind\x12\x1f\n" +
	"\vterminal_id\x18\x02 \x01(\tR\n" +
	"terminalId\"i\n" +
	"\x12CapabilityAccepted\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\x128\n" +
	"\x05scope\x18\x02 \x01(\v2\".termx.remote.auth.v1.ScopeSummaryR\x05scope\"g\n" +
	"\x12CapabilityRejected\x127\n" +
	"\x04code\x18\x01 \x01(\x0e2#.termx.remote.auth.v1.AuthErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x92\x03\n" +
	"\x19DeviceHelloSignatureInput\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12&\n" +
	"\x0fauth_session_id\x18\x03 \x01(\tR\rauthSessionId\x12\x1b\n" +
	"\tdevice_id\x18\x04 \x01(\tR\bdeviceId\x12*\n" +
	"\x11device_public_key\x18\x05 \x01(\fR\x0fdevicePublicKey\x12-\n" +
	"\x12device_fingerprint\x18\x06 \x01(\tR\x11deviceFingerprint\x12!\n" +
	"\fserver_nonce\x18\a \x01(\fR\vserverNonce\x12M\n" +
	"#daemon_dtls_certificate_fingerprint\x18\b \x01(\tR daemonDtlsCertificateFingerprint\x12-\n" +
	"\x13issued_at_unix_nano\x18\t \x01(\x03R\x10issuedAtUnixNano\"\xac\x02\n" +
	"\x14CapabilityProofInput\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12\x18\n" +
	"\aversion\x18\x02 \x01(\rR\aversion\x12&\n" +
	"\x0fauth_session_id\x18\x03 \x01(\tR\rauthSessionId\x12!\n" +
	"\fserver_nonce\x18\x04 \x01(\fR\vserverNonce\x12!\n" +
	"\fclient_nonce\x18\x05 \x01(\fR\vclientNonce\x12M\n" +
	"#daemon_dtls_certificate_fingerprint\x18\x06 \x01(\tR daemonDtlsCertificateFingerprint\x12!\n" +
	"\fgrant_sha256\x18\a \x01(\fR\vgrantSha256*\x81\x03\n" +
	"\rAuthErrorCode\x12\x1f\n" +
	"\x1bAUTH_ERROR_CODE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18AUTH_ERROR_CODE_PROTOCOL\x10\x01\x12,\n" +
	"(AUTH_ERROR_CODE_DEVICE_IDENTITY_MISMATCH\x10\x02\x12&\n" +
	"\"AUTH_ERROR_CODE_CAPABILITY_INVALID\x10\x03\x12&\n" +
	"\"AUTH_ERROR_CODE_CAPABILITY_EXPIRED\x10\x04\x12&\n" +
	"\"AUTH_ERROR_CODE_CAPABILITY_REVOKED\x10\x05\x12,\n" +
	"(AUTH_ERROR_CODE_CAPABILITY_PROOF_INVALID\x10\x06\x12!\n" +
	"\x1dAUTH_ERROR_CODE_SCOPE_INVALID\x10\a\x12\x1c\n" +
	"\x18AUTH_ERROR_CODE_REPLAYED\x10\b\x12\x1c\n" +
	"\x18AUTH_ERROR_CODE_INTERNAL\x10\t*v\n" +
	"\tScopeKind\x12\x1a\n" +
	"\x16SCOPE_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SCOPE_KIND_DAEMON\x10\x01\x12\x17\n" +
	"\x13SCOPE_KIND_TERMINAL\x10\x02\x12\x1d\n" +
	"\x19SCOPE_KIND_MACHINE_EVENTS\x10\x03B2Z0github.com/lozzow/termx/termx-proto/remoteauthpbb\x06proto3"

var (
	file_remoteauthpb_remote_auth_proto_rawDescOnce sync.Once
	file_remoteauthpb_remote_auth_proto_rawDescData []byte
)

func file_remoteauthpb_remote_auth_proto_rawDescGZIP() []byte {
	file_remoteauthpb_remote_auth_proto_rawDescOnce.Do(func() {
		file_remoteauthpb_remote_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_remoteauthpb_remote_auth_proto_rawDesc), len(file_remoteauthpb_remote_auth_proto_rawDesc)))
	})
	return file_remoteauthpb_remote_auth_proto_rawDescData
}

var file_remoteauthpb_remote_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_remoteauthpb_remote_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_remoteauthpb_remote_auth_proto_goTypes = []any{
	(AuthErrorCode)(0),                // 0: termx.remote.auth.v1.AuthErrorCode
	(ScopeKind)(0),                    // 1: termx.remote.auth.v1.ScopeKind
	(*AuthEnvelope)(nil),              // 2: termx.remote.auth.v1.AuthEnvelope
	(*DeviceHello)(nil),               // 3: termx.remote.auth.v1.DeviceHello
	(*CapabilityOpen)(nil),            // 4: termx.remote.auth.v1.CapabilityOpen
	(*ScopeSummary)(nil),              // 5: termx.remote.auth.v1.ScopeSummary
	(*CapabilityAccepted)(nil),        // 6: termx.remote.auth.v1.CapabilityAccepted
	(*CapabilityRejected)(nil),        // 7: termx.remote.auth.v1.CapabilityRejected
	(*DeviceHelloSignatureInput)(nil), // 8: termx.remote.auth.v1.DeviceHelloSignatureInput
	(*CapabilityProofInput)(nil),      // 9: termx.remote.auth.v1.CapabilityProofInput
}
var file_remoteauthpb_remote_auth_proto_depIdxs = []int32{
	3, // 0: termx.remote.auth.v1.AuthEnvelope.device_hello:type_name -> termx.remote.auth.v1.DeviceHello
	4, // 1: termx.remote.auth.v1.AuthEnvelope.capability_open:type_name -> termx.remote.auth.v1.CapabilityOpen
	6, // 2: termx.remote.auth.v1.AuthEnvelope.capability_accepted:type_name -> termx.remote.auth.v1.CapabilityAccepted
	7, // 3: termx.remote.auth.v1.AuthEnvelope.capability_rejected:type_name -> termx.remote.auth.v1.CapabilityRejected
	1, // 4: termx.remote.auth.v1.ScopeSummary.kind:type_name -> termx.remote.auth.v1.ScopeKind
	5, // 5: termx.remote.auth.v1.CapabilityAccepted.scope:type_name -> termx.remote.auth.v1.ScopeSummary
	0, // 6: termx.remote.auth.v1.CapabilityRejected.code:type_name -> termx.remote.auth.v1.AuthErrorCode
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_remoteauthpb_remote_auth_proto_init() }
func file_remoteauthpb_remote_auth_proto_init() {
	if File_remoteauthpb_remote_auth_proto != nil {
		return
	}
	file_remoteauthpb_remote_auth_proto_msgTypes[0].OneofWrappers = []any{
		(*AuthEnvelope_DeviceHello)(nil),
		(*AuthEnvelope_CapabilityOpen)(nil),
		(*AuthEnvelope_CapabilityAccepted)(nil),
		(*AuthEnvelope_CapabilityRejected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_remoteauthpb_remote_auth_proto_rawDesc), len(file_remoteauthpb_remote_auth_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_remoteauthpb_remote_auth_proto_goTypes,
		DependencyIndexes: file_remoteauthpb_remote_auth_proto_depIdxs,
		EnumInfos:         file_remoteauthpb_remote_auth_proto_enumTypes,
		MessageInfos:      file_remoteauthpb_remote_auth_proto_msgTypes,
	}.Build()
	File_remoteauthpb_remote_auth_proto = out.File
	file_remoteauthpb_remote_auth_proto_goTypes = nil
	file_remoteauthpb_remote_auth_proto_depIdxs = nil
}
