package shortcut

// DefaultBinding 是内置 shortcut catalog 的一条 scene+key -> action 声明。
// shortcut 是该数据的唯一 owner；input 只能读取并编译，不能维护第二份默认键表。
type DefaultBinding struct {
	Scene  string
	Key    string
	Action string
}

var defaultBindings = []DefaultBinding{
	{Scene: "global", Key: "ctrl-p", Action: "menu.panel"},
	{Scene: "global", Key: "ctrl-r", Action: "menu.resize"},
	{Scene: "global", Key: "ctrl-g", Action: "menu.system"},
	{Scene: "global", Key: "ctrl-o", Action: "menu.floating"},
	{Scene: "global", Key: "ctrl-t", Action: "menu.tab"},
	{Scene: "global", Key: "ctrl-w", Action: "menu.workspace"},
	{Scene: "global", Key: "ctrl-f", Action: "terminal_picker.open"},
	{Scene: "global", Key: "ctrl-v", Action: "copy.enter"},
	{Scene: "global", Key: "page-up", Action: "copy.enter"},

	{Scene: "panel", Key: "x", Action: "panel.close"},
	{Scene: "panel", Key: "w", Action: "panel.close"},
	{Scene: "panel", Key: "d", Action: "panel.detach"},
	{Scene: "panel", Key: "r", Action: "panel.reconnect"},
	{Scene: "panel", Key: "R", Action: "panel.restart"},
	{Scene: "panel", Key: "a", Action: "panel.take_owner"},
	{Scene: "panel", Key: "s", Action: "panel.size_lock"},
	{Scene: "panel", Key: "%", Action: "panel.split_right"},
	{Scene: "panel", Key: "ctrl-d", Action: "panel.split_right"},
	{Scene: "panel", Key: "\"", Action: "panel.split_down"},
	{Scene: "panel", Key: "ctrl-e", Action: "panel.split_down"},
	{Scene: "panel", Key: "X", Action: "panel.kill"},
	{Scene: "panel", Key: "z", Action: "panel.toggle_zoom"},
	{Scene: "panel", Key: "b", Action: "panel.balance"},
	{Scene: "panel", Key: "c", Action: "panel.presentation_card"},
	{Scene: "panel", Key: "p", Action: "panel.presentation_split_line"},
	{Scene: "panel", Key: "n", Action: "panel.focus_next"},
	{Scene: "panel", Key: "N", Action: "panel.focus_prev"},
	{Scene: "panel", Key: "h", Action: "panel.focus_prev"},
	{Scene: "panel", Key: "k", Action: "panel.focus_prev"},
	{Scene: "panel", Key: "l", Action: "panel.focus_next"},
	{Scene: "panel", Key: "j", Action: "panel.focus_next"},
	{Scene: "panel", Key: "left", Action: "panel.focus_prev"},
	{Scene: "panel", Key: "up", Action: "panel.focus_prev"},
	{Scene: "panel", Key: "right", Action: "panel.focus_next"},
	{Scene: "panel", Key: "down", Action: "panel.focus_next"},

	{Scene: "resize", Key: "left", Action: "resize.left"},
	{Scene: "resize", Key: "right", Action: "resize.right"},
	{Scene: "resize", Key: "up", Action: "resize.up"},
	{Scene: "resize", Key: "down", Action: "resize.down"},
	{Scene: "resize", Key: "h", Action: "resize.left"},
	{Scene: "resize", Key: "l", Action: "resize.right"},
	{Scene: "resize", Key: "k", Action: "resize.up"},
	{Scene: "resize", Key: "j", Action: "resize.down"},
	{Scene: "resize", Key: "a", Action: "panel.take_owner"},
	{Scene: "resize", Key: "s", Action: "panel.size_lock"},
	{Scene: "resize", Key: "space", Action: "resize.layout_toggle"},
	{Scene: "resize", Key: "A", Action: "resize.pan_left"},
	{Scene: "resize", Key: "S", Action: "resize.pan_down"},
	{Scene: "resize", Key: "W", Action: "resize.pan_up"},
	{Scene: "resize", Key: "D", Action: "resize.pan_right"},
	{Scene: "resize", Key: "shift-left", Action: "resize.pan_left"},
	{Scene: "resize", Key: "shift-down", Action: "resize.pan_down"},
	{Scene: "resize", Key: "shift-up", Action: "resize.pan_up"},
	{Scene: "resize", Key: "shift-right", Action: "resize.pan_right"},
	{Scene: "resize", Key: "0", Action: "resize.align_left"},
	{Scene: "resize", Key: "$", Action: "resize.align_right"},
	{Scene: "resize", Key: "^", Action: "resize.align_top"},
	{Scene: "resize", Key: "B", Action: "resize.align_bottom"},
	{Scene: "resize", Key: "m", Action: "resize.center"},
	{Scene: "resize", Key: "|", Action: "resize.center_x"},
	{Scene: "resize", Key: "_", Action: "resize.center_y"},
	{Scene: "resize", Key: "r", Action: "resize.layout_reset"},
	{Scene: "resize", Key: "H", Action: "resize.left_large"},
	{Scene: "resize", Key: "L", Action: "resize.right_large"},
	{Scene: "resize", Key: "K", Action: "resize.up_large"},
	{Scene: "resize", Key: "J", Action: "resize.down_large"},
	{Scene: "resize", Key: "b", Action: "panel.balance"},
	{Scene: "resize", Key: "=", Action: "panel.balance"},

	{Scene: "system", Key: "h", Action: "system.toggle_header"},
	{Scene: "system", Key: "f", Action: "system.toggle_footer"},
	{Scene: "system", Key: "c", Action: "system.clear_toasts"},
	{Scene: "system", Key: "T", Action: "system.close_toast"},
	{Scene: "system", Key: "p", Action: "system.open_terminal_pool"},
	{Scene: "system", Key: "m", Action: "system.open_terminal_pool"},
	{Scene: "system", Key: "t", Action: "system.open_terminal_pool"},
	{Scene: "system", Key: "w", Action: "system.open_workbench_tree"},
	{Scene: "system", Key: "e", Action: "system.open_connections"},
	{Scene: "system", Key: "l", Action: "system.toggle_shortcut_lock"},
	{Scene: "system", Key: ":", Action: "system.open_prompt"},
	{Scene: "system", Key: "?", Action: "system.open_help"},
	{Scene: "system", Key: "q", Action: "system.quit"},

	{Scene: "floating", Key: "n", Action: "floating.new"},
	{Scene: "floating", Key: "o", Action: "floating.overview"},
	{Scene: "floating", Key: "1", Action: "floating.summon.1"},
	{Scene: "floating", Key: "2", Action: "floating.summon.2"},
	{Scene: "floating", Key: "3", Action: "floating.summon.3"},
	{Scene: "floating", Key: "4", Action: "floating.summon.4"},
	{Scene: "floating", Key: "5", Action: "floating.summon.5"},
	{Scene: "floating", Key: "6", Action: "floating.summon.6"},
	{Scene: "floating", Key: "7", Action: "floating.summon.7"},
	{Scene: "floating", Key: "8", Action: "floating.summon.8"},
	{Scene: "floating", Key: "9", Action: "floating.summon.9"},
	{Scene: "floating", Key: "f", Action: "system.open_terminal_picker"},
	{Scene: "floating", Key: "a", Action: "floating.take_owner"},
	{Scene: "floating", Key: "x", Action: "floating.close"},
	{Scene: "floating", Key: "z", Action: "floating.collapse"},
	{Scene: "floating", Key: "m", Action: "floating.collapse"},
	{Scene: "floating", Key: "c", Action: "floating.center"},
	{Scene: "floating", Key: "v", Action: "floating.toggle_all"},
	{Scene: "floating", Key: "=", Action: "floating.fit"},
	{Scene: "floating", Key: "s", Action: "floating.auto_fit"},
	{Scene: "floating", Key: "h", Action: "floating.move_left"},
	{Scene: "floating", Key: "l", Action: "floating.move_right"},
	{Scene: "floating", Key: "k", Action: "floating.move_up"},
	{Scene: "floating", Key: "j", Action: "floating.move_down"},
	{Scene: "floating", Key: "left", Action: "floating.move_left"},
	{Scene: "floating", Key: "right", Action: "floating.move_right"},
	{Scene: "floating", Key: "up", Action: "floating.move_up"},
	{Scene: "floating", Key: "down", Action: "floating.move_down"},
	{Scene: "floating", Key: "H", Action: "floating.narrow"},
	{Scene: "floating", Key: "L", Action: "floating.wide"},
	{Scene: "floating", Key: "K", Action: "floating.short"},
	{Scene: "floating", Key: "J", Action: "floating.tall"},

	{Scene: "tab", Key: "c", Action: "tab.create"},
	{Scene: "tab", Key: "n", Action: "tab.next"},
	{Scene: "tab", Key: "l", Action: "tab.next"},
	{Scene: "tab", Key: "]", Action: "tab.next"},
	{Scene: "tab", Key: "p", Action: "tab.previous"},
	{Scene: "tab", Key: "h", Action: "tab.previous"},
	{Scene: "tab", Key: "[", Action: "tab.previous"},
	{Scene: "tab", Key: "1", Action: "tab.jump.1"},
	{Scene: "tab", Key: "2", Action: "tab.jump.2"},
	{Scene: "tab", Key: "3", Action: "tab.jump.3"},
	{Scene: "tab", Key: "4", Action: "tab.jump.4"},
	{Scene: "tab", Key: "5", Action: "tab.jump.5"},
	{Scene: "tab", Key: "6", Action: "tab.jump.6"},
	{Scene: "tab", Key: "7", Action: "tab.jump.7"},
	{Scene: "tab", Key: "8", Action: "tab.jump.8"},
	{Scene: "tab", Key: "9", Action: "tab.jump.9"},
	{Scene: "tab", Key: "r", Action: "tab.rename"},
	{Scene: "tab", Key: "x", Action: "tab.close"},
	{Scene: "tab", Key: "X", Action: "tab.kill"},

	{Scene: "workspace", Key: "c", Action: "workspace.create"},
	{Scene: "workspace", Key: "n", Action: "workspace.next"},
	{Scene: "workspace", Key: "l", Action: "workspace.next"},
	{Scene: "workspace", Key: "]", Action: "workspace.next"},
	{Scene: "workspace", Key: "p", Action: "workspace.previous"},
	{Scene: "workspace", Key: "h", Action: "workspace.previous"},
	{Scene: "workspace", Key: "[", Action: "workspace.previous"},
	{Scene: "workspace", Key: "r", Action: "workspace.rename"},
	{Scene: "workspace", Key: "x", Action: "workspace.delete"},
	{Scene: "workspace", Key: "t", Action: "system.open_workbench_tree"},
	{Scene: "workspace", Key: "f", Action: "system.open_workbench_tree"},
	{Scene: "workspace", Key: "s", Action: "system.open_workbench_tree"},

	{Scene: "copy", Key: "page-up", Action: "copy.request_older"},
	{Scene: "copy", Key: "page-down", Action: "copy.request_newer"},
	{Scene: "copy", Key: "home", Action: "copy.line_start"},
	{Scene: "copy", Key: "end", Action: "copy.line_end"},
	{Scene: "copy", Key: "left", Action: "copy.cursor_left"},
	{Scene: "copy", Key: "right", Action: "copy.cursor_right"},
	{Scene: "copy", Key: "down", Action: "copy.cursor_down"},
	{Scene: "copy", Key: "up", Action: "copy.cursor_up"},
	{Scene: "copy", Key: "enter", Action: "copy.accept"},
	{Scene: "copy", Key: "h", Action: "copy.cursor_left"},
	{Scene: "copy", Key: "l", Action: "copy.cursor_right"},
	{Scene: "copy", Key: "j", Action: "copy.cursor_down"},
	{Scene: "copy", Key: "k", Action: "copy.cursor_up"},
	{Scene: "copy", Key: "g", Action: "copy.oldest"},
	{Scene: "copy", Key: "G", Action: "copy.newest"},
	{Scene: "copy", Key: "u", Action: "copy.half_page_older"},
	{Scene: "copy", Key: "d", Action: "copy.half_page_newer"},
	{Scene: "copy", Key: "space", Action: "copy.mark"},
	{Scene: "copy", Key: "y", Action: "copy.copy_selection"},
	{Scene: "copy", Key: "/", Action: "copy.search_start"},
	{Scene: "copy", Key: "n", Action: "copy.search_next"},
	{Scene: "copy", Key: "N", Action: "copy.search_previous"},
	{Scene: "copy", Key: "H", Action: "menu.clipboard_history"},
	{Scene: "copy", Key: "p", Action: "clipboard.paste_latest"},
	{Scene: "copy", Key: "P", Action: "clipboard.paste_system"},

	{Scene: "terminal_picker", Key: "enter", Action: "terminal_picker.attach"},
	{Scene: "terminal_picker", Key: "tab", Action: "terminal_picker.split"},
	{Scene: "terminal_picker", Key: "ctrl-e", Action: "terminal_picker.edit"},
	{Scene: "terminal_picker", Key: "ctrl-k", Action: "terminal_picker.kill"},
	{Scene: "terminal_picker", Key: "ctrl-x", Action: "terminal_picker.delete"},

	{Scene: "terminal_pool", Key: "enter", Action: "terminal_pool.attach"},
	{Scene: "terminal_pool", Key: "ctrl-t", Action: "terminal_pool.attach_tab"},
	{Scene: "terminal_pool", Key: "ctrl-o", Action: "terminal_pool.attach_float"},
	{Scene: "terminal_pool", Key: "ctrl-r", Action: "terminal_pool.restart"},
	{Scene: "terminal_pool", Key: "ctrl-e", Action: "terminal_pool.edit"},
	{Scene: "terminal_pool", Key: "ctrl-k", Action: "terminal_pool.kill"},
	{Scene: "terminal_pool", Key: "ctrl-x", Action: "terminal_pool.delete"},

	{Scene: "connections", Key: "enter", Action: "connections.edit"},
	{Scene: "connections", Key: "space", Action: "connections.toggle"},
	{Scene: "connections", Key: "r", Action: "connections.refresh"},

	{Scene: "workbench_tree", Key: "enter", Action: "workbench_tree.open"},
	{Scene: "workbench_tree", Key: "ctrl-n", Action: "workbench_tree.new"},
	{Scene: "workbench_tree", Key: "ctrl-r", Action: "workbench_tree.rename"},
	{Scene: "workbench_tree", Key: "ctrl-x", Action: "workbench_tree.delete"},
	{Scene: "workbench_tree", Key: "ctrl-d", Action: "workbench_tree.detach"},
	{Scene: "workbench_tree", Key: "ctrl-z", Action: "workbench_tree.zoom"},

	{Scene: "clipboard_history", Key: "enter", Action: "clipboard_history.paste"},
	{Scene: "clipboard_history", Key: "ctrl-n", Action: "clipboard_history.new"},
	{Scene: "clipboard_history", Key: "ctrl-e", Action: "clipboard_history.edit"},
	{Scene: "clipboard_history", Key: "ctrl-x", Action: "clipboard_history.delete"},

	{Scene: "floating_overview", Key: "enter", Action: "floating_overview.open"},
	{Scene: "floating_overview", Key: "1", Action: "floating.summon.1"},
	{Scene: "floating_overview", Key: "2", Action: "floating.summon.2"},
	{Scene: "floating_overview", Key: "3", Action: "floating.summon.3"},
	{Scene: "floating_overview", Key: "4", Action: "floating.summon.4"},
	{Scene: "floating_overview", Key: "5", Action: "floating.summon.5"},
	{Scene: "floating_overview", Key: "6", Action: "floating.summon.6"},
	{Scene: "floating_overview", Key: "7", Action: "floating.summon.7"},
	{Scene: "floating_overview", Key: "8", Action: "floating.summon.8"},
	{Scene: "floating_overview", Key: "9", Action: "floating.summon.9"},
	{Scene: "floating_overview", Key: "s", Action: "floating_overview.show_all"},
	{Scene: "floating_overview", Key: "c", Action: "floating_overview.collapse_all"},
	{Scene: "floating_overview", Key: "x", Action: "floating.close"},

	{Scene: "prompt", Key: "enter", Action: "prompt.submit"},

	{Scene: "help", Key: "up", Action: "help.previous"},
	{Scene: "help", Key: "down", Action: "help.next"},
	{Scene: "help", Key: "page-up", Action: "help.page_up"},
	{Scene: "help", Key: "page-down", Action: "help.page_down"},
	{Scene: "help", Key: "home", Action: "help.first"},
	{Scene: "help", Key: "end", Action: "help.last"},
	{Scene: "help", Key: "enter", Action: "help.close"},
}

// DefaultBindings 返回内置 shortcut binding 的只读副本。
func DefaultBindings() []DefaultBinding {
	out := make([]DefaultBinding, len(defaultBindings))
	copy(out, defaultBindings)
	return out
}
